### ISSUE TITLE
OOM: Out of memory with library engine with Node.js v16 in test suite

### ISSUE THREAD

**Issue by Jolg42** [prisma/prisma#10183]
See https://github.com/prisma/prisma/pull/10020

One error in client https://github.com/prisma/prisma/runs/4047797484?check_suite_focus=true#step:9:1342
```
PASS src/__tests__/integration/happy/float-napi/test.ts (18.813 s)
  ✓ float-node-api (11321 ms)


<--- Last few GCs --->

[4482:0x61412c0]   500507 ms: Scavenge (reduce) 1967.7 (2082.7) -> 1966.8 (2082.7) MB, 1.9 / 0.0 ms  (average mu = 0.116, current mu = 0.056) allocation failure 
[4482:0x61412c0]   500523 ms: Scavenge (reduce) 1967.9 (2082.7) -> 1967.5 (2082.7) MB, 2.6 / 0.0 ms  (average mu = 0.116, current mu = 0.056) allocation failure 
[4482:0x61412c0]   500537 ms: Scavenge (reduce) 1968.1 (2082.7) -> 1967.9 (2083.2) MB, 3.4 / 0.0 ms  (average mu = 0.116, current mu = 0.056) allocation failure 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb02ec0 node::Abort() [node]
 2: 0xa181fb node::FatalError(char const*, char const*) [node]
 3: 0xced88e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xcedc07 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xea5ea5  [node]
 6: 0xea6986  [node]
 7: 0xeb48be  [node]
 8: 0xeb5300 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xeb827e v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xe793e2 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
11: 0xe719f4 v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawWithImmortalMap(int, v8::internal::AllocationType, v8::internal::Map, v8::internal::AllocationAlignment) [node]
12: 0xe73710 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [node]
13: 0xe7b53d v8::internal::Factory::NewStringFromUtf8(v8::base::Vector<char const> const&, v8::internal::AllocationType) [node]
14: 0xcfc625 v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::NewStringType, int) [node]
15: 0xbed579  [node]
16: 0xadd3f5  [node]
17: 0x157c42c  [node]
Aborted (core dumped)
 ELIFECYCLE  Command failed with exit code 134.
```

We should investigate to understand where this comes from.

**Comment by aqrln** [comment]
I believe this should be fixed now after https://github.com/prisma/prisma-engines/pull/3040 and https://github.com/prisma/prisma/pull/14174.

**Comment by samchon** [comment]
@aqrln Still occurs in 4.16.2

**Comment by aqrln** [comment]
@samchon please open a new issue so we could investigate. Also, does it occur with latest 5.0.0?

**Comment by samchon** [comment]
@aqrln Yes, it still occurs in v5. Such bug being occurred since table count over 120.

By the way, as current repo is private commercial, it is hard to make a reproducible repo.

I'll write an issue immediately, and consider how to make reproducible later.
