### ISSUE TITLE
Prisma client cannot find datamodel path ("schema.prisma")

### ISSUE THREAD

**Issue by 0x77dev** [prisma/prisma#10512]
### Bug description

In a monorepo environment, Prisma generates into the `prisma` folder at service root, but when the `PrismaClient` instance is created, it tries to read the schema file in random subdirectories.

That happened after upgrading Prisma to `3.x`.

### How to reproduce

Here is a repo with an example of project configuration:

https://github.com/0x77dev/prisma-datamodel-path

To reproduce:
```shell
yarn install
yarn reproduce
```

### Expected behavior

Schema to be accessed at `join(process.cwd(), 'prisma', 'schema.prisma')`.

### Schema:

```prisma
generator client {
  provider = "prisma-client-js"
  output   = "."
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id String @id @default(uuid()) @db.Uuid
}
```

### PrismaClient
```typescript
export const get = async (): Promise<PrismaClient> => {
    const { dbURL } = init()

    const { PrismaClient } = await import(join(process.cwd(), 'prisma'))

    const prisma = new PrismaClient({
      datasources: { db: { url: dbURL } },
      log:
        process.env.NODE_ENV === 'production' ? [] : ['query', 'info', 'warn'],
      rejectOnNotFound,
    })

    await prisma.$connect()

    return prisma
}
```

### Environment & setup

- OS: Ubuntu (docker image `ubuntu:latest`) (`Linux aef42a236834 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`) or macOS Monterey `v12.0.1` (`Darwin 3c7d0a05571a.lan 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64`)
- Database: `PostgreSQL 12`
- Node.js version: `v16.13.0`

### Prisma Version

```
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
```

**Comment by 0x77dev** [comment]
Maybe there is a way to specify `datamodelPath` for the engine 🤔

but the Prisma client threw an error with an invalid config for the `datamodelPath` key.

**Comment by carlo23666** [comment]
If im not wrong you can add the schema.prisma url to your packaje.json, as "prisma": {"schema": "your/parth/schema.prisma"}, hope that works for you.

**Comment by 0x77dev** [comment]
@carlo23666 Has no effect

**Comment by 0x77dev** [comment]
@carlo23666 Has no effect

**Comment by 0x77dev** [comment]
In generated output `runtime/index.js`
`getPrismaClient` function, argument `config2`
contains: 

```javascript
{
  generator: {
    name: 'client',
    provider: { fromEnvVar: null, value: 'prisma-client-js' },
    output: {
      value: '/Users/.../prisma-reproduce/packages/sample-service/prisma',
      fromEnvVar: null
    },
    config: { engineType: 'library' },
    binaryTargets: [],
    previewFeatures: [],
    isCustomOutput: true
  },
  relativeEnvPaths: { rootEnvPath: null },
  relativePath: '',
  clientVersion: '3.5.0',
  engineVersion: '78a5df6def6943431f4c022e1428dbc3e833cf8e',
  datasourceNames: [ 'db' ],
  activeProvider: 'postgresql',
  document: {
    datamodel: { enums: [], models: [Array] },
    schema: {
      inputObjectTypes: [Object],
      outputObjectTypes: [Object],
      enumTypes: [Object]
    },
    mappings: { modelOperations: [Array], otherOperations: [Object] }
  },
  dirname: '/Users/.../prisma-reproduce/packages/sample-service/node_modules'
}
```

but `process.cwd()` is `/Users/.../prisma-reproduce/packages/sample-service`

Is `config2.dirname` correct 🤔 , and is it possible to override it?

**Comment by 0x77dev** [comment]
Workaround: 

```diff
generator client {
  provider = "prisma-client-js"
-   output   = "."
+   output   = "client"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id String @id @default(uuid()) @db.Uuid
}
```

**Comment by carlo23666** [comment]
Your config2.dirname is pointing to node_modules client, and on your schema.prisma you are creating the client on the same dir than the schema is, comment the output line for prisma to create client on node_modules

**Comment by 0x77dev** [comment]
It is not possible in our case, we don't want to generate prisma in node modules

**Comment by Faithfinder** [comment]
We're experiencing the same problem. I've tried bumping prisma versions one by one and tracked it down to upgrade from `3.0.2` to `3.1.1`. Looked at the diff between the tags, but didn't find a change that looks suspicious.

We generate prisma client as a separate package to be used in different apps.
i.e there's a `prisma-client` package in the monorepo that looks like this:

```
//prisma.schema
generator client {
  provider = "prisma-client-js"
  output   = "./dist"
}
// rest
```

```json
//package.json
{
    "name": "prisma-client",
    "main": "dist/index.js",
    "types": "dist/index.d.ts",
    "scripts": {
        "build": "prisma generate",
    },
    "devDependencies": {
        "prisma": "3.0.2"
    },
    "dependencies": {
        "@prisma/client": "3.0.2"
    }
}
```

**Comment by pantharshit00** [comment]
I can reproduce this. I will mark it as a bug for now.

**Comment by cesconix** [comment]
I try to fix it with PR #11829.

**Comment by millsp** [comment]
Fixed via https://github.com/prisma/prisma/pull/12427

**Comment by TheVoid-0** [comment]
Hello guys, can't figure it out if it's the same issue or not.

I tried creating a client in a custom path with the @prisma/client@dev but when loading the created client it throws 
`ENOENT: no such file or directory, open 'D:\development\<project-workspace>\node_modules\.prisma\client\schema.prisma'`. 

this is the schema used to generate the client
```prisma

generator client {
  provider        = "prisma-client-js"
  output          = "./client"
  previewFeatures = ["interactiveTransactions"]
  binaryTargets = ["linux-musl", "darwin", "windows"]
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```
I use this to generate a npm private library because I need multiple prisma clients with different schemas, so I import each of them from one library:
```ts

const client1 = await import('@myorg/prisma1').PrismaClient
const client2 = await import('@myorg/prisma2').PrismaClient

const prismaClient1 = new client({ datasources: { db: { url: this.prepareUrl(factoryOptions) } } })
```

But upon instantiating any one of them it produces that ENOENT error.

I'm sorry if this is not related, but anyone could give me a hand?

**Comment by Jolg42** [comment]
Hi @TheVoid-0 !

Could you [create a new issue?](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml) The template will help fill out what we need to attempt a reproduction.

**Comment by nvsd** [comment]
> We're experiencing the same problem. I've tried bumping prisma versions one by one and tracked it down to upgrade from `3.0.2` to `3.1.1`. Looked at the diff between the tags, but didn't find a change that looks suspicious.
> 
> We generate prisma client as a separate package to be used in different apps. i.e there's a `prisma-client` package in the monorepo that looks like...

I have this exact same setup and I'm still getting this issue on `@prisma/client@dev`.

Wherever I import prisma it looks in that directory for the schema.prisma file.

**Comment by Jolg42** [comment]
Hi @nvsd 

Could you [create a new issue?](https://github.com/prisma/prisma/issues/new?assignees=&labels=kind%2Fbug&template=bug_report.yml) The template will help fill out what we need to attempt a reproduction.

It would be helpful because it's very hard in an old and long issue to say what `this exact same setup` means. And you might have slightly different things, like a different version.

**Comment by klippx** [comment]
Workaround: Use a tool such as https://www.npmjs.com/package/copyfiles to manually copy `schema.prisma` over from `src/` to `dist/` folder as part of the build step in `package.json`:

```package.json
    "build": "yarn prisma:generate && yarn tsc && yarn prisma:copy",
    "prisma:copy": "copyfiles -u 2 src/prisma/schema.prisma dist/prisma/generated/client/",
```
