### ISSUE TITLE
Browser-Importable Typings

### ISSUE THREAD

**Issue by xlxAciDxlx** [prisma/prisma#1272]
Hey all! I'm currently working on building an API using prisma2, and a website using React. Everything works fine until I go to load a type in React. Say for example I have a `Category` model, and I want to load that in a browser (since the types are already there) - I'm currently unable to do this.

_Method of import:_
```ts
import { Command } from "@prisma2/photon";
```

_Error:_
```
C:\Code\project\node_modules\@prisma\photon\runtime\index.js
Cannot find module: 'readline'. Make sure this package is installed.
```

Are there any plans to make it so types (I don't need the specific methods like `findMany`, etc) are exposable/usable in a browser environment? Or is there any way I can work around this problem if browser support isn't planned any time soon? Aside from manually writing my own types, ideally.

**Comment by pantharshit00** [comment]
I am marking this as a feature but ideally, you should generate typing from the API layer instead of relying on the database typings. They are generally not a 1:1 map.

**Comment by xlxAciDxlx** [comment]
Sorry, but I'm not sure what you mean by "generate typings from the API layer". While I can see the types may not be a 1:1 map, would they not be sufficient enough on the Client-side to use as a rough guideline for specifying data to send to the API?

I have a `Request` class (async data handler - handles GET, POST, etc to my API) that I could manually specify data for certain endpoints, but it'd seem redundant to have to do that when I already have the typings from the database.

**Comment by bstro** [comment]
Check out this [tweet](https://twitter.com/drosenwasser/status/1214355095594266624).

This functionality is available in `typescript@next` and I am able to import type information from the @prisma package like so:

`import type {MyCoolFooType, MyCoolBarType} from '@prisma/photon'` without requiring the entire module into your browserland code.

Disclaimer: I'm still wrapping my head around this, I don't have it working 100% yet in my CRA app.

**Comment by xlxAciDxlx** [comment]
The biggest hindering factor right now is that `index.d.ts` in `photon` always imports extra into the types.

Example (line 1 of `index.d.ts`):
```ts
import { DMMF, DMMFClass, Engine } from './runtime';
```

Results in `runtime/index.js` being imported, which then tries to import the `readline` package.

I'm theorizing here, but it seems like if those imports/declarations were split off of the _index_ type definitions, it'd probably be fine (at least loosely looking at the current types; haven't deep-dove into them yet)

---

Also, the `typescript@next` and `type` export, unfortunately, makes no difference. I'm not 100% sure if it's because of the above reasoning, but that's my current theory.

**Comment by bstro** [comment]
Ah, that does look like a potential snag. Thanks! I'll keep banging my head against the wall and see if I can come up with anything.

**Comment by xlxAciDxlx** [comment]
Please do let me know if you figure anything out! Definitely open to other ways of doing things, so long as it works! Haha

**Comment by bstro** [comment]
Having some success right now with `export type MyCoolFooType = import('@prisma/photon').MyCoolFooType`

**Comment by xlxAciDxlx** [comment]
Unfortunately for me, my use case is in `create-react-app`, so even after trying
`export type { Command } from "@prisma/photon";`
and
`export type Command = import("@prisma/photon").Command`

I still get faulted by the `readline` error :/ I guess for now I can just manually specify types, though ideally, it'd be nice to have them provided by Prisma as I already do the work (for lack of a better word) of specifying the schema.

**Comment by bstro** [comment]
Odd. I am also using `create-react-app` and things are working for me. I wonder what is the difference between our use cases.

**Comment by xlxAciDxlx** [comment]
Possibly different versions of a dependency?

root dependencies (I'm working in a monorepo):
- typescript@next: ^3.8.0-dev.20200108

`api` dependencies:
- @prisma/photon: ^2.0.0-preview019

`website` (create-react-app) dependencies:
- react: ^16.12.0
- react-dom: ^16.12.0
- react-router-dom: ^5.1.2

---

FWIW, I'm also not using an ejected or modified config for `create-react-app`. Not sure if you are or not.

**Comment by bstro** [comment]
Also monorepo, also unejected create-react-app
react: `16.10.2`
react-scripts: `3.3.0`
typescript: `3.7.4`
@prisma/photon: `2.0.0-preview018.2`

**Comment by pierreyves-lebrun** [comment]
> Are there any plans to make it so types (I don't need the specific methods like `findMany`, etc) are exposable/usable in a browser environment? Or is there any way I can work around this problem if browser support isn't planned any time soon? Aside from manually writing my own types, ideally.

You can use [GraphQL code generator](https://graphql-code-generator.com/docs/plugins/typescript-react-apollo) for that. It will generate all typings on the top of creating ready to use queries/mutations.

**Comment by pantharshit00** [comment]
Yes, that is what I meant. You should generate the frontend typing from API layer using tool like GraphQL code generator. That will ensure better type safety for your frontend.

Also, looks like Typescript will enable to you to import types in 3.8 so this might already get addressed.

**Comment by xlxAciDxlx** [comment]
I should have specified sooner that I'm using the REST setup, not GraphQL. But out of curiosity, I set up a basic GraphQL setup (I've been meaning to learn GraphQL/dig into it for a while now) and I'm confused about how to tie everything together. I have codegen configured and working, though I seem to not be able to use the `schema.graphql` to generate the types, and have to manually create a `query.graphql` to get query and mutation types to work (which leads me to have to write duplicate types again, anyway).

Am I missing a step somewhere? I generate to an `API.tsx` file in my `website` directory - the file is there, but without me _manully_ specifying queries and mutations in a `*.graphql` file, they don't seem to get picked up (despite being generated into `schema.graphql`)

**Comment by Suniron** [comment]
I have the same problem :'(.

**Comment by FredericLatour** [comment]
@xlxAciDxlx Hi, did you find a way around this matter.   
It seems like a major concern to me. What's the point of Prisma 2 if I can't get to easily share types especially in basic CRUD scenarios where the added value at the server level only in not really big? 
However, being able to expose both Query types and Model types is a real plus.

**Comment by xlxAciDxlx** [comment]
Unfortunately, I had not found a good solution nor workaround. Even if I were to try to find a workaround for the sake of others, I'm unable to even use Prisma with my preferred database (MySQL) at all on my system due to [this issue](https://github.com/prisma/migrate/issues/339) still being present.

**Comment by thebiglabasky** [comment]
Hi @xlxAciDxlx,
As of today, the generated types are available by default in `/node_modules/.prisma/index.d.ts`
You could copy these types on the client side (even [customize where the generated types go](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/generating-prisma-client#specifying-a-custom-output-path) before copying the file) so that these can be imported from another place.
This would come with a lot of other types but would do the trick I believe.

**Comment by IanMitchell** [comment]
Just ran into this as well! It would be nice to import the values directly for projects not using TypeScript, and not just rely on typings for this functionality. I have a situation where I want to do an authorization check on a page, which means validating a session with a minimum required role - hardcoding this string works (or sending it via `getStaticProps`) but it would be preferable if I could just import an enum to use directly.

**Comment by joaopaulobdac** [comment]
@IanMitchell Me too. I can import types without any problems using `import type` because typescript removes them before webpack compilation, but I can't use enums values on the frontend without webpack trying to bundle prisma. Maybe a webpack/babel plugin could extract the enum into a standalone file before compilation?

**Comment by flybayer** [comment]
This is a notable UX issue in Blitz apps.

I think you could fix this by generating both a server entry point and a browser entry point, where the browser entry point only has the enum and client-safe code.

**Comment by JuanM04** [comment]
This issue should be closed. It was resolved in v2.13.0

**Comment by matthewmueller** [comment]
I think this one can be closed with https://github.com/prisma/prisma/releases/tag/2.13.0. See: Import types and enums in the browser. Let us know if you run into any issues!

**Comment by joaopaulobdac** [comment]
@matthewmueller I'm on 2.14.0 and the bundler still tries to import modules from node like "fs" and "path" along when I try to use a enum from prisma. I tried deleting node_modules and regenerating everything from scratch but the enum is still in a generated file that requires modules from Node.js. Do I need to enable something?

**Comment by joaopaulobdac** [comment]
Just to be clear, I could always use TS definitions from prisma without any problems because these types come from the generated `index.d.ts` file which is removed before bundling. Enums that are the problem. They are just JS objects, so they are imported from the generated `index.js` file, which includes node.js `require` statements.

**Comment by matthewmueller** [comment]
@joaopaulobdac interesting. That should be solved in `2.13.0`. Do you mind sharing an example import and the require statements you're seeing in the code?

**Comment by joaopaulobdac** [comment]
`./prisma/schema.prisma`
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  output   = "../generated"
}

model Post {
  id        Int      @id @default(autoincrement())
  title     String
  content   Letters?
  published Boolean  @default(false)
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

enum Letters {
  a
  b
  c
}
```

`./script.ts`
```ts
import { Letters } from './generated'

console.log(Letters)
```

Bundling
```console
$ yarn add esbuild

$ yarn esbuild --bundle script.ts
 > generated/index.js: error: Could not resolve "path" (set platform to "node" when building for node)
    20 │ const path = require('path')
       ╵                      ~~~~~~

 > generated/runtime/index.js: warning: Define "process.env.NODE_ENV" when bundling for the browser
    42005 │     if (process.env.NODE_ENV !== "test") {
          ╵         ~~~~~~~~~~~~~~~~~~~~

 > generated/runtime/index.js: error: Could not resolve "fs" (set platform to "node" when building for node)
    39 │   var fs3 = require("fs");
       ╵                     ~~~~

 > generated/runtime/index.js: error: Could not resolve "path" (set platform to "node" when building for node)
    160 │   var path3 = require("path");
        ╵                       ~~~~~~

 > generated/runtime/index.js: error: Could not resolve "child_process" (set platform to "node" when building for node)
    482 │   var cp = require("child_process");
        ╵                    ~~~~~~~~~~~~~~~

 > generated/runtime/index.js: error: Could not resolve "stream" (set platform to "node" when building for node)
    509 │   var stream = require("stream");
        ╵                        ~~~~~~~~

 > generated/runtime/index.js: error: Could not resolve "util" (set platform to "node" when building for node)
    510 │   var util2 = require("util");
        ╵                       ~~~~~~

 > generated/runtime/index.js: error: Could not resolve "os" (set platform to "node" when building for node)
    1703 │   var os2 = require("os");
         ╵                     ~~~~

 > generated/runtime/index.js: error: Could not resolve "tty" (set platform to "node" when building for node)
    1704 │   var tty = require("tty");
         ╵                     ~~~~~

 > generated/runtime/index.js: error: Could not resolve "crypto" (set platform to "node" when building for node)
    3556 │   var crypto_1 = __importDefault2(require("crypto"));
         ╵                                           ~~~~~~~~

 > generated/runtime/index.js: error: Could not resolve "assert" (set platform to "node" when building for node)
    8258 │     var assert = require("assert");
         ╵                          ~~~~~~~~
```

**Comment by joaopaulobdac** [comment]
I took a peek at the `generated` folder and found a `index-browser.js` file. But when importing the enum TS gives this error
```ts
// Module '"./generated/runtime/index-browser"' has no exported member 'Letters'.
import { Letters } from './generated/runtime/index-browser'
```

**Comment by pantharshit00** [comment]
Hey @joaopaulobdac 

Please open a new issue with these details. This issue tracked the browser build which is now shipped. We can make necessary changes to it if it is not working for your use case so please open a new issue.

**Comment by somonek** [comment]
I'm still experiencing this with 2.26.0. However I could solve it this way:
```javascript
new webpack.NormalModuleReplacementPlugin(
      /(.*)orm\/prisma\/index.js(\.*)/,
      function (resource) {
        resource.request = resource.request.replace(
          'orm/prisma/index.js',
          'orm/prisma/index-browser.js'
        );
      }
    ),
```

I'm bundling the prisma client with its schema and all, in a dedicated package which I import from different apps. I called this package `@myScope/orm` and then the prisma is bundled in a prisma folder inside this package, so my imports look like this: `import { Prisma, WhateverEnum, PrismaClient, User, Etc } from '@myScope/orm/prisma';`. Therefore in the regex above I'm basically targeting my package, so webpack pulls stuff from `index-browser.js` instead `index.js`. On non client side apps all imports work just fine.

**Comment by joaopaulobdac** [comment]
Hi @smartymoon, I could not fix this issue. I was able to import types without problems, but not enums. You can open an issue and see if this can be fixed.

**Comment by smartymoon** [comment]
@joaopaulobdac  thank you for reply, have a nice day

**Comment by Frankitch** [comment]
Hi @joaopaulobdac  @smartymoon @pantharshit00, I am also facing this issue that seems to occur only when prisma client is generated in a custom output.

To me, it's due to the fact that in the case of a custom output there is not the `package.json` file that allows webpack (?) to get the appropriate file.

Prisma client generated in the default folder:
![Capture d’écran de 2022-03-11 13-50-45](https://user-images.githubusercontent.com/6025759/157877342-67b344f0-c262-4024-a943-3144886b0fcd.png)

Prisma client generated in a custom folder (`output   = "../node_modules/.prisma-app1"`):
![Capture d’écran de 2022-03-11 13-53-02](https://user-images.githubusercontent.com/6025759/157877262-88084b0a-7eb7-4bc1-992f-f1a40b9996bf.png)

There is no `package.json` in the latter case.

If I copy the `package.json` file in the custom output, it works!

Content of the package.json:
```
{
  "name": ".prisma/client",
  "main": "index.js",
  "types": "index.d.ts",
  "browser": "index-browser.js"
}
```


After some search, it seems that this `package.json` is no more added to the Prisma client on purpose since release 2.11 to fix  #4048 (fixed by @timsuchanek).

Instead of removing `package.json`, could it be possible to rename the `name` property in the `package.json` file as [suggested by #4048 issuer](https://github.com/prisma/prisma/issues/4048#issue-730273330)?

**Comment by janpio** [comment]
Please open a new issue and describe the full problem there. We will not be able to respond properly in a closed feature request. Thanks.

**Comment by stuart-haas** [comment]
For anyone who is still looking for a solid solution and having a hard time finding one, I wrote up an article on this, and it's been implemented in a production-grade application.

https://dev.to/stuarthaas/client-side-prisma-types-mj
