### ISSUE TITLE
Incorrect platform for CloudLinux OS

### ISSUE THREAD

**Issue by Maxime-J** [prisma/prisma#13977]
### Bug description

On a CloudLinux OS, in my understanding, prisma doesn't use/download the correct engine.
Hence, native target doesn't match the systyem and we can't generate client, nor launch prisma -v

Expected engine should be rhel-openssl-1.0.x, but debian-openssl-1.1.x is used.

I can tweak the files (rhel files named as debian ones) so that prisma -v works
(which confirms that rhel engine should be used)
But can't find a way to make generate work, even with  ``binaryTargets = ["rhel-openssl-1.0.x"]`` in prisma.schema
(may be linked to the implicite native ? https://github.com/prisma/prisma/issues/12691)

**Error logs** :

prisma -v (see below for the working output)
```
Environment variables loaded from .env
Error: Command failed with exit code 127: /home/wufwjymd/nodevenv/drimex/14/lib/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x --version
/home/wufwjymd/nodevenv/drimex/14/lib/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

prisma generate
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Unable to require(`/home/wufwjymd/nodevenv/drimex/14/lib/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node`)
 /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/wufwjymd/nodevenv/drimex/14/lib/node_modules/prisma/libquery_engine-debian-openssl-1.1.x.so.node)
```

### How to reproduce

Can be reproduced every time in a Node.js environnement provided by Planethoster

### Environment & setup

- OS: CloudLinux , kernel version leads to CloudLinux 7 (that's why I tried the rhel engine)
- Node.js version: v14.17.3

### Prisma Version

With files tweaked
```
Environment variables loaded from .env
prisma                  : 3.14.0
@prisma/client          : 3.14.0
Current platform        : debian-openssl-1.1.x
Query Engine (Node-API) : libquery-engine 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at ../nodevenv/drimex/14/lib/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.1.x.so.node)
Migration Engine        : migration-engine-cli 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at ../nodevenv/drimex/14/lib/node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine    : introspection-core 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at ../nodevenv/drimex/14/lib/node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary           : prisma-fmt 2b0c12756921c891fec4f68d9444e18c7d5d4a6a (at ../nodevenv/drimex/14/lib/node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Default Engines Hash    : 2b0c12756921c891fec4f68d9444e18c7d5d4a6a
Studio                  : 0.460.0
```

**Comment by janpio** [comment]
If Prisma detects the wrong platform, there is not much you can do unfortunately - the `binaryTargets` only influences which engine files are downloaded, not which ones are chosen and executed. I don't think we have method to overwrite the platform detection. (This could be a good feature request for exactly such use cases.)

We should fix the detection though. Do you know if there is a simple Docker image available to reproduce this?

**Comment by Maxime-J** [comment]
I'll fill a feature request 👍

Thanks for the info of how it works.

Concerning the detection, I bet the problem is specific to shared setups used by providers, where `/etc/os-release` isn't accessible (saw that on PlanetHoster and o2switch), whereas it is on a simple CloudLinux setup.

Given how prisma detects the distribution
https://github.com/prisma/engines-wrapper/blob/main/packages/get-platform/src/getPlatform.ts#L110
a working way would be to check there the presence of `/usr/sbin/cloudlinux-selector` and return `rhel`.

But maybe it's better to rely on a platform override feature for these edge cases ?

(and I finally manage to circumvent my issue with some tweaking :) )

**Comment by janpio** [comment]
I think we should do both: Fix this concrete case, but also offer a way to instantly workaround similar cases in the future (or cases where it is not viable/possible to fix the actual mis-detection).

**Comment by Maxime-J** [comment]
Ok, I will submit a PR soon.
For that specific case however, there's an added problem,
openssl version reported by `openssl version -v` doesn't match the libraries in `/lib64` and `/usr/lib64`

Current detection prioritizes the version reported by `openssl`,
so in that case, prisma doesn't work if we only fix the distribution check.

So either we prioritizes the library version, which seems to be more logical for a working product
or we check that both versions are identical and return the lib one if there's a difference.
But I don't know if there could be some consequences ? ( will it broke some configs? )

**Comment by janpio** [comment]
Is that a problem with our current, existing implementation? Then this might be worth a new, separate issue where you explain just this problem and why this is undesirable.

**Comment by Maxime-J** [comment]
Issue created, I can provide a test environment if you want to confirm all of that on your end.

**Comment by aenema25** [comment]
I have the exact same issue, can you share how you fixed ?

> I'll fill a feature request 👍
> 
> Thanks for the info of how it works.
> 
> Concerning the detection, I bet the problem is specific to shared setups used by providers, where `/etc/os-release` isn't accessible (saw that on PlanetHoster and o2switch), whereas it is on a simple CloudLinux setup.
> 
> Given how prisma detects the distribution https://github.com/prisma/engines-wrapper/blob/main/packages/get-platform/src/getPlatform.ts#L110 a working way would be to check there the presence of `/usr/sbin/cloudlinux-selector` and return `rhel`.
> 
> But maybe it's better to rely on a platform override feature for these edge cases?
> 
> (and I finally manage to circumvent my issue with some tweaking :) )

Could you share how you fix it ? I have the exact same issue with cloudlinux

**Comment by Maxime-J** [comment]
The way I circumvent that is not sustainable, a bit hacky, and might not suit every case.
So I prefer not to share an exact process, it's better to wait for and override platform detection feature.

Anyway, without the details, it involves editing prisma production files
`nodes_modules\prisma\build\index.js` and `nodes_modules@prisma\client\runtime\index.js`
and download the appropriate engine in `nodes_modules\@prisma\engines` with the download script inside and the corresponding environment variable.

**Comment by benardp** [comment]
I have the same issue on Planethoster. Would you mind sharing some more details about your workaround (or even a patch of those files) until the new feature is available? Thanks!

**Comment by Maxime-J** [comment]
If you only need the Prisma client running on PlanetHoster, I ended up with a more convenient way by building the app (and most importantly generating Prisma client) outside of PlanetHoster with a matching node version, and running the app on it afterwards.

For that, before build you can add `binaryTargets = ["rhel-openssl-1.0.x"]` in `generator client { }` of schema.prisma,
and after the app is built (that means after `prisma generate`), you would have to rename in `node_modules/.prisma/client` folder `libquery_engine-rhel-openssl-1.0.x.so.node` to `libquery_engine-debian-openssl-1.1.x.so.node`

--
The other workaround involved modifying builded/packed js files, that's not clean, but in the files I mentioned in the previous message, the idea is to make the `getPlatform()` function directly returning `rhel-openssl-1.0.x`.
Download script isn't present anymore, so same modification in `nodes_modules/@prisma/engines/dist/postinstall.js`, 
After that in `nodes_modules/@prisma/engines` folder, you would have to run `node scripts/postinstall.js` to download the appropriate engines.

**Comment by benardp** [comment]
After upgrading from version 4.8.1 to 4.9.0, I get the following warning:
`prisma:warn`` Prisma failed to detect the Linux distro in use, and may not work as expected. Defaulting to "debian".`
Can I ignore this message safely on CloudLinux?

**Comment by janpio** [comment]
Some context on that error message: https://github.com/prisma/prisma/issues/17545#issuecomment-1408916970

We do not know yet if everything works as expected on Cluodlinux. Please let us know.

**Comment by benardp** [comment]
Thank you for the context. So far, Prisma seems to be running fine on CloudLinux with the default Debian client.

**Comment by jcubic** [comment]
I'm trying to run Prisma on CloudLinux on Atthost (Polish hosting provider) and got this error:

```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Environment variables loaded from .env
prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
Error: Unable to require(`/home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.0.x.so.node`).
Prisma has detected an incompatible version of the `glibc` C standard library installed in your system. This probably means your system may be too old to run Prisma. Please refer to the documentation about Prisma's system requirements: https://pris.ly/d/system-requirements

Details: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/jcubic/websites/koduj/quiz/node_modules/@prisma/engines/libquery_engine-debian-openssl-1.0.x.so.node)
```

**Comment by aqrln** [comment]
I can't reproduce with CloudLinux 8 (it is correctly detected as `rhel-openssl-1.1.x` for me even on Prisma 3.14) and I can't find a Docker image for CloudLinux 7 anywhere to test. However, assuming the issue did occur on CloudLinux 7, theoretically it would have been fixed by https://github.com/prisma/prisma/pull/17476 in Prisma 4.10.0. Can you confirm if it works for you with the latest Prisma?

**Comment by jcubic** [comment]
@aqrln Do you have the /etc/ file that prisma uses to detect OS? On my hosting, the file was missing.

**Comment by Maxime-J** [comment]
Thanks for your attention @aqrln,
here is a summary about why distribution couldn't and still can't be properly detected in Cloudlinux:

Prisma relies on `/etc/os-release` to detect the distribution used (https://github.com/prisma/prisma/blob/main/packages/get-platform/src/getPlatform.ts#L218).
However, hosters are likely to use CloudLinux with CageFS (https://docs.cloudlinux.com/cloudlinux_os_components/#cagefs), leading that some system files can't be seen from users.
And `/etc/os-release` is one of those files by default.

I can also reproduce with their CloudLinux 8 + CageFS VM image.

As I mentioned previously, a working way could to be check the presence of `/usr/sbin/cloudlinux-selector` if there's an error reading `/etc/os-release`.
I can submit a PR if wanted, but that ticket can also be closed if you judge the case too specific to be handled :)

_And there was also an issue with libssl version, but it was fixed since then_
https://github.com/prisma/prisma/issues/14042

**Comment by aqrln** [comment]
Thank for the additional details @Maxime-J and @jcubic!

So, as far as I understand, there are two separate things we can do here:

1. Prisma should detect RHEL and not Debian in this case. Checking for presence of a CloudLinux-specific file is an option, but a better and more general approach, IMO, is always falling back to RHEL and not Debian when we could not detect the distro. We build RHEL binaries agains older glibc version, and they will work with a wider range of Linux distribution than our Debian binaries — in fact, they should work on all systems where our Debian binaries work too but not the other way around — so it makes more sense to use them as the fallback.
2. We should probably still consider adding a mechanism (likely an environment variable) to override the detected platform. This would be a useful workaround in different edge cases when something goes wrong in the platform detection or if the user wants to override the default behaviour (e.g. when an undesirable version of OpenSSL is picked among the multiple installed ones).

**Comment by aqrln** [comment]
Starting with upcoming Prisma 4.14 release, Debian binaries are now built with glibc 2.17 (as an interim step before merging `debian` and `rhel` targets in a major release). I think this would partially solve the issue for you. Do I understand it correctly that the OpenSSL version would still be detected incorrectly in your case?

**Comment by Maxime-J** [comment]
Thanks ! I believe it would totally solve the issue (there was indeed a problem with OpenSSL version, but it has been fixed #14042).
I'll confirm when 4.14 will be released.

**Comment by Maxime-J** [comment]
OK, all good for me 👍 There is the expected fallback warning but It's working now.

> prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
> Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.

**Comment by aqrln** [comment]
Nice, thanks for confirming!

**Comment by HubertK778** [comment]
Same issue

**Comment by areeb111** [comment]
> Same issue

Please describe more.
Show me your error and i will help you fixing that.

**Comment by Jolg42** [comment]
Hello here,

I'm curious to know if this is still an issue with a recent version of Prisma and CloudLinux.

Please let us know and make sure to provide the versions when commenting.

If you can guide us on how we could try to reproduce this, that would help a lot, I guess there is no easy Dockerfile for this case, and we would need to install the OS as a VM (https://docs.cloudlinux.com/solo/installation/)

Notes: From this comment https://github.com/prisma/prisma/issues/13977#issuecomment-1515274387 it could be this is only affecting CloudLinux v7 and v8 works.
v7 is apparently End-of-Life now (CloudLinux has recently announced the end-of-life for CloudLinux OS 7 (June 30, 2024) from https://blog.cloudlinux.com/)
v8 seems "old" and the current version is v9 I think.

**Comment by Maxime-J** [comment]
Hi @Jolg42,
these reported errors are caused by the shared environnement used by hosters.
This is summarized in that comment https://github.com/prisma/prisma/issues/13977#issuecomment-1518313072
And a resolution was proposed by @aqrln from Prisma and validated in the 5 following comments.

Basically, the distribution still can't be detected correctly but, starting from Prisma 4.14, the fallback engine is compiled so that it's compatible with a wider range of linux distributions.

I had no problem since then in a CloudLinux v7 still used by a well known provider.

Note that the distribution can't be detected correctly in all CloudLinux versions (v8 and v9 also) with a shared setup and CageFS (default config), but it shouldn't prevent Prisma from working correctly now.

I will provide guidelines in the next days to have a VM environnement where you could reproduce.

**Comment by Jolg42** [comment]
@Maxime-J Thanks for your comment!

>Basically, the distribution still can't be detected correctly

I think this is about the warning:
```
prisma:warn Prisma doesn't know which engines to download for the Linux distro "undefined". Falling back to Prisma engines built "debian".
Please report your experience by creating an issue at https://github.com/prisma/prisma/issues so we can add your distro to the list of known supported distros.
```
If so, we actually removed it 

I'll close this, as the fallback/default engine should work as expected, so only a report would be needed if there is an issue, let us know if that's the case.

Note that we changed the message, to make it informational only in https://github.com/prisma/prisma/pull/23243
The updated message `Distro is "${originalDistro}". Falling back to Prisma engines built for "${defaultDistro}".` was shipped in `5.11.0`

With that gone, everything works as expected now for you, if I understand? So the issue could be closed?

**Comment by Jolg42** [comment]
While reading messages again, I'm unsure about the OpenSSL detection.

**Comment by Maxime-J** [comment]
Yes it's all working since Prisma 4.14.
(Technically, distro resolution is failing to resolve as rhel, but the fallback engine is working now)

And OpenSSL issue was resolved in Prisma 4.9 https://github.com/prisma/prisma/issues/14042
(Sorry for the mixup, this issue actually involved two different problems.)

This can be closed 👍 I just let it opened because aqrln was mentioning some interim steps and eventual other things Prisma could do.

Thanks to you and the Prisma team!

**Comment by cefaci** [comment]
Just a post for completeness if somebody else needs it too. Thanks for the help!
Just renaming worked for me and an .env variable would be useful to force what I need.

## Environment & setup
- OS: CloudLinux 7 w/ **OpenSSL 1.0.2k-fips**
- Node.js version: v16.x
- Nextjs@13.5.4
- prisma@5.15.0

running over **Plesk** and **SSH** w/ **minimal rights**

#### OS infos over SSH
```
> npm x prisma -v      # 8.19.4
> openssl version      # OpenSSL 1.0.2k-fips
> uname -srm           # 4.18.0-425.3.1.lve.3.el7h.x86_64 
> cat /proc/version    # Linux version 4.18.0-425.3.1.lve.3.el7h.x86_64 (gcc version 8.2.1 20180905 (Red Hat 8.2.1-3) (GCC)) 
> lsb_release -a       # command not found
> hostnamectl          # command not found
> cat /etc/os-release  # No such file or directory
> cat /etc/*release    # No such file or directory
```

#### binaryTargets
1. `prisma.schema`
```
generator client {
  provider = "prisma-client-js"
  binaryTargets = ["rhel-openssl-1.0.x"]
}
```
2. SSH and Plesk generates me **different** binaryTargets
- SSH:          `> npm x prisma generate` installs **debian-openssl-1.1.x**
- Plesk npm run: `> npm x prisma generate` installs **rhel-openssl-1.0.x**
into `<Project>/node_modules/@prisma/engines/`

## Solution
1. Copied and renamed 
`<Project>/node_modules/@prisma/engines/libquery_engine-rhel-openssl-1.0.x.so.node`
to
`<Project>/prisma/libquery_engine-debian-openssl-1.0.x.so.node`
`<Project>/prisma/libquery_engine-debian-openssl-1.1.x.so.node`

2. Copied and renamed 
`<Project>/node_modules/@prisma/engines/schema-engine-rhel-openssl-1.0.x`
to
`<Project>/prisma/schema-engine-debian-openssl-1.0.x`
`<Project>/prisma/schema-engine-debian-openssl-1.1.x`

## Optional: Plesk Nextjs deploy infos
- [Setup Nextjs on Plesk](https://dev.to/optimbro/how-to-setup-nextjs-application-on-plesk-hosting-control-panel-linux-3d54)
- **Building** the application only works in **Plesk** `npm run build` not over SSH as I got spawn ENOMEM errors in ssh
- Get out of fork bombs in SSH `kill -9 -1`
- Useful to know set in `next.config.js` for spawn errors
```
experimental: {
   workerThreads: false,
   cpus: 1,
}
```
