### ISSUE TITLE
next-auth: `PrismaClient is unable to be run in the browser.`

### ISSUE THREAD

**Issue by exosky12** [prisma/prisma#20147]
### Bug description

Got this error in the prismaClient configuration file.

<img width="961" alt="Screenshot 2023-07-10 at 11 34 46" src="https://github.com/prisma/prisma/assets/102408092/b77f72e0-b96c-486e-a91f-a53dcce01283">

### Prisma information

```prisma

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url  	= env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")
}
model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String? @db.Text
  access_token      String? @db.Text
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String? @db.Text
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  userId       String
  expires      DateTime
  sessionToken String   @unique
  accessToken  String   @unique
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
  user         User     @relation(fields: [userId], references: [id])
}

model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  accounts      Account[]
  sessions      Session[]
}

model VerificationRequest {
  id         String   @id @default(cuid())
  identifier String
  token      String   @unique
  expires    DateTime
  createdAt  DateTime @default(now())
  updatedAt  DateTime @updatedAt

  @@unique([identifier, token])
}

```

```ts
import { PrismaClient } from '@prisma/client';

declare global {
    // eslint-disable-next-line no-var, no-unused-vars
    var cachedPrisma: PrismaClient;
}

let prisma: PrismaClient;
if (process.env.NODE_ENV === 'production') {
    prisma = new PrismaClient();
} else {
    if (!global.cachedPrisma) {
        global.cachedPrisma = new PrismaClient();
    }
    prisma = global.cachedPrisma;
}

export const db = prisma;

```

### Environment & setup

- OS: macOS
- Database: PostgreSQL
- Node.js version: v19.7.0

### Prisma Version

```
prisma                  : 4.16.2
@prisma/client          : 4.16.2
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/.pnpm/@prisma+engines@4.16.2/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81 (at node_modules/.pnpm/@prisma+engines@4.16.2/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Format Wasm             : @prisma/prisma-fmt-wasm 4.16.1-1.4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Default Engines Hash    : 4bc8b6e1b66cb932731fb1bdbbc550d1e010de81
Studio                  : 0.484.0
```

**Comment by exosky12** [comment]
I am implementing next auth, here's my auth file: 
```ts
import { db } from '@/lib/db';
import { PrismaAdapter } from '@next-auth/prisma-adapter';
import { NextAuthOptions } from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';

function getGoogleCredentials(): { clientId: string; clientSecret: string } {
    const clientId = process.env.GOOGLE_CLIENT_ID;
    const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
    if (!clientId || clientId.length === 0) {
        throw new Error('Missing GOOGLE_CLIENT_ID');
    }

    if (!clientSecret || clientSecret.length === 0) {
        throw new Error('Missing GOOGLE_CLIENT_SECRET');
    }

    return { clientId, clientSecret };
}

export const authOptions: NextAuthOptions = {
    secret: process.env.NEXTAUTH_SECRET,
    adapter: PrismaAdapter(db),
    session: {
        strategy: 'jwt',
    },
    pages: {
        signIn: '/',
    },
    providers: [
        GoogleProvider({
            clientId: getGoogleCredentials().clientId,
            clientSecret: getGoogleCredentials().clientSecret,
        }),
    ],
    callbacks: {
        async session({ token, session }) {
            if (token) {
                session.user.id = token.id;
                session.user.name = token.name;
                session.user.email = token.email;
                session.user.image = token.picture;
            }

            return session;
        },
        async jwt({ token, user }) {
            const dbUser = await db.user.findFirst({
                where: {
                    email: token.email,
                },
            });

            if (!dbUser) {
                token.id = user!.id;
                return token;
            }

            return {
                id: dbUser.id,
                name: dbUser.name,
                email: dbUser.email,
                picture: dbUser.image,
            };
        },
        redirect() {
            return '/';
        },
    },
};
```

**Comment by millsp** [comment]
Could you please provide us with a reproduction repository?

**Comment by millsp** [comment]
Somehow it seems this is included in your frontend? The Prisma Client would then throw an error.

**Comment by evanrosa** [comment]
I'm having a similar issue but mine is in the edge I believe. Any suggestions? For context, I'm also using nextauth with next13 with a similar auth setup as @millsp

**Comment by janpio** [comment]
> I'm having a similar issue but mine is in the edge I believe. Any suggestions? For context, I'm also using nextauth with next13 with a similar auth setup as @exosky12

Could you please provide us with a reproduction repository?

**Comment by exosky12** [comment]
> Somehow it seems this is included in your frontend? The Prisma Client would then throw an error.

I'm just trying to initialize Prisma, not calling anything for now @millsp :/

**Comment by millsp** [comment]
This [code](https://github.com/prisma/prisma/blob/dbc49099301cede0b22436103d4c2a2be3a82686/packages/client/src/generation/TSClient/TSClient.ts/#L319-L320) suggests that at some point something called `new PrismaClient` either in the browser-side code or somehow it was bundled incorrectly. It would help us if you could share a small repro repository with what is happening.

**Comment by exosky12** [comment]
Yes, I think the problem comes from my getServerSession, how can I get the actual session (next auth) without causing troubles ?
I will do a reproduction repository as fast as possible.

**Comment by nukkerone** [comment]
> This [code](https://github.com/prisma/prisma/blob/dbc49099301cede0b22436103d4c2a2be3a82686/packages/client/src/generation/TSClient/TSClient.ts/#L319-L320) suggests that at some point something called `new PrismaClient` either in the browser-side code or somehow it was bundled incorrectly. It would help us if you could share a small repro repository with what is happening.

I know it's not a Repo, but this error is happening to me when I use Prisma from a Server Function (server action) that's being called from a Client Component in NextJS using the App Router.

**Comment by janpio** [comment]
It would be _really_, really helpful if someone could take the time to put a case like this into a reproduction repository. We'll be able to take that and make it run any time, but setting it up from scratch will take us to properly reserve time for this - which we barely have any right now. Sorry - so please someone help us out. Thanks!

**Comment by AbelR007** [comment]
I had this same error and I was able to resolve it by updating the auth file.
Instead of using Prisma Adapter directly in the authOptions, use it seperately

Instead of this
```js
export const authOptions: NextAuthOptions = {
    secret: process.env.NEXTAUTH_SECRET,
    adapter: PrismaAdapter(db),
    session: {
        strategy: 'jwt',
    },
```
Do this
```js
const adapter = PrismaAdapter(prisma);
export const authOptions: NextAuthOptions = {
    secret: process.env.NEXTAUTH_SECRET,
    adapter: adapter,
    session: {
        strategy: 'jwt',
    },
```
Update me if this works out for you, it did for me anyway!

**Comment by Oliveira-86** [comment]
I got the same error because I was passing data as props that were called in the layout file I assigned as a client component, "use client".

**Comment by gutodiasdev** [comment]
Hi, everything good? I had the same problem few minutes ago, after a some tries, the thing was everything the frontend and how i treated the client side button.

I just made an AuthenticationButton recieving provider.id from getProviders method in Server Component:

```typescript
import { AuthenticationButton } from '@/components/AuthenticationButton';
import { getProviders } from 'next-auth/react';
import Image from 'next/image';
import { FcGoogle } from 'react-icons/fc';

export default async function SignUp() {
  const providers = await getProviders();

  return (
    <main>
      <div className='flex flex-col min-h-[calc(100vh/2)] bg-[#5528ff] z-10'></div>
      <div className='flex flex-col h-1/2'>
        <div className='p-8 min-w-[400px] mx-auto bg-white -mt-12 z-20 border border-gray-300 rounded-lg'>
          <div className='flex flex-col items-center pb-8'>
            <Image src='/promogate-logo.svg' alt='Promogate Logo' width={120} height={60} />
          </div>
          {
            Object.values(providers!).map((provider, i) => {
              return (
                <AuthenticationButton key={i} className='border border-gray-500 p-2 w-full text-sm text-center'
                providerId={provider.id}>
                  <FcGoogle />
                  Cadastrar-se com {provider.name}
                </AuthenticationButton>
              )
            })
          }
        </div>
      </div>
    </main>
  )
``` 

```typescript
'use client'
import { openSans } from '@/application/utils/fonts'
import { signIn } from 'next-auth/react'
import React, { ButtonHTMLAttributes } from 'react'

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  children: React.ReactNode,
  className?: string,
  providerId: string
}

export function AuthenticationButton({ children, className, providerId, ...rest }: ButtonProps) {
  return (
    <button {...rest} className={'p-4 rounded-lg rounded-tl-none flex justify-center items-center gap-x-4' + ' ' + className}
    style={openSans.style} onClick={() => signIn(providerId)}>
      {children}
    </button>
  )
}
``` 

No prisma errors doing this.

**Comment by alvesvaren** [comment]
I had a similar issue due to me importing a prisma instance in my nextauth-file. I then exported the authOptions to be used with getServerSession, which I then had imported in a file shared between both the backend and the frontend

**Comment by TakashiAihara** [comment]
The same error occurred in my monorepo repository as well.

The cause was that I consolidated both frontend and backend functions into index.ts. As you all have pointed out, it was directly because I imported authOptions, but be careful as there seems to be a pattern where it's indirectly imported.

### index.ts (Bug occurs)

```TypeScript
export { default } from "next-auth"; 
export { signIn, signOut, useSession } from "next-auth/react";
export { authOptions } from "./src/auth-options";
export { getServerSession } from "./src/get-session";
```

👇Fixed

### client.ts

```TypeScript
export { default } from "next-auth";
export { SessionProvider, signIn, signOut, useSession } from "next-auth/react";
```

### server.ts

```TypeScript
export { authOptions } from "./src/auth-options";
export { getServerSession } from "./src/get-session";
```

### package.json

```Json
  "files": [
    "client.ts",
    "server.ts"
  ],
```

**Comment by janpio** [comment]
Can someone please help us get a working reproduction of the problem? The code snippets above might be helpful if you know Next.js and next-auth, but it would take us quite some time to put that together. It would be amazing if one of you could create a new project and implement the minimal code to show the problem - and then put it on GitHub. Thank you!

**Comment by jkomyno** [comment]
While we still don't have a reproduction of this issue, I don't think this is a Prisma issue per se.

The problem to me is that Prisma Client should be used in a backend JS runtime (e.g., Node.js) only, but when developing isomorphic Next.js projects (in which the separation between frontend and backend isn't necessarily super clear at first glance), the Prisma Client instance can easily leak into the frontend.

And, since these leaks cause Prisma Client to run in a browser (which is not supported), the runtime error above is thrown.

**Comment by millsp** [comment]
In addition to what @jkomyno said, we recently fixed the fact that that we threw errors when doing `new PrismaClient` and now we moved these errors to only happen if you try emitting a query in your front-end (which obviously cannot work).
