### ISSUE TITLE
No such argument error in relations with prisma2 beta1

### ISSUE THREAD

**Issue by akoufa** [prisma/prisma#2035]
Hello to all. 

I am using   **"@prisma/cli": "^2.0.0-beta.1",**

I have schema definition like:

```
someFieldX       TypeX @relation(fields: [someFieldXId], references: [id])
someFieldXId     String
```

When trying to run **prisma2 generate** I am getting the following error:

`Error: Schema parsing
error: No such argument.`

And the issue seems to be `fields: [someFieldXId]` as this is highlighted in red

**Comment by pantharshit00** [comment]
I was unable to reproduce this with `2.0.0-beta.1`. I used the following schema:
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

model User {
  id           String @default(cuid()) @id
  someFieldX   TypeX  @relation(fields: [someFieldXId], references: [id])
  someFieldXId String
}

model TypeX {
  id   String @default(cuid()) @id
  name String
  user User   
}
```

Can you please paste your complete schema here?

**Comment by JCLMAQ** [comment]
I get the same error with this schema: 
```
datasource postgresql {
  provider = "postgresql"
  url = env("POSTGRESQL_URL")
  enabled  = true
}

generator client {
  provider = "prisma-client-js"
 //  output   = "../node_modules/@generated/photon"
}

model User {
  id         String     @id @default(uuid())
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  email      String     @unique
  roles      String
  nickName   String?
  pwdHash    String
  salt       String
  profiles   Profile[]
  lastName   String?
  firstName  String?
  fullName   String?
  gender     Gender?
  manager    User?      @relation(name: "reportsTo")
  team       User[]     @relation(name: "reportsTo")
  groups     Group[]
  posts      Post[]
  comments   Comment[]
  todos      Todo[] 

}

model UserTodo {
  user      User  @relation(fields: [userId], references: [id])
  userId    String
  todo      Todo  @relation(fields: [todoId], references: [id])
  todoId    String
  createdAt DateTime @default(now())
  author    Boolean
  assigned  Boolean

  @@id([userId, todoId])
}

model Todo {
  id          String    @id @default(uuid())
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  title       String
  content     String?
  state       TodoState @default(CREATION)
  published   Boolean   @default(false)
  public      Boolean   @default(false)
  mainTodo    Todo?     @relation(name: "subTodo")
  subTodo     Todo[]    @relation(name: "subTodo")
  users       User[]
  groupConcern Group[]
}

enum TodoState {
  CREATION
  STANDBY
  RUNNING
  DONE
}
```

**Comment by akoufa** [comment]
@pantharshit00 I am not allowed to post my full schema here but it is similar to what @JCLMAQ JCLMAQ has posted

**Comment by ranjan-purbey** [comment]
Hey @JCLMAQ , can you please share the error logs here. I am assuming you have also defined the remaining types like Gender, Group, and Comment in your schema

**Comment by JCLMAQ** [comment]
The error is: 
```
$ npx prisma2 generate

Error: Schema parsing
error: No such argument.
  -->  schema.prisma:44
   | 
43 | model UserTodo {
44 |   user      User  @relation(fields: [userId], references: [id])
   | 
error: No such argument.
  -->  schema.prisma:46
   | 
45 |   userId    String
46 |   todo      Todo  @relation(fields: [todoId], references: [id])
   | 

Validation Error Count: 2
```
the full schema is: 
```
model User {
  id         String     @id @default(uuid())
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  email      String     @unique
  roles      String
  nickName   String?
  pwdHash    String
  salt       String
  profiles   Profile[]
  lastName   String?
  firstName  String?
  fullName   String?
  gender     Gender?
  manager    User?      @relation(name: "reportsTo")
  team       User[]     @relation(name: "reportsTo")
  groups     Group[]
  posts      Post[]
  comments   Comment[]
 todos      Todo[]
}

model UserTodo {
  user      User  @relation(fields: [userId], references: [id])
  userId    String
  todo      Todo  @relation(fields: [todoId], references: [id])
  todoId    String
  createdAt DateTime @default(now())
  author    Boolean
  assigned  Boolean

  @@id([userId, todoId])
}

model Todo {
  id          String    @id @default(uuid())
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  title       String
  content     String?
  state       TodoState @default(CREATION)
  published   Boolean   @default(false)
  public      Boolean   @default(false)
  mainTodo    Todo?     @relation(name: "subTodo")
  subTodo     Todo[]    @relation(name: "subTodo")
  users       User[]
  groupConcern Group[]
}

enum TodoState {
  CREATION
  STANDBY
  RUNNING
  DONE
}

model Profile {
  id         String     @id @default(uuid())
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  users      User[]
  bio        String
}

enum Gender {
  MALE
  FEMELE
  UNKNOWN
}

enum Role {
  USER
  ADMIN
  SUPERADMIN
}

model Group {
  id         String     @id @default(uuid())
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  name       String
  users      User[]
}

model Post {
  id         String     @id @default(uuid())
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  published  Boolean    @default(false)
  title      String
  content    String?
  author     User
  categories Category[]
  comments   Comment[]
}

model Category {
  id        String      @id @default(uuid())
  name      String
  posts     Post[]
}

model Comment {
  id        String    @id @default(uuid())
  createdAt DateTime  @default(now())
  updatedAt DateTime  @updatedAt
  published Boolean   @default(false)
  content   String?
  author    User
  post      Post
}
```

**Comment by ranjan-purbey** [comment]
@JCLMAQ  I think this error is being thrown because you are using an old version of prisma (the generate command that you are using is `npx prisma2 generate` instead of the one from 2.0.0-beta.1 which is `npx prisma generate`). Please update prisma to `v2.0.0-beta.1` and that should resolve the issue.

@akoufa are you too using the old version?

**Comment by JCLMAQ** [comment]
@ranjan-purbey 
In package.json, I get the beta version. And I did try to clean older versions (deleting the node_modules folder and   unsintall at the global level) , but I still get this error when I do try : 
```
$ npx prisma generate
npx : 593 installé(s) en 66.439s
 !    Couldn’t find `prisma.yml` file. Are you in the right directory?

```

**Comment by akoufa** [comment]
@ranjan-purbey 
I have following  "@prisma/client": "2.0.0-beta.1", and   "@prisma/cli": "^2.0.0-beta.1", defined in my package.json. When running `npx prisma generate` I am also getting the issue as @JCLMAQ . Probably it uses prisma1 despite that it should use prisma2 that was renamed to just prisma. That's why I also run it through package.json where I have a script like `"generate": "prisma2 generate",`

**Comment by arthuryeti** [comment]
Try to remove your `node_modules` and `package-lock.json` and redo an `npm install`

**Comment by akoufa** [comment]
@ranjan-purbey 

Yes I already had deleted node_modules and lock file.

`npx prisma -v` output:

```
npx: installed 593 in 18.556s
Prisma CLI version: prisma/1.34.10 (darwin-x64) node-v12.16.1
```

But I used `npm cache clean --force`

And now it get's the correct version. So I will close the issue. Thank you.
