### ISSUE TITLE
Cannot run cli behind proxy

### ISSUE THREAD

**Issue by joaomanke** [prisma/prisma#2181]
I've been trying to follow the getting started tutorial for prisma and have been stuck on the very beginning.

When I try to run the init command:
```
npx prisma init
```

I get the following error:
```
Downloading Prisma engines for windows [                    ] 0%
Error: request to https://binaries.prisma.sh/master/76857c35ba1e1764dd5473656ecbbb2f739e1822/windows/query-engine.exe.gz.sha256 failed, reason: connect ECONNREFUSED 13.227.120.121:443
```

I am currently working under a company proxy which is what I think might be the problem, however I have the environment variables as well as npm configs set correctly and have no idea why this is happening or how to fix it.

I am using a windows machine, as you can tell from the error message.
I have tried installing globally but get the same result.

**Comment by pantharshit00** [comment]
@joaomanke 

We use a mirror to store our binaries at https://binaries.prisma.sh which is an AWS Cloudfront on top of an AWS S3 bucket.

We do that because if we do that via npm we can't detect the OS and we have to ship each and every binary to you.

We do support a proxy for corporate firewalls: https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-cli/installation#using-a-http-proxy-for-the-cli. Please try using that.

Let me know if you are still getting trouble

**Comment by joaomanke** [comment]
@pantharshit00 Thank you for the quick response.

I had already tried setting the environment variables before, to no avail. Tried again to make sure, but same result.

I can manually download the binaries, so I don't think my proxy is blocking access to the url.

I managed to workaround the cli downloads by manually downloading the binaries and extracting them to a binaries folder within my project and pointing to them with the environment variables raise to my attention in #1333.

This, however, is not really maintainable, but works for now. When the current alpha version gets released the PRISMA_BINARIES_MIRROR environment variable probably will be the way to go for me.

**Comment by janpio** [comment]
> I had already tried setting the environment variables before, to no avail. Tried again to make sure, but same result.
> 
> I can manually download the binaries, so I don't think my proxy is blocking access to the url.

That is really strange and unexpected.

Can you please set the env var `DEBUG=*` (`set DEBUG=*` on Windows) and post the full output here? Maybe that gives us some insight.

**Comment by joaomanke** [comment]
Sorry for the late reply,

> Can you please set the env var `DEBUG=*` (`set DEBUG=*` on Windows) and post the full output here? Maybe that gives us some insight.

Will do, later today when I get to work I'll post it here.

**Comment by joaomanke** [comment]
Here it is:

```
  prisma {
  prisma   argv: [
  prisma     'C:\\Program Files\\nodejs\\node.exe',
  prisma     'C:\\Users\\joaomanke\\Desktop\\prisma\\node_modules\\@prisma\\cli\\build\\index.js',
  prisma     'init'
  prisma   ]
  prisma } +0ms
  prisma Environment variables not loaded +6ms
  getos { platform: 'win32', libssl: undefined } +0ms
  download { fileExists: false, cachedFile: null } +0ms
  download { needsToBeDownloaded: true } +0ms
  download { fileExists: false, cachedFile: null } +2ms
  download { needsToBeDownloaded: true } +0ms
  download { fileExists: false, cachedFile: null } +1ms
  download { needsToBeDownloaded: true } +1ms
  download Downloading https://binaries.prisma.sh/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/windows/migration-engine.exe.gz to C:\Users\joaomanke\Desktop\prisma\node_modules\@prisma\cli\migration-engine-windows.exe +2ms
> Downloading Prisma engines for windows [                    ] 0%  download Downloading zip +3ms
  download Downloading https://binaries.prisma.sh/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/windows/query-engine.exe.gz to C:\Users\joaomanke\Desktop\prisma\node_modules\@prisma\cli\query-engine-windows.exe +18ms
  download Downloading zip +2ms
  download Downloading https://binaries.prisma.sh/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/windows/introspection-engine.exe.gz to C:\Users\joaomanke\Desktop\prisma\node_modules\@prisma\cli\introspection-engine-windows.exe +2ms
  download Downloading zip +1ms
Error: FetchError: request to https://binaries.prisma.sh/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/windows/introspection-engine.exe.gz.sha256 failed, reason: connect ECONNREFUSED 13.227.120.27:443
    at ClientRequest.<anonymous> (C:\Users\joaomanke\Desktop\prisma\node_modules\@prisma\cli\build\index.js:2:505664)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

I realize that on the 8th line it says `prisma Environment variables not loaded +6ms`

Just in case this is relevant, here are my npm configs:
```
; cli configs
metrics-registry = // Company mirror repo
scope = ""
user-agent = "npm/6.14.4 node/v13.12.0 win32 x64"

; userconfig C:\Users\joaomanke\.npmrc
registry = // Company mirror repo

; builtin config undefined
prefix = "C:\\Users\\joaomanke\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\joaomanke\Desktop\prisma
; HOME = C:\Users\joaomanke
; "npm config ls -l" to show all defaults.
```

And my Environment Variables (the relevant ones at least) :
```
HTTP_PROXY= // Proxy with user and pwd -> http://user:password@proxy:port
HTTPS_PROXY= // Proxy with user and pwd -> http://user:password@proxy:port
DEBUG=*
```

**Comment by ethernal** [comment]
The problem is not the CDN links but that, as in my case, your proxy requires authentication. I have not dug into the code yet but WHAT is downloading the binaries? It's not npm (i have it configured for proxy), if it's a fetch from a JS/binary file then this would explain things.

One solution (possible?) would be to make an npm packages from binaries and load them as dependencies or just invoke npm/yarn to install them - that way we could have it all working as expected.

The other way around would be need to implement proxy with authentication support for whatever piece of software is downloading the binaries. What do you think @janpio @pantharshit00 ?

**Comment by adam-madet** [comment]
I've spent this whole day trying to get this problem fixed, I tired setting up a node proxy server to forward requests to https://binaries.prisma.sh, but am still stuck with this error..

`Error: request to https://binaries.prisma.sh/master/2fb8f444d9cdf7c0beee7b041194b42d7a9ce1e6/debian-openssl-1.1.x/query-engine.gz.sha256 failed, reason: connect ECONNREFUSED 13.226.18.126:443`

Would really not like to rewrite all my code without prisma since that would be way too time consuming, any chance a fix like the one described by @ethernal might be coming soon. That way people under corporate proxies won't run into issues downloading binaries.

**Comment by adam-madet** [comment]
Update I got it working... had to use

ENV PRISMA_BINARIES_MIRROR http://prisma-builds.s3-eu-west-1.amazonaws.com

For the mirror to work under a company proxy. https does not work under a company proxy even though I can wget to the the direct https:// site. Hope theres a real fix for this soon.

**Comment by janpio** [comment]
> ENV https_proxy http://{company_url}:8080

You usually have to add a `https` proxy there for https requests to work, right?

**Comment by adam-madet** [comment]
@janpio My bad it was suppose to be https:// for the https_proxy env variable, typed it over into the comment incorrectly. This wasn't the solution however

**Comment by pantharshit00** [comment]
Hi again,

Can you please all try the latest alpha version? We had this fix merged https://github.com/prisma/prisma/pull/2540 which might fix the issue for you all

**Comment by joaomanke** [comment]
> Hi again,
> 
> Can you please all try the latest alpha version? We had this fix merged #2540 which might fix the issue for you all

It worked for me! Thank you!

**Comment by pantharshit00** [comment]
I am going to close this now as this is resolved for the original poster. 

If you still experiencing this issue, please create a new github issue

**Comment by astahmer** [comment]
in case someone still gets this issue, here what I tried : 
- appending `?sslmode=disable` to db url
- `DEBUG='*' proxy -p 8180 && HTTP_PROXY=http://localhost:8180/ HTTPS_PROXY=https://localhost:8180/ prisma generate`
- `NODE_TLS_REJECT_UNAUTHORIZED=0`

nothing worked until finding this thread with
`ENV PRISMA_BINARIES_MIRROR http://prisma-builds.s3-eu-west-1.amazonaws.com/`

**Comment by rodrigoarias12** [comment]
> nothing worked until finding this thread with `ENV PRISMA_BINARIES_MIRROR http://prisma-builds.s3-eu-west-1.amazonaws.com`

In my case(windows + cmd ) only worked with set `PRISMA_BINARIES_MIRROR http://prisma-builds.s3-eu-west-1.amazonaws.com`

**Comment by janpio** [comment]
Why does using the `amazonaws.com` hostname work, but using `binaries.prisma.sh` does not? It is really the same server behind it.

**Comment by rodrigoarias12** [comment]
> Why does using the `prisma-builds.s3-eu-west-1.amazonaws.com` hostname work, but using `binaries.prisma.sh` does not? It is really the same server behind it.

I don't know what the difference is between them. Both of them are without  SSL certificates. 
Is binaries.prisma.sh  a new domain ?

**Comment by janpio** [comment]
Ahh, you are all switching from our `https` endpoints to `http` without SSL. That might indeed explain why your local networks do not block requests (although blocking requests to hostnames behind SSL is pretty questionable).

> Is binaries.prisma.sh a new domain ?
It is an actually load balanced and globally distributed hostname that serves the same files as `prisma-builds.s3-eu-west-1.amazonaws.com`.

**Comment by dassoukhi** [comment]
> 



> en utilisant prisma généré dans une image docker
> 
> au cas où quelqu'un aurait toujours ce problème, voici ce que j'ai essayé :
> 
> * ajout `?sslmode=disable`à l'URL de la base de données
> * `DEBUG='*' proxy -p 8180 && HTTP_PROXY=http://localhost:8180/ HTTPS_PROXY=https://localhost:8180/ prisma generate`
> * `NODE_TLS_REJECT_UNAUTHORIZED=0`
> 
> rien n'a fonctionné jusqu'à trouver ce fil avec `ENV PRISMA_BINARIES_MIRROR http://prisma-builds.s3-eu-west-1.amazonaws.com`

Salut mec, je suis bloqué dessus depuis une semaine déjà, tu peux stp me montrer ton Dockerfile ? je suis sous proxy entreprise aussi. meric à toi

**Comment by astahmer** [comment]
> > 
> 
> > en utilisant prisma généré dans une image docker
> > au cas où quelqu'un aurait toujours ce problème, voici ce que j'ai essayé :
> > 
> > * ajout `?sslmode=disable`à l'URL de la base de données
> > * `DEBUG='*' proxy -p 8180 && HTTP_PROXY=http://localhost:8180/ HTTPS_PROXY=https://localhost:8180/ prisma generate`
> > * `NODE_TLS_REJECT_UNAUTHORIZED=0`
> > 
> > rien n'a fonctionné jusqu'à trouver ce fil avec `ENV PRISMA_BINARIES_MIRROR http://prisma-builds.s3-eu-west-1.amazonaws.com`
> 
> Salut mec, je suis bloqué dessus depuis une semaine déjà, tu peux stp me montrer ton Dockerfile ? je suis sous proxy entreprise aussi. meric à toi

.Dockerfile

```dockerfile
# syntax=docker/dockerfile:1
# install pnpm
FROM node:16-slim AS with-pnpm

RUN npm i -g pnpm
RUN apt-get update
RUN apt-get install -y openssl
# https://github.com/prisma/prisma/issues/8783

# install deps
FROM with-pnpm AS deps

WORKDIR /app

COPY ./pnpm-lock.yaml /app
COPY ./package.json /app
RUN pnpm install --frozen-lockfile

# build
FROM with-pnpm AS build

WORKDIR /app

COPY --from=deps /app/node_modules /app/node_modules
COPY ./src /app/src
COPY ./prisma /app/prisma
COPY ./package.json /app
COPY ./tsconfig.json /app
COPY ./rollup.config.js /app
COPY ./vitest.config.ts /app

ENV PRISMA_BINARIES_MIRROR http://prisma-builds.s3-eu-west-1.amazonaws.com
ENV PRISMA_CLI_QUERY_ENGINE_TYPE binary
ENV PRISMA_CLIENT_ENGINE_TYPE binary
# https://github.com/prisma/prisma/issues/8783

RUN pnpm build

# start production environment
FROM with-pnpm

WORKDIR /app
COPY --from=build /app ./

EXPOSE 8080

CMD NODE_ENV=production pnpm start:prod
```

// package.json scripts
```json
"migration:up:prod": "DATABASE_URL=${DATABASE_MIGRATE_URL} yarn prisma migrate deploy",
"start:prod": "PRISMA_BINARIES_MIRROR=http://prisma-builds.s3-eu-west-1.amazonaws.com PRISMA_CLI_QUERY_ENGINE_TYPE=binary PRISMA_CLIENT_ENGINE_TYPE=binary yarn migration:up:prod && NODE_ENV=production node dist/main.js",
```
