### ISSUE TITLE
Deploying SvelteKit App to Vercel Edge Function with Planetscale MiddleWare results in Error

### ISSUE THREAD

**Issue by shawnlong636** [prisma/prisma#23599]
### Bug description

Hello, I'm using SvelteKit on Vercel Edge Functions and am trying to use the PlanetScale Edge Middleware. I followed the guide in the docs, but got hung up in a couple places. Locally, I can use the adapter middleware perfectly, with my db connection looking like this:

```ts
import { DATABASE_URL } from '$env/static/private';
import { Client } from '@planetscale/database';
import { PrismaPlanetScale } from '@prisma/adapter-planetscale';
import { PrismaClient } from '@prisma/client';

const config = {
    url: DATABASE_URL
};

const client = new Client(config);
const adapter = new PrismaPlanetScale(client);
export const prisma = new PrismaClient({ adapter });
```

The problem is that when I deploy this on Vercel, I get the following error:

```
error: PrismaClient is not configured to run in Vercel Edge Functions or Edge Middleware. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters

If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report
    at (../../../../node_modules/.pnpm/@prisma+client@5.11.0_prisma@5.11.0/node_modules/.prisma/client/index-browser.js:352:14)
    at (../../../../.svelte-kit/output/server/entries/endpoints/api/top-categories/_server.ts.js:3:31)
    at (../../../../.svelte-kit/output/server/index.js:181:25)
    at (../../../../.svelte-kit/output/server/index.js:3459:27)
    at (../../../../.svelte-kit/output/server/chunks/hooks.server.js:4:9)
    at (../../../../.svelte-kit/output/server/index.js:3353:21)
```

From the docs, two alternative configurations involve adding `export const runtime = 'edge'`, but this doesn't appear to have any effect in SvelteKit. Alternatively, I also saw some docs which use the custom fetch function from `undici` and supply that to the PlanetScale config. Unfortunately though, undici fails to build on the edge runtime, thus that isn't a good solution either.

### How to reproduce

1. Set up basic sveltekit repo with runtime: 'edge' in svelte.config.js
2. Connect to a PlanetScale database as per the docs. Ensure previewFeature flag is enabled generator provider is `prisma-client-js`
3. Deploy to Vercel
4. Visit page that uses prisma client (either an API Route, or in a +server.ts file)
5. View Vercel Logs and see errors from Prisma Client

### Expected behavior

Prisma Client should not throw an error when being used in a Vercel edge function if middleware is enabled. An alternative solution to `export const runtime = 'edge'` is needed so that frameworks such as Svelte don't falsely flag an error with the PrismaClient when there actually isn't an error.

### Prisma information

```prisma
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["driverAdapters", "fullTextIndex", "fullTextSearch"]
}

datasource db {
  provider     = "mysql"
  url          = env("DATABASE_URL")
  relationMode = "prisma"
}

model Category {
  id Int @id @default(autoincrement())

  courses Course[]

  imgHref String @map("img_href") @db.Text
  title   String @unique

  @@map("categories")
}

model Course {
  id Int @id @default(autoincrement())

  category           Category         @relation(fields: [categoryId], references: [id], onUpdate: Cascade, onDelete: Restrict)
  courseProgressions CourseProgress[]
  instructor         User             @relation(fields: [instructorId], references: [id], onUpdate: Cascade, onDelete: Cascade)
  lessons            Lesson[]
  organization       Organization?    @relation(fields: [organizationId], references: [id], onUpdate: Cascade, onDelete: SetNull)

  categoryId           Int     @map("category_id")
  currentPrice         Decimal @map("current_price")
  description          String  @db.Text
  difficulty           String
  estimatedTimeHours   Int     @map("estimated_time_hours")
  estimatedTimeMinutes Int     @map("estimated_time_minutes")
  imgHref              String  @map("img_href")
  instructorId         Int     @map("instructor_id")
  lessonCount          Int     @map("lesson_count")
  organizationId       Int?    @map("organization_id")
  originalPrice        Decimal @map("original_price")
  ratingAverage        Float   @map("rating_average")
  ratingCount          Int     @map("rating_count")
  title                String  @db.Text

  @@index([categoryId])
  @@index([instructorId])
  @@index([organizationId])
  @@fulltext([title])
  @@fulltext([title, description])
  @@map("courses")
}

enum ContentType {
  VIDEO
  TEXT
  QUIZ
}

model CourseContent {
  id Int @id @default(autoincrement())

  contentType ContentType @map("content_type")

  authorId Int     @map("author_id")
  content  Json
  lessonId Int?    @map("lesson_id")
  Lesson   Lesson? @relation(fields: [lessonId], references: [id])

  @@index([authorId])
  @@index([lessonId])
  @@map("course_contents")
}

model CourseProgress {
  course Course @relation(fields: [courseId], references: [id], onUpdate: Cascade, onDelete: Cascade)
  user   User   @relation(fields: [userId], references: [id], onUpdate: Cascade, onDelete: Cascade)

  courseId         Int @map("course_id")
  lessonsCompleted Int @map("lessons_completed")
  userId           Int @map("user_id")

  @@id([userId, courseId])
  @@index([courseId])
  @@index([userId])
  @@map("course_progresions")
}

model Lesson {
  id Int @id @default(autoincrement())

  course         Course?         @relation(fields: [courseId], references: [id], onUpdate: Cascade, onDelete: Cascade)
  courseContents CourseContent[]

  courseId Int?   @map("course_id")
  title    String

  @@index([courseId])
  @@map("lessons")
}

model Organization {
  id Int @id @default(autoincrement())

  courses Course[]

  description String? @db.Text
  name        String  @db.Text
  User        User[]

  @@map("organizations")
}

model User {
  id Int @id @default(autoincrement())

  AuthUser           AuthUser?        @relation(fields: [authUserId], references: [id], onUpdate: Cascade, onDelete: Cascade)
  courses            Course[]
  courseProgressions CourseProgress[]
  organization       Organization?    @relation(fields: [organizationId], references: [id], onUpdate: Cascade, onDelete: SetNull)
  permissions        Permission[]

  areaCode       String? @map("area_code") @db.VarChar(5)
  authUserId     String? @unique @map("auth_user_id") @db.VarChar(30)
  bio            String? @db.Text
  city           String? @db.Text
  countryCode    String? @map("country_code") @db.VarChar(5)
  email          String  @unique
  name           String  @db.Text
  organizationId Int?    @map("organization_id")
  phoneNumber    String? @map("phone_number") @db.VarChar(15)
  photoUrl       String? @map("photo_url") @db.Text
  role           String  @default("user")
  state          String?

  @@index([authUserId])
  @@index([organizationId])
  @@map("users")
}

enum KeyType {
  CREDENTIAL_HASH
  OAUTH_TOKEN
}

model AuthKey {
  id String @id @default(cuid()) @db.VarChar(30)

  authUser AuthUser @relation(fields: [authUserId], references: [id], onUpdate: Cascade, onDelete: Cascade)

  authUserId String  @map("auth_user_id") @db.VarChar(30)
  keyValue   String  @map("key_value")
  keyType    KeyType @map("key_type")

  @@index([authUserId])
  @@map("auth_keys")
}

model AuthSession {
  id String @id @default(cuid()) @db.VarChar(30)

  authUser AuthUser @relation(fields: [authUserId], references: [id], onUpdate: Cascade, onDelete: Cascade)

  authUserId     String   @map("auth_user_id") @db.VarChar(30)
  expirationDate DateTime @map("expiration_date")

  @@index([authUserId])
  @@map("auth_sessions")
}

model AuthUser {
  id String @id @default(cuid()) @db.VarChar(30)

  authKeys     AuthKey[]
  authSessions AuthSession[]
  user         User?

  email String @unique

  @@map("auth_users")
}

model CsrfToken {
  token String @id @default(cuid()) @db.VarChar(30)

  expirationDate DateTime @map("expiration_date")

  @@map("csrf_tokens")
}

enum PermissionType {
  READ
  WRITE
  DELETE
}

enum ResourceType {
  COURSE
  LESSON
  USER
}

model Permission {
  id Int @id @default(autoincrement())

  user User @relation(fields: [userId], references: [id], onUpdate: Cascade, onDelete: Cascade)

  permissionType PermissionType @map("permission_type")
  resourceId     Int            @map("resouce_id") // Eventually shift this to another table
  resourceType   ResourceType   @map("resource_type")
  userId         Int            @map("user_id")

  @@index([userId])
  @@map("permissions")
}
```

// src/lib/database/server/database.ts
```ts
import { DATABASE_URL } from '$env/static/private';
import { Client } from '@planetscale/database';
import { PrismaPlanetScale } from '@prisma/adapter-planetscale';
import { PrismaClient } from '@prisma/client';

const config = {
    url: DATABASE_URL
};

const client = new Client(config);
const adapter = new PrismaPlanetScale(client);
export const prisma = new PrismaClient({ adapter });
```

// An example API Route which uses prisma
// src/routes/api/courses/+server.ts

```ts
import { csrf } from '$lib/server/csrf';
import { prisma } from '$lib/server/database';

import type { RequestHandler } from './$types';

export const GET = (async ({ cookies }) => {
    await csrf.validateCookies(cookies);

    const coursesWithInstructors = await prisma.course.findMany({
        include: {
            instructor: true
        },
        take: 20
    });

    const unzippedCoursesWithInstructors: { course: Course; instructor: User }[] =
        coursesWithInstructors.map(({ instructor, ...course }) => ({
            course,
            instructor
        }));

    const json = JSON.stringify(unzippedCoursesWithInstructors);

    return new Response(json, {
        headers: {
            'cache-control': 'public, max-age=3600',
            'content-type': 'application/json;charset=UTF-8'
        }
    });
}) satisfies RequestHandler;
```

### Environment & setup

- OS: Edge Runtime (Vercel Edge Functions)
- Database: PlanetScale
- Node.js version: 18.X (Vercel)

### Prisma Version

```
prisma                  : 5.11.0
@prisma/client          : 5.11.0
Computed binaryTarget   : darwin
Operating System        : darwin
Architecture            : x64
Node.js                 : v20.11.1
Query Engine (Node-API) : libquery-engine efd2449663b3d73d637ea1fd226bafbcf45b3102 (at node_modules/.pnpm/@prisma+engines@5.11.0/node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Schema Engine           : schema-engine-cli efd2449663b3d73d637ea1fd226bafbcf45b3102 (at node_modules/.pnpm/@prisma+engines@5.11.0/node_modules/@prisma/engines/schema-engine-darwin)
Schema Wasm             : @prisma/prisma-schema-wasm 5.11.0-15.efd2449663b3d73d637ea1fd226bafbcf45b3102
Default Engines Hash    : efd2449663b3d73d637ea1fd226bafbcf45b3102
Studio                  : 0.499.0
Preview Features        : driverAdapters, fullTextIndex, fullTextSearch
```

**Comment by janpio** [comment]
Can you maybe put a minimal project with all the necessary code on GitHub so we just need to run some commands? That would help us to reproduce this the easiest. Thanks!

**Comment by shawnlong636** [comment]
Absolutely @janpio, I'll try and get that set up tonight.

**Comment by shawnlong636** [comment]
@janpio, just included a public repo with minimal example and more clear steps to reproduce. This should be pretty straightforward even if you're not familiar with SvelteKit.

[Link to Minimal Example Rep](https://github.com/shawnlong636/prisma-pscale-edge-basic)

**Comment by shawnlong636** [comment]
FYI @janpio, I decided to clone the repo and see if I might be able to lend a hand pushing a fix for this. It looks like what's happening is that the stub Prisma Client from `packages/client/src/generation/TSClient/TSClient.ts` is being called and that's what's causing the error to be thrown. What I haven't been able to figure out yet is how the client runtime is being determined at runtime leading to that stub being called.

**Comment by Jolg42** [comment]
Note: I could reproduce with https://github.com/shawnlong636/prisma-pscale-edge-basic

This project is using `@sveltejs/adapter-vercel` with the following config
```
adapter: adapter({
    runtime: "edge",
    split: true,
}),
```
Docs: https://kit.svelte.dev/docs/adapter-vercel
Source: https://github.com/sveltejs/kit/tree/main/packages/adapter-vercel

Maybe the problem happens because this adapter is doing something wrong? (to be investigated)

**Comment by jkomyno** [comment]
Hi @shawnlong636, can you please retry with the following (unstable) version of `prisma` and `@prisma/client`?
`5.15.0-integration-client-dynamic-wasm-imports.1`.

We believe that contains the fix to this issue. Thanks!

**Comment by jkomyno** [comment]
Hey all, with Prisma 5.15.0, this issue is now fixed. Even though I will close the issue right now, you're still welcome to leave feedback below ✨

Thanks!

**Comment by shawnlong636** [comment]
Hey @jkomyno, been away from using prisma for a while but decided to come back and check on this. I tested with the version you mentioned as well as the new latest prisma, version 5.19.1 and I still get the same error when using the prisma client with the database adapter on vercel edge. I updated [my example repo linked before](https://github.com/shawnlong636/prisma-pscale-edge-basic) with the latest prisma version.

```
Error: PrismaClient is not configured to run in Edge Runtime (Vercel Edge Functions, Vercel Edge Middleware, Next.js (Pages Router) Edge API Routes, Next.js (App Router) Edge Route Handlers or Next.js Middleware). In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters

If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report
    at (../../../../node_modules/.pnpm/@prisma+client@5.19.1_prisma@5.19.1/node_modules/.prisma/client/index-browser.js:164:14)
    at (../../../../.svelte-kit/output/server/entries/endpoints/api/user/_server.ts.js:63:29)
    at (../../../../.svelte-kit/output/server/index.js:257:25)
    at (../../../../.svelte-kit/output/server/index.js:3537:27)
    at (../../../../.svelte-kit/output/server/index.js:3432:21)
   ```
