### ISSUE TITLE
Timed out fetching a new connection from the pool

### ISSUE THREAD

**Issue by rivatove** [prisma/prisma#24844]
### Bug description

Recently, I experienced similar issues to those mentioned in the following issues:
https://github.com/prisma/prisma/issues/7249
https://github.com/prisma/prisma/issues/9902

That is, Prisma will sporadically hang with the following errors:
- Worker nodes: `P1001`
- Web server nodes: `P2024` (as in title)

At first, some errors will happen but the application recovers (with increased latency). Unfortunately, some minutes later the errors come back and it's not recoverable at that point. Here are error log timestamps to illustrate the pattern: https://i.imgur.com/wKTLBCO.png

Here are RDS logs from the time the issue happened: https://i.imgur.com/9o1TYKl.png

It makes me think that Prisma encounters an actual issue with the DB server but for some reason is not able to recover after that.

Restarting the app servers resolves the issue.

I'll be implementing the following auto-recovery mechanism, please let me know if it looks good to you:

```
  prisma.$on('error', (e) => {
    if (
      e.message.includes(`Can't reach database server`) ||
      e.message.includes(
        `Timed out fetching a new connection from the connection pool`,
      )
    )
      prisma.$disconnect().catch((e) => logger.error(e));
  });
```

### How to reproduce

No reproduction as it only happened 2 times in production.

### Prisma information

-

### Environment & setup

MySQL 8.0.35 hosted on Multi-AZ RDS.

### Prisma Version

The issue happened to me 2 times, on 21.06 (version 5.15), and on 18.07 (version 5.16.2). If we assume the issue takes up to a month to manifest, the version 5.14 could also be affected.

I've been using Prisma for around 2 years and these are the first time it happened. Which makes me think a regression could've been introduced in the code. I'll be rolling back to 5.13 in my production environment and monitoring.

**Comment by istarkov** [comment]
We are experiencing a similar issue on a regular basis. Every few hours, we encounter the following events.

On some instances, we receive the following error:
```
Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 1)
```
Subsequent or parallel requests to that instance then start failing with the following error:
```
Vercel Runtime Timeout Error: Task timed out after 30 seconds
```
This happens on any Prisma invocation, suggesting that Prisma hangs when attempting to reuse a connection.

**Comment by sorenbs** [comment]
> We are using Supabase connection pool
> with the following connection string (Transaction mode)

Hi @istarkov, 

1) Could you let me know what Supabase instance size you are using?

2) Could you follow these steps to verify if the issue is related to too many open connections on the Supabase side: https://github.com/prisma/prisma/issues/24844#issuecomment-2247216660

3) Have you recently changed the version of Prisma you are using? We are not aware of a regression that could cause this, but it is good to rule out if we can.

**Comment by istarkov** [comment]
1.	T4g.micro machine

2.	The Supavisor connection pooler has maxConn set to 400 and dbConn set to 15. I have tried various connection strings for DATABASE_URL as shown below:
```
datasource db {
  provider  = "postgres"
  url       = env("DATABASE_URL")
  directUrl = env("DIRECT_URL")
}
```
I have tested with and without the connection_limit parameter in the query string, i.e., ?pgbouncer=true&connection_limit=1. There do not appear to be any issues on the Supabase side.

3.	Regarding the current volume of errors, we started experiencing a significant increase on July 23, 2024, at 07:00 UTC. Previously, we encountered only 1-3 errors per day without any changes on our end.

**Comment by istarkov** [comment]
I think I can reproduce similar behaviour locally:

# Pre

You need to have working postgres on `0.0.0.0:5432` address
You need to have `netcat`  i.e. `nc` utilities installed
Following ts file with any prisma setup

```typescript
// runme.ts
import { PrismaClient, Prisma } from "./__generated__";
const prisma = new PrismaClient();
for (let i = 0; i < 100; ++i) {
  const res = await prisma.$executeRaw(Prisma.sql`SELECT 1;`);
  await new Promise((resolve) => setTimeout(resolve, 1000));
  console.log(res);
}
```


# Reproduction:

In any of you project with prisma setup create following ts


Execute (forward port 5431 to 5432 once)

```bash
nc -l -p 5431 -c "nc 0.0.0.0 5432"
```

Execute 
```bash
tsx ./runme.ts
```

Pause or stop sql after few seconds

The result:
`runme.ts` will hang forever, but should throw that connection is not exists or some query timeout reached.

**Comment by istarkov** [comment]
Same code with pg and query_timeout parameter (client timeout)

```
import pg from "pg";
const { Pool } = pg;

const pool = new Pool({
  query_timeout: 5000,
  connectionString: process.env.DATABASE_URL,
});

for (let i = 0; i < 100; ++i) {
  const res = await pool.query("SELECT 1;");
  await new Promise((resolve) => setTimeout(resolve, 1000));
  console.log(res.rows[0]);
}
```
has no issues and fails with 
```
Error: Query read timeout
```

**Comment by sorenbs** [comment]
Thank you @istarkov!

We will be running this reproduction and get back to you with additional information or questions.

**Comment by istarkov** [comment]
If anyone is experiencing similar issues, our solution was to switch to an IPv4 direct connection (a paid plugin from Supabase) and set ?connection_limit=1 (not mandatory, but we use edge functions).

**Comment by sorenbs** [comment]
Thank you @istarkov! Can you confirm that disabling the Supabase Supavisor connection pooler and using a direct database connection instead completely resolved the issue?

I'd like to talk to the Supabase team so we can get to the bottom of this.

**Comment by abc3** [comment]
Out of curiosity, did you try using Supavisor on port 5432? Does the issue still persist?

**Comment by abc3** [comment]
@istarkov could you reach out to Supabase support to check your project's logs?

**Comment by istarkov** [comment]
I believe this is the reason for the issue: https://github.com/prisma/prisma/issues/24844#issuecomment-2247851311

For an unknown reason, Supavisor connections are being dropped from the database but still exist between the Vercel instance and the Supavisor endpoint. As a result, Prisma cannot detect that the connection has dropped and hangs indefinitely. This is one of the reasons why `pg` has a client implementation of query_timeout.

I have checked supavisor and db logs

There are usual messages like
```
"DbHandler: ClientHandler #PID<0.15079.4732> went down with reason {:shutdown, :socket_closed}"
"ClientHandler: socket closed with reason {:shutdown, :socket_closed}, DbHandler {#PID<50036.15505.2460>, {:authentication, :transaction}}
```

There is nothing unusual or non-standard in the SQL logs.

I haven’t tried using port 5432. The issue reproduces somewhat consistently only in our production environment, making it difficult to test.

With a direct connection, we experienced a single, clear Prisma timeout error, but without the hanging issue.

**Comment by istarkov** [comment]
Anyway, we have informed Supabase, and they are investigating this as well. The issue also broke our CLI psql in the CI/CD environment ;-)

**Comment by istarkov** [comment]
It seems that the following was happening on the Supabase side:
We recently started using PostgREST for some queries, and somehow it caused memory thrashing on the server. It appears that the server periodically had memory [thrashing](https://en.wikipedia.org/wiki/Thrashing_(computer_science)) issues, which could have impacted the connection. (This might be the reason why the connection between PostgreSQL and Supavisor was dropping.)

**Comment by jpetto** [comment]
@rivatove curious if your proposed fix (disconnecting on error) yielded any results.

**Comment by rivatove** [comment]
I haven't yet encountered the error again so can't speak on that.

pt., 26 lip 2024, 00:04 użytkownik jpetto ***@***.***>
napisał:

**Comment by suhail135** [comment]
I have encountered similar issue, The issue was fixed for me after updating to the latest version of Prisma ( 5.17.0 )

**Comment by apolanc** [comment]
@istarkov are you still experiencing this problem in Prisma version 5.17? we haven't yet ran a reproduction of the issue and we will come to that.

I nevertheless wanted to double check with you before that.

**Comment by istarkov** [comment]
The test above clearly shows that Prisma can hang indefinitely in certain situations, and there is no option to set a query timeout. This leads to a scenario where, as in our case, all we see in the logs are serverless function timeouts.

As I demonstrated above, a query timeout is available in node pg and other libraries. It’s not normal for a method call to hang indefinitely.

**Comment by moltar** [comment]
We are hitting the same issue on RDS (not using Supabase).

The symptom is that we suddenly get a wall of logs with the subj error message.

We are also observing some memory issues (perhaps a leak) but are still unsure whether they are related or something on our side.

**Comment by rivatove** [comment]
I haven't encountered the issue again after rolling back to 5.13. So it's very likely the bug has been introduced in future releases.

I think the findings of @istarkov are what this issue is about. AWS RDS with multi-AZ enabled uses a proxy for seamless switching between the primary and replica. So this is somehow consistent with the findings.

**Comment by michael-rzero** [comment]
Encountering this too with supabase pooler.

**Comment by aqrln** [comment]
Hey everyone! The upcoming Prisma 5.23.0 release will include a fix for one of the reasons this problem can occur. Your case is likely to be fixed if:
1. You are using PostgreSQL.
2. You are using TLS encryption to connect to the database (this is the case by default whenever the database supports it, e.g., on AWS RDS, Supabase, Neon).
3. Your application is running in a resource-constrained environment, e.g., small EC2 instances or Lambda functions.

Please let us know if your case is fixed so we can investigate and fix the remaining cases.

**Comment by SanditZZ** [comment]
+1 
Anyone found a solution for this yet? Any suggestions would be appreciated.

**Comment by mattkindy** [comment]
Still seeing this on 6.4.1

**Comment by aqrln** [comment]
@SanditZZ please provide more information and a reproduction. The only case that has been confirmed so far was fixed in Prisma 5.22.0 (the one that most people in this issue except the original reporter seemed to have encountered). Just writing "+1" with no context in an issue where people discussed multiple unrelated things doesn't make it possible for us to help you.

**Comment by SanditZZ** [comment]
@aqrln  Thanks for replying so I remember to come back and update. Turned out it was a different issue and not related to prisma.

For my case, it was related to Next.js deployment using a docker container. We couldn't get the app to work properly when navigating to different pages, kept getting timeout errors. The issue was using bun instead of node so it's solved when we switched back to node. In case anyone's experiencing similar issues I'm putting it here.

My bad for initially thinking it was from prisma. I'm still new to debugging in production environment.

**Comment by aqrln** [comment]
@SanditZZ thanks for the additional context, this is interesting! I wouldn't expect the JavaScript runtime to matter here because the error comes from the Rust code, so it's hard to tell without debugging what exactly the problem was when running with Bun. Thinking that the root cause was in Prisma was a very reasonable assumption, so no worries at all. We would actually still be interested to look into it if you have a Dockerfile we can reproduce this with. But I'm glad to hear your problem is now resolved.

**Comment by Thibault2ss** [comment]
We're still having this issue. From time to time we get a bunch of `Timed out fetching a new connection from the connection pool` (`P2024`)

- `prisma: 6.5.0`
- `@prisma/client: 6.5.0`
- using AWS RDS (aurora serverless v2)

**Comment by AeinEsk** [comment]
We are having the same issue with RDS and multi value records

**Comment by rivatove** [comment]
@aqrln Experienced it again yesterday, albeit with a new error message.

```
Engine is not yet connected.
Backtrace [{ fn: "start_thread" }, { fn: "__clone3" }]
```

The modus operandi remains the same. First, there was an actual error due to temporary unavailability of the server:

```
Can't reach database server at `uri.eu-west-1.rds.amazonaws.com:3306`

Please make sure your database server is running at `uri.eu-west-1.rds.amazonaws.com:3306`.
```

Then, the connection errors started coming in and I had to manually restart my app server.

EDIT: I just realized I'm still using the below snippet. I was under the impression that the "$disconnect" call would auto-reconnect but if it does not, it could explain these errors as well.

```ts
  prisma.$on(
    'error',
    throttle((e) => {
      if (
        [
          `Can't reach database server`,
          `Timed out fetching a new connection from the connection pool`,
        ].some((msg) => e.message.includes(msg))
      )
        prisma.$disconnect().catch((e) => {
          logger.error(e);
        });
    }, 5000),
  );
```

**Comment by rbgadotti** [comment]
Same issue with Vercel + Prisma + Supabase

**Comment by rhuntuco** [comment]
Same issue with Vercel + Prisma + Neon.

**Comment by onahkenneth** [comment]
Same issue with Remix + Prisma + PostgreSQL

**Comment by jarrvis** [comment]
Same issue: DigitalOcean + Postgres (Prisma ORM). It happens independent from traffic, lots of connection slots available in the pool

**Comment by jddeltoro** [comment]
Same problem with NestJS+Prisma api deployed to EC2 with Postgres RDS. Solved only by waiting a lot of time(10mins) the api autorecovers once the connection pool has free connections, or manually deploy the system. 

I implemented a  solution that does the following :
1-Cloudwatch Metrics to detect the error
2-Cloudwatch Alert to send a message to an SNS topic
3-SNS sends Email alerts to the dev team and also Event Messages to a webhook in the API
4-The api detects and processes the SNS message and invokes an action using the GH api to trigger an autodeploy of the system.

This way, every time the errors happen, an automatic deploy solves the problem, it works, but it is a horribly overengineered design to solve what should be a simple problem. If anyone has a better solution, please tag me.

**Comment by jddeltoro** [comment]
I did not read the full thread. Now that I have done it, I hope this can be fixed by migrating to the most current versions. I'm currently using Prisma 5.9.1. I will upgrade my API and check if the issue happens again

**Comment by rohitspujari** [comment]
Is there a resolution on this Prisma team? We're also facing the same issue, now happening almost every day. 

`Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 25)`

FYI the db connects fine through dbeaver.

**Comment by onahkenneth** [comment]
The root cause of the timeouts in my case was an N+1 query problem. Resolved it and the timeouts stopped

**Comment by horyd** [comment]
> The root cause of the timeouts in my case was an N+1 query problem. Resolved it and the timeouts stopped

This appears to have been the issue in my case too

**Comment by lustsazeus-lab** [comment]
Given the P1001 -> P2024 pattern, your recovery idea is reasonable, but I’d add a guard so reconnects are rate-limited (to avoid disconnect storms under load).

Useful triage signals here are pool wait time and connection acquisition latency right before failure bursts. If those spike while DB CPU/connections stay moderate, it points more to client pool starvation than pure DB outage.

If helpful, I can sketch a minimal circuit-breaker + jittered reconnect policy for Prisma clients in multi-node deployments.

**Comment by rivatove** [comment]
This issue has historically been fixed by the Prisma team. Unfortunately, I started seeing a similar issue starting from Prisma 7.5 (or, much less likely, 7.6). It stopped occurring after reverting to 7.4.2.
