### ISSUE TITLE
Typing error when using omit without preview feature

### ISSUE THREAD

**Issue by WikiRik** [prisma/prisma#25992]
### Bug description

TypeScript will throw an error when trying to use the global omit feature in 6.2.0 without the feature on.
The error it throws is `Object literal may only specify known properties, and 'omit' does not exist in type 'Subset<PrismaClientOptions, PrismaClientOptions>'.ts(2353)`

I have a hunch some usages of `context.isPreviewFeatureOn('omitApi')` still need to be removed in the codebase.

### How to reproduce

I followed the first four steps of the [sqlite quickstart](https://www.prisma.io/docs/getting-started/quickstart-sqlite) and wanted to adapt the script.ts with the following prisma;

```
const prisma = new PrismaClient({
    omit: {
      user: {
        name: true
      }
    }
  })
```

### Expected behavior

TypeScript does not throw an error.

### Prisma information

Taken from the [sqlite quickstart](https://www.prisma.io/docs/getting-started/quickstart-sqlite)

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User    @relation(fields: [authorId], references: [id])
  authorId  Int
}
```

```ts
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient({
    omit: {
      user: {
        name: true
      }
    }
  })

async function main() {
    const user = await prisma.user.create({
        data: {
          name: 'Alice',
          email: 'alice@prisma.io',
        },
      })
      console.log(user)
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })
```

### Environment & setup

- OS:  Ubuntu 24.04, in personal project using a devcontainer with `mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm`
- Database:  sqlite, but also on personal project using postgres
- Node.js version:  20.16.0 and on personal project also 22.12.0

### Prisma Version

```
prisma                  : 6.2.0
@prisma/client          : 6.2.0
Computed binaryTarget   : debian-openssl-3.0.x
Operating System        : linux
Architecture            : x64
Node.js                 : v20.16.0
TypeScript              : 5.4.5
Query Engine (Node-API) : libquery-engine 4123509d24aa4dede1e864b46351bf2790323b69 (at node_modules/@prisma/engines/libquery_engine-debian-openssl-3.0.x.so.node)
Schema Engine           : schema-engine-cli 4123509d24aa4dede1e864b46351bf2790323b69 (at node_modules/@prisma/engines/schema-engine-debian-openssl-3.0.x)
Schema Wasm             : @prisma/prisma-schema-wasm 6.2.0-14.4123509d24aa4dede1e864b46351bf2790323b69
Default Engines Hash    : 4123509d24aa4dede1e864b46351bf2790323b69
Studio                  : 0.503.0
```
(ran using `npx prisma -v`, since I do not have prisma globally installed)

**Comment by Pilfer** [comment]
Also experiencing this bug - adding the `omitApi` feature flag in the .prisma file produces the expected types.

**Comment by gcmarcello** [comment]
Yes, it is still not working despite the official announcement

**Comment by ShahedAKZ** [comment]
+1 for the issue, using Windows and Node v20 LTS

**Comment by WikiRik** [comment]
I see that work has been done on the `omitApi` in https://github.com/prisma/prisma/pull/25997 so this might get fixed in 6.2.1

**Comment by nurul3101** [comment]
6.2.1 is out: https://github.com/prisma/prisma/releases/tag/6.2.1

Can you check if everything works as expected in 6.2.1?

**Comment by tuanpq1998** [comment]
I faced the same issue with 6.2.0. After updating 6.2.1 now it works fine

**Comment by WikiRik** [comment]
Fixed for me in 6.2.1

**Comment by AizenSousuke** [comment]
I'm still getting this on node 18.18, latest prisma and prisma client (6.5.0) with and without omitApi
