### ISSUE TITLE
[6.6] WebAssembly.instantiate(): Import #0 "./query_compiler_bg.js": module is not an object or function]

### ISSUE THREAD

**Issue by medz** [prisma/prisma#26880]
### Bug description

Nitro + Prisma 6.6.0 + D1 does not work

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

https://github.com/medz/nitro-prisma-6.6

### Expected vs. Actual Behavior

Expected behavior: WASM modules can be parsed normally

### Frequency

Consistently reproducible

### Does this occur in development or production?

Only in development (e.g., CLI tools, migrations, Prisma Studio)

### Is this a regression?

Prisma: 6.6.0
Nitro: 2.11.9
wrangler: 4.10.0

### Workaround

-

### Prisma Schema & Queries

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

generator client {
  provider        = "prisma-client"
  output          = "./client/"
  previewFeatures = ["driverAdapters"]
  runtime         = "cloudflare"
}

model Result {
  id        String   @id @default(uuid(7))
  createdAt DateTime @default(now())
}

```
```ts
import { PrismaD1 } from "@prisma/adapter-d1";
import { PrismaClient } from "~/prisma/client";

export default defineEventHandler((event) => {
  const adapter = new PrismaD1(event.context.cloudflare.env.DB as any);
  const client = new PrismaClient({ adapter });
});

```

### Logs & Debug Info

```
$ nitro dev

 ╭─────────────────────────────────────────────────────────╮
 │                                                         │
 │  🔥 Cloudflare context bindings enabled for dev server  │
 │                                                         │
 │  Config path: wrangler.toml                             │
 │  Persist dir: .wrangler/state/v3                        │
 │                                                         │
 ╰─────────────────────────────────────────────────────────╯


  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

[unwasm] Failed to parse WASM module wasm/query_compiler_bg.sqlite-afbae85635953d66.wasm: Error: [unwasm] Failed to parse wasm/query_compiler_bg.sqlite-afbae85635953d66.wasm: Error: Internal failure: parseVec could not cast the value
    at parseWasm (file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/unwasm/dist/tools.mjs:6496:11)
    at parse (file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/unwasm/dist/plugin.mjs:195:22)
    at Object.transform (file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/unwasm/dist/plugin.mjs:272:73)
    at file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/rollup/dist/es/shared/node-entry.js:22156:40 {
  [cause]: CompileError2: Internal failure: parseVec could not cast the value
      at parseVec (file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/unwasm/dist/tools.mjs:5132:19)
      at parseTypeSection (file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/unwasm/dist/tools.mjs:5148:33)
      at parseSection (file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/unwasm/dist/tools.mjs:5895:26)
      at Object.decode2 [as decode] (file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/unwasm/dist/tools.mjs:6169:29)
      at decode2 (file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/unwasm/dist/tools.mjs:6476:25)
      at parseWasm (file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/unwasm/dist/tools.mjs:6494:11)
      at parse (file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/unwasm/dist/plugin.mjs:195:22)
      at Object.transform (file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/unwasm/dist/plugin.mjs:272:73)
      at file:///Users/seven/workspace/panews-api-server/test-prisma/node_modules/rollup/dist/es/shared/node-entry.js:22156:40
}
✔ Nitro Server built in 1024ms                                                     nitro 10:46:54
[uncaughtException] [TypeError: WebAssembly.instantiate(): Import #0 "./query_compiler_bg.js": module is not an object or function]
```

### Environment & Setup

- **OS:** 
- **Database:** 
- **Node.js version:** 

### Prisma Version

```
Prisma schema loaded from prisma/schema.prisma
prisma                  : 6.6.0
@prisma/client          : 6.6.0
Computed binaryTarget   : darwin-arm64
Operating System        : darwin
Architecture            : arm64
Node.js                 : v23.9.0
TypeScript              : 5.8.2
Query Engine (Node-API) : libquery-engine f676762280b54cd07c770017ed3711ddde35f37a (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Schema Engine           : schema-engine-cli f676762280b54cd07c770017ed3711ddde35f37a (at node_modules/@prisma/engines/schema-engine-darwin-arm64)
Schema Wasm             : @prisma/prisma-schema-wasm 6.6.0-53.f676762280b54cd07c770017ed3711ddde35f37a
Default Engines Hash    : f676762280b54cd07c770017ed3711ddde35f37a
Studio                  : 0.511.0
```

**Comment by medz** [comment]
It is very noteworthy that this does not exist in prisma 6.5 and everything works fine. This problem only occurs after upgrading to 6.6.

**Comment by nurul3101** [comment]
I was able to reproduce the error based on the reproduction repository:

<img width="1117" alt="Image" src="https://github.com/user-attachments/assets/341161fa-30c5-4a1b-9163-02d41bee3f79" />

Interestingly, when I tried downgrading to version 6.5.0, I got this error as well:

<img width="1117" alt="Image" src="https://github.com/user-attachments/assets/69384dfc-bb32-4a9b-9b7c-059df05c1de5" />

**Comment by medz** [comment]
> I was able to reproduce the error based on the reproduction repository:
> 
> <img alt="Image" width="1117" src="https://private-user-images.githubusercontent.com/13049676/434313884-341161fa-30c5-4a1b-9163-02d41bee3f79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ4MTMzMDUsIm5iZiI6MTc0NDgxMzAwNSwicGF0aCI6Ii8xMzA0OTY3Ni80MzQzMTM4ODQtMzQxMTYxZmEtMzBjNS00YTFiLTkxNjMtMDJkNDFiZWUzZjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE2VDE0MTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMDRkMWZmNDBlZTA4MTJmZTU2YmQ2MTU1MTBkYjFkZDQ5MTJkMzgzOTRhOWMwOTAyZTIxOGFmNmM0NzlhNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2l61uMTmXczicrgpl40MN3W1i0sL6e1F-Owy_ZOGeJo">
> Interestingly, when I tried downgrading to version 6.5.0, I got this error as well:
> 
> <img alt="Image" width="1117" src="https://private-user-images.githubusercontent.com/13049676/434314144-69384dfc-bb32-4a9b-9b7c-059df05c1de5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ4MTMzMDUsIm5iZiI6MTc0NDgxMzAwNSwicGF0aCI6Ii8xMzA0OTY3Ni80MzQzMTQxNDQtNjkzODRkZmMtYmIzMi00YTliLTliN2MtMDU5ZGYwNWMxZGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDE2VDE0MTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNTFiMWU3YWNjMjEyMzU3NTBmZTQzMDFhYjI1YWM2NDY0ZGY0NTY5ZDc1NmQ3YTQwMTJlYTk1MjY5ZTgxYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LbS7VUwcbUmy-5USCqAPRG1bomrMWHOzyHYT1bhfKjI">

I don't know why, I completely discarded the code changes for upgrading to 6.6, and then went back to the previous commit to make it work. In the repo, once the 6.6.0 version is installed, downgrading will not work at all.

I also tried deleting the lock file and deleting `node_modules`, but it still didn't work. Finally, I chose git to roll back to the commit before the upgrade and finally I can continue to work on the 6.5.x version.

**Comment by medz** [comment]
> Interestingly, when I tried downgrading to version 6.5.0, I got this error as well:

The reason why the build still fails in Prisma 6.5 is because prisma uses __dirname, which is not supported in esm.

My solution is to write a patch file and apply it between builds. Replace __dirname with import.meta.url compatible code.

**Comment by aqrln** [comment]
> It is very noteworthy that this does not exist in prisma 6.5 and everything works fine. This problem only occurs after upgrading to 6.6.

You also switched to the experimental new generator, not just upgraded. Does the issue occur for you in the old `prisma-client-js` generator on 6.6?

**Comment by medz** [comment]
> > It is very noteworthy that this does not exist in prisma 6.5 and everything works fine. This problem only occurs after upgrading to 6.6.
> 
> You also switched to the experimental new generator, not just upgraded. Does the issue occur for you in the old `prisma-client-js` generator on 6.6?
@aqrln 
No, I tried again the other day to upgrade to Prisma 6.6.0 and continued to use the `prisma-js-client` generator.

Everything works fine now.

**Comment by medz** [comment]
> > > It is very noteworthy that this does not exist in prisma 6.5 and everything works fine. This problem only occurs after upgrading to 6.6.
> > 
> > 
> > You also switched to the experimental new generator, not just upgraded. Does the issue occur for you in the old `prisma-client-js` generator on 6.6?


 [@aqrln](https://github.com/aqrln)

 No, I tried again the other day to upgrade to Prisma 6.6.0 and continued to use the `prisma-js-client` generator.

Everything works fine now.

**Comment by medz** [comment]
I just tried `prisma-client` on this and the problem persists. This only happens on new builds.

**Comment by takakikasuga** [comment]
I just have encounterd this problem.
since once updgraded to v6.6, even if v6.5 re-install, application keep crash...

my environment is cloudflare pages and uses [cloudflare-next-on-pages](https://github.com/cloudflare/next-on-pages)...

```
WebAssembly.Instance(): Import #0 "./query_engine_bg.js" "__wbindgen_string_get": function import requires a callable
```

**Comment by FGoessler** [comment]
Nitro seems to be bundling stuff a bit different than raw cloudflare. It behaves more like an `edge-light` runtime.

@medz can you try if you have more success when you use `runtime = "edge-light"` instead of `runtime = "cloudflare"` in your `schema.prisma` file? Maybe also use that in combination with our latest dev build `6.7.0-dev.35`.

@takakikasuga what generator are you using and do you perform a `prisma generate` between version/config changes? 6.5.0 did not have the old generator so it seems more like your local state has some outdated or cached stuff around.

**Comment by medz** [comment]
> Nitro seems to be bundling stuff a bit different than raw cloudflare. It behaves more like an `edge-light` runtime.
> 
> [@medz](https://github.com/medz) can you try if you have more success when you use `runtime = "edge-light"` instead of `runtime = "cloudflare"` in your `schema.prisma` file? Maybe also use that in combination with our latest dev build `6.7.0-dev.35`.
> 
> [@takakikasuga](https://github.com/takakikasuga) what generator are you using and do you perform a `prisma generate` between version/config changes? 6.5.0 did not have the old generator so it seems more like your local state has some outdated or cached stuff around.

After I changed the runtime to `edge-light`, the packaging was normal. But a new problem appeared. After I deployed the program to the worker, I got an error when accessing the test route:

```
WebAssembly.Instance(): Import #0 \"./query_compiler_bg.js\": module is not an object or function
```

This shows that the problem is still there, but it has been transferred from the compilation period to the runtime period.

**Comment by medz** [comment]
I think there's a problem here：

https://github.com/prisma/prisma/blob/main/packages/client/src/runtime/core/engines/client/ClientEngine.ts#L86
https://github.com/prisma/prisma/blob/main/packages/client/src/runtime/core/engines/client/WasmQueryCompilerLoader.ts#L43-L44

**Comment by medz** [comment]
<img width="362" alt="Image" src="https://github.com/user-attachments/assets/e841752f-a0d7-4730-8130-62e910e2398b" />

**Comment by medz** [comment]
https://github.com/prisma/prisma-engines/blob/79e5a4a6ca3f5e9d77e1d6ed61402319cb053a85/libs/driver-adapters/executor/src/query-compiler-wasm.ts#L37-L39

**Comment by medz** [comment]
<img width="1389" alt="Image" src="https://github.com/user-attachments/assets/3d918f35-5d89-4a3a-8f31-07df672381e0" />

Prisma 6.7.0-dev is still available

**Comment by taylor-lindores-reeves** [comment]
+1 Same issue here 

<img width="662" alt="Image" src="https://github.com/user-attachments/assets/cbf80139-3345-4772-a905-28d48f571601" />

Running NextJS 15@canary with `nodeMiddleware: true`

**Comment by jacek-prisma** [comment]
Hi @medz ,
I think this should be resolved in 6.9.0, can you retry?

**Comment by medz** [comment]
> Hi [@medz](https://github.com/medz) , I think this should be resolved in 6.9.0, can you retry?

OK, I will verify later. I have updated to version 6.9.0, but I dare not use generator=Prisma client. I am still using 'Prisma client js' and have developed my own API interface to simulate the Planetscale API. I successfully ran it on the worker using the Planetscale adapter.

I will try to write a minimal worker code to verify if it is still a problem.

**Comment by medz** [comment]
@jacek-prisma We are happy to announce that this issue has been resolved. My configuration:
```prisma
generator experimental {
  provider        = "prisma-client"
  previewFeatures = ["driverAdapters", "queryCompiler"]
  output          = "../src/generated/prisma"
  runtime         = "workerd"
}
```
```ts
import { PrismaClient } from '../../generated/prisma';
import type { SecretsStoreSecret } from '@cloudflare/workers-types';
import { PrismaPlanetScale } from '@prisma/adapter-planetscale';

type Env = { DATABASE_URL: SecretsStoreSecret };

export default {
  async fetch(_: Request, env: Env) {
    const adapter = new PrismaPlanetScale({
      url: await env.DATABASE_URL.get(),
    });
    // @ts-expect-error
    const prisma = new PrismaClient({ adapter });
    const topics = await prisma.topic.findMany({ take: 3 });

    return Response.json(topics);
  },
};
```

However, there is still a problem with `prisma-client`. PrismaClient does not support the `adapter` parameter, but this does not affect the use of the function.

It is worth noting that the package size of the same code once reached `3033.04 KiB / gzip: 1054.53 KiB`, but now it is only `2273.59 KiB / gzip: 803.94 KiB`, which is a very big improvement.👍

**Comment by medz** [comment]
无论此问题是否解决，我应该仍然会继续使用 `prisma-client-js`。通过 issue 发现 `prisma-client` 并不稳定。现在我会在测试环境使用它。

**Comment by IHIutch** [comment]
Hm, I'm still getting this issue with 6.9.0

```
PrismaClientKnownRequestError: 
Invalid `prisma.users.findUnique()` invocation:


Cannot find module '@prisma/client/runtime/query_compiler_bg.postgresql.wasm'
Require stack:
- /var/task/index.mjs
````

I'm using TanStack Start in a Turborepo monorepo on Vercel. 

This is my prisma schema:

```
generator client {
  provider        = "prisma-client"
  output          = "../generated/prisma"
  previewFeatures = ["relationJoins", "queryCompiler", "driverAdapters"]
}
```

Related? https://github.com/prisma/prisma/issues/27083

**Comment by medz** [comment]
> Hm, I'm still getting this issue with 6.9.0
> 
> ```
> PrismaClientKnownRequestError: 
> Invalid `prisma.users.findUnique()` invocation:
> 
> 
> Cannot find module '@prisma/client/runtime/query_compiler_bg.postgresql.wasm'
> Require stack:
> - /var/task/index.mjs
> ```
> 
> I'm using TanStack Start in a Turborepo monorepo on Vercel.
> 
> This is my prisma schema:
> 
> ```
> generator client {
>   provider        = "prisma-client"
>   output          = "../generated/prisma"
>   previewFeatures = ["relationJoins", "queryCompiler", "driverAdapters"]
> }
> ```
> 
> Related? [#27083](https://github.com/prisma/prisma/issues/27083)

I'm sorry I closed the issue directly because I always encountered this problem on cloudflare worker, so I defaulted to linking similar issues to worked.

If you still encounter it, I think the Prisma team should reopen it or track it in a new issue.

**Comment by aaly00** [comment]
I am running into this on github actions on 6.9

**Comment by jkomyno** [comment]
@IHIutch about https://github.com/prisma/prisma/issues/26880#issuecomment-2961029461

> generator client {
>   provider        = "prisma-client"
>   output          = "../generated/prisma"
>   previewFeatures = ["relationJoins", "queryCompiler", "driverAdapters"]
> }

Can you please try with the following

```diff
  generator client {
    provider        = "prisma-client"
    output          = "../generated/prisma"
    previewFeatures = ["relationJoins", "queryCompiler", "driverAdapters"]
+   runtime         = "edge-light"
  }
```

and report back? Thanks

**Comment by IHIutch** [comment]
Hm, I updated my config to this:

```
generator client {
  provider        = "prisma-client"
  output          = "../src/generated/client"
  previewFeatures = ["relationJoins", "queryCompiler", "driverAdapters"]
  runtime         = "edge-light"
}
```
 (wasn't sure if not having files in my src dir was causing issues...)

Still getting this error: 
```
gtm-start:build: error during build:
gtm-start:build: Error: Could not load /vercel/path0/node_modules/.pnpm/@prisma+client@6.9.0_prisma@6.9.0_typescript@5.8.3__typescript@5.8.3/node_modules/@prisma/client/runtime/query_compiler_bg.postgresql.wasm?module (imported by ../../packages/database/src/generated/client/internal/class.ts): ENOENT: no such file or directory, open '/vercel/path0/node_modules/.pnpm/@prisma+client@6.9.0_prisma@6.9.0_typescript@5.8.3__typescript@5.8.3/node_modules/@prisma/client/runtime/query_compiler_bg.postgresql.wasm?module'
gtm-start:build:     at async open (node:internal/fs/promises:633:25)
gtm-start:build:     at async readFile (node:internal/fs/promises:1237:14)
gtm-start:build:     at async file:///vercel/path0/node_modules/.pnpm/rollup@4.41.1/node_modules/rollup/dist/es/shared/node-entry.js:21140:24
gtm-start:build:     at async Queue.work (file:///vercel/path0/node_modules/.pnpm/rollup@4.41.1/node_modules/rollup/dist/es/shared/node-entry.js:22359:32)
gtm-start:build:  ELIFECYCLE  Command failed with exit code 1.
gtm-start:build: ERROR: command finished with error: command (/vercel/path0/apps/backend) /pnpm10/node_modules/.bin/pnpm run build exited (1)
gtm-start#build: command (/vercel/path0/apps/backend) /pnpm10/node_modules/.bin/pnpm run build exited (1)
```

I've been bouncing between a few different issues with various configurations, here's some more details https://github.com/prisma/prisma/issues/27083#issuecomment-2980748717

**Comment by jkomyno** [comment]
Hey @IHIutch, please see [this example](https://github.com/prisma/prisma-examples/tree/latest/generator-prisma-client/nextjs-starter-webpack-with-middleware) for a reference project using both the `edge-light` and `nodejs` runtimes in a Next.js project, with the `prisma-client` generator. It builds and runs locally (as well as on Vercel) for me with Prisma 6.11.0.

**Comment by IHIutch** [comment]
I updated [my prisma configuration](https://github.com/IHIutch/getthemenu/tree/71773b3273e7d7e609da7552924b620d1e84279d/packages/database) to match the monorepo example but Im still seeing this error:

```
Invalid `prisma.users.findUnique()` invocation:


Cannot find module '/var/task/node_modules/@prisma/client/runtime/query_compiler_bg.postgresql.wasm'
```

Fwiw. I am using Turborepo and Vite. Not sure to what extent those would affect the output.

**Comment by jkomyno** [comment]
Hi @IHIutch, I think you bumped into a `vite-tsconfig-paths` plugin bug (independent of Prisma).
You can find technical details on [Discord](https://discord.com/channels/804011606160703521/1201533611468398612/1390617713348448328).

If you remove `vite-tsconfig-paths`, `prisma-client` should work out of the box with Prisma 6.11.0.

**Comment by IHIutch** [comment]
@jkomyno Really appreciate you looking into this. This is working now 🙏

For anyone else experiencing this: 
- I removed `vite-tsconfig-paths` from my Vite config
- Updated all my imports to be relative path
- Updated my prisma schema to use `provider = "prisma-client"`
   - And everything else needed for `prisma-client`

So far so good. Thank you!

---

Question based on the [monorepo example](https://github.com/prisma/prisma-examples/tree/latest/generator-prisma-client/nextjs-starter-webpack-monorepo): Is there an expectation that you'd need to build your prisma package before importing? Iirc, the other guides demonstrate being able to import without a build step in `/package/prisma`

**Comment by IHIutch** [comment]
Following up here: I am still running into [this issue](https://github.com/prisma/prisma/issues/26880#issuecomment-3042103689) at runtime, using the postrges adapter, even with the `vite-tsconfig-paths` fix.

**Comment by jkomyno** [comment]
> Question based on the [monorepo example](https://github.com/prisma/prisma-examples/tree/latest/generator-prisma-client/nextjs-starter-webpack-monorepo): Is there an expectation that you'd need to build your prisma package before importing? Iirc, the other guides demonstrate being able to import without a build step in /package/prisma

This is not necessarily needed. [Here's another example using Turborepo](https://github.com/prisma/prisma-examples/pull/8243) where the package containing Prisma definitions isn't built. The trick is to use `exports` map: https://github.com/prisma/prisma-examples/blob/79440c034c91d6614c4849c8cedfede4a1cb7902/generator-prisma-client/nextjs-starter-webpack-turborepo/packages/database/package.json#L5-L8

**Comment by medz** [comment]
I have this problem again!

---
> 2025-07-29 Updated

I upgraded Prisma from 6.10 to 6.12 and it happened again. But I switched runtime cong
`workerd` to `edge-light` and it worked fine.

**Comment by medz** [comment]
Changing runtime to `edge-light` can temporarily solve the problem!

```diff
generator client {
    provider        = "prisma-client"
    previewFeatures = ["driverAdapters", "queryCompiler", "typedSql"]
    output          = "../src/generated/prisma"
-   runtime         = "workerd"
+   runtime         = "edge-light"
}
```

**Comment by jkomyno** [comment]
Hi @medz, @IHIutch and others, can you please try this integration version of Prisma: [prisma@6.14.0-integration-feat-client-wasm-base64-on-nodejs.6](https://www.npmjs.com/package/prisma/v/6.14.0-integration-feat-client-wasm-base64-on-nodejs.6) (from https://github.com/prisma/prisma/pull/27795) and report back?

Make sure to re-run `prisma generate` after the update.

Handy update script for your projects:
```
pnpm update "@prisma/*"@6.14.0-integration-feat-client-wasm-base64-on-nodejs.6
pnpm update "prisma"@6.14.0-integration-feat-client-wasm-base64-on-nodejs.6
pnpm prisma generate
```

We aim to stabilize the `prisma-client` generator as "generally available" within the next 3 weeks, so your feedback is helpful!
Thanks

**Comment by medz** [comment]
<img width="792" height="625" alt="Image" src="https://github.com/user-attachments/assets/81eb0f0d-a210-4726-9692-9b3eada9345b" />

<img width="780" height="235" alt="Image" src="https://github.com/user-attachments/assets/9b8b00ec-9b99-4662-a45c-3418850dd14a" />

<img width="819" height="291" alt="Image" src="https://github.com/user-attachments/assets/48d3ac15-4afe-49a9-85bb-36f50c3b0072" />

<img width="834" height="326" alt="Image" src="https://github.com/user-attachments/assets/60e4b9e6-e06e-4f53-9fab-2a09d4f79797" />

<img width="834" height="319" alt="Image" src="https://github.com/user-attachments/assets/15dd540b-05ac-455c-a518-862373191768" />

@jkomyno still

**Comment by tobiasdiez** [comment]
See https://github.com/unjs/unwasm/issues/21#issuecomment-3090187078 for details about this parseVec issue.

**Comment by jkomyno** [comment]
Ok, that's a different issue though depending on Nuxt / unwasm specifically though, no?

You should no longer face "Import #0 "./query_compiler_bg.js": module is not an object or function" errors.
I'll create a new issue to specifically track `parseVec` / `0x6f` incompatibilities, which only seem to affect our SQLite query compiler.

**Comment by datagutt** [comment]
I do not think parseVec is limited to sqlite query compiler.
I am seeing the parseVec error with Next 14.2.31, using postgresql with driverAdapters and neondatabase adapter.
This is using "edge-light" runtime, prisma-client (both with and without queryCompiler).

**Comment by tobiasdiez** [comment]
With the latest version 6.14 I now get during build:
```
[warn] [unwasm] Failed to parse WASM module wasm/query_compiler_bg.postgresql.wasm-base64.mjs-77efa594fc3f7375.wasm: [unwasm] Failed to parse wasm/query_compiler_bg.postgresql.wasm-base64.mjs-77efa594fc3f7375.wasm: Error: magic header not detected
  at parseWasm (node_modules/.pnpm/unwasm@0.3.9/node_modules/unwasm/dist/tools.mjs:6496:11)
  at parse (node_modules/.pnpm/unwasm@0.3.9/node_modules/unwasm/dist/plugin.mjs:195:22)
  at Object.transform (node_modules/.pnpm/unwasm@0.3.9/node_modules/unwasm/dist/plugin.mjs:272:73)
  at node_modules/.pnpm/rollup@4.44.2/node_modules/rollup/dist/es/shared/node-entry.js:22276:40

  [cause]: magic header not detected
    at parseModuleHeader (node_modules/.pnpm/unwasm@0.3.9/node_modules/unwasm/dist/tools.mjs:5101:17)
    at Object.decode2 [as decode] (node_modules/.pnpm/unwasm@0.3.9/node_modules/unwasm/dist/tools.mjs:6158:7)
    at decode2 (node_modules/.pnpm/unwasm@0.3.9/node_modules/unwasm/dist/tools.mjs:6476:25)
    at parseWasm (node_modules/.pnpm/unwasm@0.3.9/node_modules/unwasm/dist/tools.mjs:6494:11)
    at parse (node_modules/.pnpm/unwasm@0.3.9/node_modules/unwasm/dist/plugin.mjs:195:22)
    at Object.transform (node_modules/.pnpm/unwasm@0.3.9/node_modules/unwasm/dist/plugin.mjs:272:73)
    at node_modules/.pnpm/rollup@4.44.2/node_modules/rollup/dist/es/shared/node-entry.js:22276:40
```
(see CI at https://github.com/JabRef/JabRefOnline/pull/2647)

@jkomyno What do you think about adding a special option to use [unwasm's `?module`](https://github.com/unjs/unwasm?tab=readme-ov-file#module-compatibility) imports similar to this patch https://github.com/JabRef/JabRefOnline/blob/b94a868489a29a22ea56c8be30a0653d973f6dc2/patches/prisma.patch? This should simplify the loading quite a bit for nitro/nuxt projects.

**Comment by jkomyno** [comment]
Hey @tobiasdiez, I fixed your issue in https://github.com/JabRef/JabRefOnline/pull/2647#issuecomment-3196069757.

Since @medz' original issue was resolved in https://github.com/prisma/prisma/issues/26880#issuecomment-2955520340, I will now close this issue.

Thank you!

**Comment by Ehbraheem** [comment]
This is unresolved @jkomyno. Check https://github.com/unjs/unwasm/issues/21#issuecomment-3271809938

**Comment by medz** [comment]
> This is unresolved [@jkomyno](https://github.com/jkomyno). Check [unjs/unwasm#21 (comment)](https://github.com/unjs/unwasm/issues/21#issuecomment-3271809938)

<img width="1376" height="374" alt="Image" src="https://github.com/user-attachments/assets/abbfd9d7-e33f-4be4-a6bb-fd3c801c25d1" />

I did encounter a regression. Setting up `workerd` worked in a previous update, but the issue persists in the latest version of Prisma, `6.15.0`.

My solution was to set `runtime = "edge-light"`. See: https://github.com/prisma/prisma/issues/26880#issuecomment-3126415106

**Comment by Ehbraheem** [comment]
> > This is unresolved [@jkomyno](https://github.com/jkomyno). Check [unjs/unwasm#21 (comment)](https://github.com/unjs/unwasm/issues/21#issuecomment-3271809938)
> 
> <img alt="Image" width="1376" height="374" src="https://private-user-images.githubusercontent.com/5564821/487433403-abbfd9d7-e33f-4be4-a6bb-fd3c801c25d1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc0NDc3NjMsIm5iZiI6MTc1NzQ0NzQ2MywicGF0aCI6Ii81NTY0ODIxLzQ4NzQzMzQwMy1hYmJmZDlkNy1lMzNmLTRiZTQtYTZiYi1mZDNjODAxYzI1ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA5MDlUMTk1MTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTdkZGVhZDQ4MjdlMzgzMDQ0Zjk0ZjFkZjVhYzQ5YmFkOThhMGY2YzQ3ODA0ZmMzZjZkNWI3YjEyMTk4YWIwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.e7BX9wsaok_YYUy9FcNgVd7mOixTJHkD63Z3LYe59hw">
> 
> I did encounter a regression. Setting up `workerd` worked in a previous update, but the issue persists in the latest version of Prisma, `6.15.0`.
> 
> My solution was to set `runtime = "edge-light"`. See: [#26880 (comment)](https://github.com/prisma/prisma/issues/26880#issuecomment-3126415106)

Thanks @medz. It's not working in the test environment. I'm currently using Vitest with Cloudflare worker pool
