### ISSUE TITLE
Error validating datasource `db`: the URL must start with the protocol `prisma://` or `prisma+postgres://`

### ISSUE THREAD

**Issue by j-beniwal** [prisma/prisma#27253]
I am using vercel for hosting nestjs app with next auth, 

I have configured the database_url variable already and it starts with postgres://user:password@host/db

getting below error what is the cause 

[31m[auth][cause][0m: PrismaClientKnownRequestError: 
Invalid `prisma.account.findUnique()` invocation:

Error validating datasource `db`: the URL must start with the protocol `prisma://` or `prisma+postgres://`
    at l$.handleRequestError (/var/task/.next/server/chunks/969.js:114:7967)
    at l$.handleAndLogRequestError (/var/task/.next/server/chunks/969.js:114:7049)
    at l$.request (/var/task/.next/server/chunks/969.js:114:6756)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async s (/var/task/.next/server/chunks/969.js:126:6317)
    at async getUserByAccount (/var/task/.next/server/chunks/314.js:1:47625)
    at async r.<computed> (/var/task/.next/server/chunks/314.js:1:104839)
    at async aj (/var/task/.next/server/chunks/314.js:404:40181)
    at async aZ (/var/task/.next/server/chunks/314.js:404:51771)
    at async aq (/var/task/.next/server/chunks/314.js:404:56463)

**Comment by jacek-prisma** [comment]
Hi @j-beniwal, can you provide the prisma schema file and the command you run?

**Comment by MarcioJrios** [comment]
I stumbled upon this issue as well. My project was working fine, but this week I started working on a multiple databases implementation, and since I made the changes in [this](https://www.prisma.io/docs/guides/multiple-databases) guide this error started to occur.

**Comment by MarcioJrios** [comment]
> I stumbled upon this issue as well. My project was working fine, but this week I started working on a multiple databases implementation, and since I made the changes in [this](https://www.prisma.io/docs/guides/multiple-databases) guide this error started to occur.

Nevermind. My problem in this case was because I was still using the `--no-engine` flag when using prisma generate, and my database is not a Prisma Postgress

**Comment by zhouLion** [comment]
I'm having the same issue when I configure two schemas.

![Image](https://github.com/user-attachments/assets/5b1e0abe-a0c1-4e62-8548-7983fc2fe65c)

---

### package.json
``` 
    "prisma:generate": "prisma generate --schema ./prisma/schema.prisma --no-engine=false && prisma generate --schema ./prisma-mongo/schema.prisma --no-engine=false",

```

### One of the prisma.schema

![Image](https://github.com/user-attachments/assets/198bb8d2-fff4-4a1e-80ac-1eb68b900e45)

**Comment by pulkitgxrg** [comment]
I was having the same problem but then I figured it out that I was using --no-engine in the production, just removed it and it was solved. Hope it helps.

**Comment by The-Lone-Druid** [comment]
## 🐛 Issue Resolution: `prisma://` Protocol Error with Local or non-edge Database

**Problem:** Getting `Error validating datasource 'db': the URL must start with the protocol 'prisma://' or 'prisma+postgres://'` when using a local PostgreSQL database.

**Root Cause:** The `--no-engine` flag was being used during Prisma client generation, which creates an edge-compatible client that expects Prisma Accelerate/Pulse cloud services instead of direct database connections.

**Solution:** 
Remove the `--no-engine` flag from your Prisma generation commands and regenerate the client:

```bash
# Instead of: npx prisma generate --no-engine
npx prisma generate

# Regenerate to fix existing client
npx prisma generate
```

**Explanation:**
- `--no-engine` generates a client for edge environments that requires `prisma://` URLs (Accelerate/Pulse)
- Standard Prisma clients connect directly using `postgresql://`, `mysql://`, etc.
- For local development, use the standard client without `--no-engine`

**Environment Setup:**
```env
# ✅ Correct for local PostgreSQL
DATABASE_URL="postgresql://user:password@localhost:5432/database"

# ❌ Only for Prisma Accelerate
DATABASE_URL="prisma+postgres://..."
```

This resolves the protocol validation error and allows normal database operations with local PostgreSQL instances.

**Comment by Okafor-Ifeanyi** [comment]
Error validating datasource `db`: the URL must start with the protocol `prisma://` or `prisma+postgres://`

Getting this same issue on NestJS where I don't call my npx prisma generate directly

This is my schema setup

datasource db {
  provider = "postgresql"
}
generator client {
  provider = "prisma-client-js"
  output   = "../generated/prisma"
}

but I still get the error, Please how do I proceed
