### ISSUE TITLE
RangeError: Invalid array buffer length in WASM when using Prisma Client in Cloudflare Workers

### ISSUE THREAD

**Issue by kevinsimper** [prisma/prisma#28012]
### Bug description

We're encountering a production error with Prisma Client in Cloudflare Workers that results in an "Invalid array buffer length" error. This appears to be related to WASM memory allocation issues within the Prisma engine. The critical issue is that this error persists until we redeploy the worker - no other fix works.

### Severity

🚨 Critical: Data loss, app crash, security issue

### Reproduction

Har do reproduce, there is something about testing memory, but it happens randomly and suddenly persists.
https://github.com/prisma/prisma/issues/25714

  RangeError: Invalid array buffer length
      at Uint8Array.subarray (<anonymous>)
      at f (index.js:59:6937)
      at yt (index.js:60:4832)
      at wasm://wasm/0085bf12:wasm-function[6030]:0x1f0934
      at wasm://wasm/0085bf12:wasm-function[1977]:0x19c67f
      at wasm://wasm/0085bf12:wasm-function[4285]:0x1d18d5
      at new V (index.js:60:6241)
      at A0e.loadEngine (index.js:53:15178)
      at async A0e.instantiateLibrary (index.js:53:14414)

### Expected vs. Actual Behavior

That either Cloudflare Worker restarts or that Prisma does not have a RangeError

### Frequency

Intermittent / Random

### Does this occur in development or production?

Only in production (e.g., query engine, generated client)

### Is this a regression?

I have not seen any previous prisma versions where it worked, I also experienced it in 6.5.0

Upgraded to see if it was fixed, and upgraded from prisma-client-js to prisma-client and I am getting the same error. https://github.com/prisma/prisma/issues/27662#issuecomment-3219769055

### Workaround

Only a redeploy works since Cloudflare does not mark the isolate as crashed even though all new requests will fail.

### Prisma Schema & Queries

No relevant

### Prisma Config

```prisma
  generator client {
    provider        = "prisma-client"
    previewFeatures = ["driverAdapters"]
    output          = "../generated"
    runtime = "workerd"
  }

  datasource db {
    provider     = "sqlite"
    url          = env("DATABASE_URL")
    relationMode = "prisma"
  }
```

### Logs & Debug Info

```
// Debug logs here
```

### Environment & Setup

  - Runtime: workerd (Cloudflare Workers)
  - Environment: Cloudflare Workers (production)
  - Database: Cloudflare D1 (SQLite)

### Prisma Version

  - Prisma version: 6.15.0
  - @prisma/client version: 6.15.0
  - @prisma/adapter-d1 version: 6.15.0

**Comment by fongfan999** [comment]
I'm also having the same issue!

**Comment by aqrln** [comment]
Could you check if you are still facing the issue if you enable `queryCompiler` preview feature?

**Comment by aiji42** [comment]
I’m experiencing the same error with Prisma `v6.16.2` (latest at the time of writing).

**Environment**
- prisma: v6.16.2
- @prisma/client: v6.16.2
- @prisma/adapter-pg: v6.16.2
- Running on Cloudflare Workers
- Connecting to Supabase Postgres via Hyperdrive
- Using Rust-free client (`engineType = "client"`) with `workerd` runtime
```
generator client {
  provider        = "prisma-client"
  engineType      = "client"
  runtime         = "workerd"
  previewFeatures = ["relationJoins"]
}
```

**Error**
```
PrismaClientUnknownRequestError: 
Invalid `prisma.[maskedTableName].findUniqueOrThrow()` invocation:

Invalid array buffer length
```
- The error occurs in the WASM-based query builder part of the client.
- It does not always occur, but once it starts, it persists for tens of minutes to hours.
- It happens with `findMany`, `findFirst`, and other queries as well.
- I can reproduce it in two separate cases:
    1. Querying a table that has only a single row.
    2. Querying with select limited to just one lightweight column.
→ This suggests the issue is not related to the size of the returned dataset.
- Redeploying the Worker makes the issue temporarily disappear.
- Does not correlate directly with request volume.

This has been a persistent problem since [#25714](https://github.com/prisma/prisma/issues/25714)
I was hoping it would be resolved with the GA release of Rust-free (`engineType = "client"`) but the issue remains.

**Comment by OllieJennings** [comment]
Likewise having this issue @aqrln , on latest version of everything with new queryCompiler, only occurs once you suddenly start heavy load for me, then you need to redeploy your worker to fix, pretty critical

**Comment by karambir-zz** [comment]
I'm having the same issue as well.

**Comment by aroman** [comment]
we are also running into this issue. unfortunately, the new query compiler is unstable and not ready for production, with several known critical issues, in particular this one, which caused us even more severe issues than this WASM issue: https://github.com/prisma/prisma/issues/27990

Every day I grow to regret our decision more and more to use Prisma with Cloudflare. It has proven to be both slow and unreliable :(

**Comment by derdawid** [comment]
I think I was able to resolve the problem. 

For me the issue was due to making requests to backend APIs using service binding requests. I realized non of those problem happen when the request was coming from the browser, but happens for once done from NextJs server.  My backend and Prisma doesn't use NextJs and it's a separate project. 

That how API requests where made from UI server side

```ts
  const context = await getCloudflareContext({ async: true });
  const workerApi = context.env.WORKER_API;
  const fetchPromise = workerApi.fetch(url, requestParams);
```

I change to simple fetch and problem is gone. 
```ts
 const fetchPromise = fetch(url, requestParams);
```

**Comment by tavoyne** [comment]
Also experiencing this (6.18.0).

**Comment by aiji42** [comment]
I've been following this issue for quite some time, and it's disappointing that it still hasn’t been addressed.

In my production environment, I managed to completely eliminate this problem by isolating Prisma inside a Cloudflare Durable Object and rotating the instance periodically (in my case, every 10 minutes).

## Implementation

Here’s a simplified version of the workaround:

```ts
import { DurableObject } from "cloudflare:workers";
import { PrismaPg } from "@prisma/adapter-pg";
import dayjs from "dayjs";
import utc from "dayjs/plugin/utc";
import { PrismaClient } from "../generated/prisma/client";

dayjs.extend(utc);

const ROTATE_MIN = 10;

export class DB extends DurableObject {
  readonly #prisma: PrismaClient;

  constructor(ctx, env) {
    super(ctx, env);

    const adapter = new PrismaPg({ connectionString: env.HYPERDRIVE.connectionString });
    this.#prisma = new PrismaClient({ adapter });
  }

  get prisma(): PrismaClient {
    return this.#prisma;
  }
}

export const getPrismaClient = (env): PrismaClient => {
  const now = dayjs.utc();
  const name = `db:${now.minute(Math.floor(now.minute() / ROTATE_MIN) * ROTATE_MIN).format("YYYYMMDDHHmm")}`;
  return env.DB.getByName(name).prisma;
};
```

Usage example:
```ts
const prisma = getPrismaClient(env);
const res = await prisma.someTable.findMany({ ... });
```

This approach creates a new `DB` Durable Object instance every few minutes (10 min in my case), which means each Prisma client and its WASM runtime only live for a short window.

## Verification

In production, this setup has been running for over two months and has processed tens of thousands of queries per day without a single recurrence of the issue.

I’m connecting through Cloudflare Hyperdrive, but based on testing, Hyperdrive itself seems unrelated — the issue occurred even with a direct PostgreSQL connection.
The key stabilizing factor is clearly the periodic recreation of the Prisma client and its internal WASM engine.

## Hypothesis

The error originates in the WASM layer of Prisma, not the adapter or database connection.
Given that Cloudflare Workers’ runtime model isolates state between requests but reuses the same underlying isolate (instance) for performance, I suspect the problem comes from persistent in-memory or global WASM state leaking across requests.

Over time, this reused isolate likely retains residual state (buffers, memory mappings, or async handles) within the Prisma WASM query engine.
Eventually, this leads to an unrecoverable internal state or runtime panic.

By contrast, forcing a periodic rotation of the Durable Object (and thus the WASM instance) effectively resets that state, making the system stable again.

---

While this workaround isn’t a true fix, it’s a production-safe and verified mitigation.
It demonstrates that the root cause likely lies in the WASM engine’s lifecycle management, not in the adapter or network layer.
Hopefully this insight helps narrow down the investigation — particularly around how the WASM query engine maintains (or fails to reset) global state in reused execution contexts.

**Comment by jacek-prisma** [comment]
Hi @aiji42 @kevinsimper 
I've done extensive memory profiling based on these reports and I think they were related to memory leaks in two places. One leak was in the library engine that was recently replaced by the client engine (`engineType = "client"`) and now removed in Prisma 7. The other leak was in the pg adapter and was fixed in https://github.com/prisma/prisma/pull/28057. I can't reproduce this leak with recent versions of the client engine (6.19.0 and 7.0.0). Are you still seeing the same problem with the recent versions?

**Comment by jacek-prisma** [comment]
Hi @kevinsimper @aiji42 

I'm fairly certain this is caused by a memory leak.

I've done extensive memory profiling with the provided reproduction steps and I found a few things:
1. There appears to be a leak on repeated `new PrismaClient` calls with our old library engine. This leak does not occur on the client engine, so you should not see it in Prisma 7 or Prisma 6 with `engineType = "client"`.
2. Our D1 guides recommend users to create a new `PrismaClient` for every request. What happens in practice is that whenever a request re-uses the same runtime, we allocate additional memory within the WASM runtime without freeing WASM objects used by the previous `PrismaClient`. In theory the memory should be freed automatically through the `FinalizationRegistry` which [is supported by CF workers](https://blog.cloudflare.com/we-shipped-finalizationregistry-in-workers-why-you-should-never-use-it/), but in my tests I could see that the WASM memory buffer was growing the more requests I made. This is not surprising, because even the CF docs make it clear that `FinalizationRegistry` is not as reliable as manual memory management. I've found a really simple solution that prevents the leak and it's just calling `prisma.$disconnect()` (which manually frees the WASM memory under the hood) at the end of the exported `fetch` function. Alternatively the `PrismaClient` can be stored in a module-level variable, but storing references to the `D1Database` object globally is an anti-pattern, so I think it should be avoided. I'll make sure our guide is updated to account for this.

Basically, you should not see this error if you use Prisma 7 or Prisma 6 with `engineType = "client"` and make sure you include `await prisma.$disconnect();` after you're done using the `PrismaClient`.

**Comment by aiji42** [comment]
@jacek-prisma 

Thanks a lot for the detailed investigation and memory profiling 🙏
Really appreciate you taking the time to dig into this.

For context, I’m already running with `engineType = "client"` as mentioned in my earlier comment here:
https://github.com/prisma/prisma/issues/28012#issuecomment-3308326427

Given your explanation about `FinalizationRegistry` not reliably freeing WASM memory on Cloudflare Workers, the behavior I’m seeing makes a lot of sense.

As a next step, I’m going to update one of the higher-traffic endpoints to explicitly call:
```ts
await prisma.$disconnect();
```

after each request and verify whether that stabilizes memory usage and prevents the `RangeError: WebAssembly.Memory(): could not allocate memory` under load.
I’ll report back here once I’ve gathered some data.

---

For anyone else running Prisma on Cloudflare Workers + Hono, here’s a pattern that gives you:
- a per-request singleton `PrismaClient` (so you don’t accidentally create multiple clients in different layers/classes), and
- an automatic `prisma.$disconnect()` at the end of each request,

using `AsyncLocalStorage`.

```ts
// context.ts
import { AsyncLocalStorage } from "node:async_hooks";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

type RequestContext = {
  env: Env;
  prisma?: PrismaClient; // holds a per-request singleton PrismaClient
};

const storage = new AsyncLocalStorage<RequestContext>();

export function runWithRequestContext<T>(
  ctx: { env: Env },
  fn: () => T | Promise<T>,
): Promise<T> {
  // Start a new AsyncLocalStorage context for each request
  return storage.run(ctx, async () => {
    try {
      return await fn();
    } finally {
      // Automatically executed at the end of each request.
      // Ensures PrismaClient is always disconnected (manual WASM cleanup).
      const store = storage.getStore();
      if (store?.prisma) {
        await store.prisma.$disconnect();
        store.prisma = undefined;
      }
    }
  });
}

export function getPrisma(): PrismaClient {
  const store = storage.getStore();
  if (!store) throw new Error("No AsyncLocalStorage context found");

  // Lazily create a PrismaClient only once per request
  if (!store.prisma) {
    const adapter = new PrismaPg({
      // Hyperdrive connection string is required on Workers
      connectionString: store.env.HYPERDRIVE.connectionString,
    });

    store.prisma = new PrismaClient({ adapter });
  }

  // Return the same PrismaClient instance within this request
  return store.prisma;
}
```

```ts
// app.ts
import { Hono } from "hono";
import { runWithRequestContext } from "./context";

const app = new Hono<{ Bindings: Env }>();

app.use("*", (c, next) => {
  // Wrap each request so PrismaClient is automatically cleaned up
  return runWithRequestContext(c, () => next());
});

// In any handler / service / class, you can now do:
// import { getPrisma } from "./context";
// const prisma = getPrisma();
```

Within a single request, every place that calls `getPrisma()` (including deep inside classes/services) receives the same `PrismaClient` instance, and it’s always disconnected exactly once at the end of the request via `runWithRequestContext`.

Thanks again for the explanation and for planning to update the docs — this is super helpful for those of us running Prisma on Workers in production.

**Comment by OllieJennings** [comment]
I will point out as well, everywhere we create a new Prisma client, we always call disconnect after usage and we have completely removed these errors from our workers.

**Comment by tavoyne** [comment]
This didn't fix the issue in my case, @jacek-prisma. I'm getting a huge number of these errors during spikes, even when calling disconnect before the worker ends. I'm now on Prisma `7.20.0`.

EDIT: This was my mistake. I was storing the db reference on `globalThis`, not realizing that during traffic spikes Cloudflare can reuse the same isolate across multiple requests. This meant that `$disconnect()` would sometimes try to close a connection that was created by a different request, causing Cloudflare to block it and the disconnect never actually happened. The fix was to use `AsyncLocalStorage` to scope the db connection per request, just like in [aiji42's comment](https://github.com/prisma/prisma/issues/28012#issuecomment-3563326540) above.
