### ISSUE TITLE
internal/modules/cjs/loader.js:594 Error: Cannot find module 'generate'

### ISSUE THREAD

**Issue by ducdev** [prisma/prisma#3458]
**Describe the bug**
Can not initialize with prisma via Homebrew
**To Reproduce**
New installed macOS Mojave, install homebrew, install prisma via homebrew, install Docker CE, signed in Docker, run `prisma init abc`, choose all options, throw Error.

**Expected behavior**
It should work as well as prisma installed with npm
**Screenshots**
![image](https://user-images.githubusercontent.com/3524016/48302133-fd8c0800-e52a-11e8-9a62-4073c708fd28.png)

**Versions (please complete the following information):**
- OS: macOS Mojave
- Latest Prisma

**Comment by timsuchanek** [comment]
Thanks for reporting @ducdev ! What's the output of `prisma -v`?

**Comment by pantharshit00** [comment]
This is now fixed in #3653

**Comment by Maxximus007** [comment]
Having the exact same issue with `prisma/1.24.0 (darwin-x64) node-v10.4.1` running brew version on Mojave.

**Comment by THPubs** [comment]
Same issue here. `macOS Mojave, brew, prisma/1.24.0, node-v10.15.0`

**Comment by rouxfeur** [comment]
The issue is still not fixed.

**Comment by huyqpham** [comment]
The issue is still there with: prisma/1.29.1 (windows-x64) node-v10.15.3

**Comment by kenigbolo** [comment]
This issue still exists in prisma 1.30.x when prisma is installed with homebrew. When installed with npm the issue becomes nonexistent

**Comment by rares-lupascu** [comment]
same here

**Comment by jagadeeshreddy2018** [comment]
C:\Users\SYSTEM1>ng
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'symbol-observable'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\SYSTEM1\AppData\Roaming\npm\node_modules\@an
gular\cli\lib\init.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by jagadeeshreddy2018** [comment]
please provide the solution

**Comment by redaikidoka** [comment]
Just tried this with `Prisma CLI version: prisma/1.33.0 (darwin-x64) node-v10.4.1`

## The error
```
Next steps:

  1. Start your Prisma server: docker-compose up -d
  2. Deploy your Prisma service: prisma deploy
  3. Read more about introspection:
     http://bit.ly/prisma-introspection
internal/modules/cjs/loader.js:594
    throw err;
    ^

Error: Cannot find module '/Users/isengard/Dev/str/pw20190516/generate'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1285:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1314:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Comment by brunolemos** [comment]
The solution is to uninstall prisma from `brew` and reinstall using `npm`:

```
brew uninstall prisma
npm i -g prisma
prisma init hello-world
```

**Comment by thatgibbyguy** [comment]
Ran into this issue and ^ worked perfectly for me.
