### ISSUE TITLE
PostgreSQL Existing - PSQLException "no schema has been selected to create in"

### ISSUE THREAD

**Issue by james-ff** [prisma/prisma#4059]
**Describe the bug**
After Successful Existing Database setup and running `docker-compose up -d`, the logs on the container generated show the following error a couple of times:

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: no schema has been selected to create in
  Position: 35
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
        at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
        at slick.jdbc.Invoker.first(Invoker.scala:30)
        at slick.jdbc.Invoker.first$(Invoker.scala:29)
        at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:15)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
        at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
1. Setup Existing Database with Postgres to Step 4 https://www.prisma.io/docs/get-started/01-setting-up-prisma-existing-database-TYPESCRIPT-t003/
2. Run `docker-compose up -d`
3. Check Container Logs
4. See errors

**Expected behavior**
No errors and `prisma deploy` is successful after `docker-compose up -d`.

**Versions (please complete the following information):**
 - PostgreSQL: 10.5
 - `prisma` CLI: prisma/1.26.4 (darwin-x64) node-v11.9.0
 - OS: macOS Mojave

**Comment by hadongz** [comment]
I have the same issue, it's asking me the schema name but when I match the database name and schema name it didn't generate _RealyId in the schema

`org.postgresql.util.PSQLException: ERROR: relation "mydb._RelayId" does not exist
  Position: 13
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$insertToDBIO$1(SharedSlickExtensions.scala:43)
        at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$insertToDBIO$1$adapted(SharedSlickExtensions.scala:43)
        at com.prisma.connector.shared.jdbc.SharedSlickExtensions.$anonfun$jooqToDBIO$1(SharedSlickExtensions.scala:62)
        at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
        at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by pantharshit00** [comment]
@james-ff 

Looks like you are not providing schema property in the docker-compose file, please use this kind of docker-compose file. @divyenduz We should also for this in the cli.

```yaml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.26
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            database: test_admin
            user: harshit
            password: ''
            rawAccess: true
            port: '5432'
            migrations: true
            schema: public
```


@hadongz 
I can also confirm that prisma is current creating the `_Relayid` table in `service$schema` instead of provided schema. cc @do4gr 

Please create the following table manually in the meanwhile.

![image](https://user-images.githubusercontent.com/22195362/53029144-42123280-348e-11e9-80b9-5c072b62ee36.png)

**Comment by james-ff** [comment]
@pantharshit00 Hi, I perhaps should have said originally that I am already providing a schema property in my docker-compose file. I am using a schema different to "public", my schema is "mtg", is this possibly causing the issue?

**Comment by do4gr** [comment]
Hey @james-ff, we just released a fix for similar issues with 1.27.2. Could you please check whether that solves your problem? If not, just let me know and I'll try to identify your issue.

**Comment by james-ff** [comment]
I'm afraid the same error is appearning in the logs from version 1.27.3.

`Exception in thread "main" org.postgresql.util.PSQLException: ERROR: no schema has been selected to create in
  Position: 35`

Any idea if this is this referring to the schema property of the postgres connector set up in the docker-compose file?

**Comment by pantharshit00** [comment]
I can't reproduce this with 1.28 @james-ff, can you please try again?

cc @divyenduz

**Comment by james-ff** [comment]
I have removed the docker container and image, reinstalled prisma globally, changed the prisma version in docker-compose, and unfortunatly still see the issue after running `docker-compose up`.

Is there some way I can get more verbose error logs? I'd be up for looking into this issue more myself if I can be pointed in the right direction.

**Comment by divyenduz** [comment]
@james-ff : I am also unable to reproduce this with 1.28.x. Can you provide a small reproduction repository with steps that I can follow to reproduce this? 

Also, can you share the output of `docker ps` and `prisma version` command? Along with the `docker logs <prisma container>` command? 

Thanks!

**Comment by james-ff** [comment]
Docker Logs:

```
docker logs -f d112d262f90305622d44ac6509f22f15d0b2a39e609b158110608c5c4d2bf405
No log level set, defaulting to INFO.
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: no schema has been selected to create in
  Position: 35
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
        at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
        at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
        at slick.jdbc.Invoker.first(Invoker.scala:30)
        at slick.jdbc.Invoker.first$(Invoker.scala:29)
        at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:15)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
        at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
        at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
        at scala.collection.Iterator.foreach(Iterator.scala:937)
        at scala.collection.Iterator.foreach$(Iterator.scala:937)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
        at scala.collection.IterableLike.foreach(IterableLike.scala:70)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
        at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
        at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Docker ps:
![Screen Shot 2019-03-15 at 12 10 26](https://user-images.githubusercontent.com/1874352/54430554-de40f980-471b-11e9-9e2a-759cc1cb9cfb.png)

Prisma version:
![Screen Shot 2019-03-15 at 12 11 25](https://user-images.githubusercontent.com/1874352/54430537-d2edce00-471b-11e9-8408-0aa45bad2c53.png)

I'm wondering if it is something to do with my database specifically?

Docker Compose:

```
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.28.3
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: host.docker.internal
            port: 5432
            user: mtgcuk
            password: __REDACTED__
            rawAccess: true
            migrations: false
            database: mtgcompareuk
            schema: mtg
```

**Comment by divyenduz** [comment]
@james-ff : Would it be possible for you to share a dump of your Postgres schema (maybe with some data)? Would help us validate if there is an issue with your specific DB.

**Comment by james-ff** [comment]
Schema:

```sql
CREATE SCHEMA myschema;

CREATE TABLE myschema.card (
    id INTEGER DEFAULT PRIMARY KEY,
    uniqueid TEXT NOT NULL UNIQUE,
    updated TIMESTAMP WITH TIME ZONE DEFAULT now(),
    name TEXT NOT NULL,
    url TEXT NOT NULL DEFAULT 'notfound'
);

CREATE TABLE myschema.card_reserved (
    id INTEGER DEFAULT PRIMARY KEY,
    uniqueid TEXT NOT NULL UNIQUE,
    updated TIMESTAMP WITH TIME ZONE DEFAULT now(),
    name TEXT NOT NULL,
    url TEXT NOT NULL DEFAULT 'notfound'
);

CREATE TABLE myschema.card_product (
    id INTEGER DEFAULT PRIMARY KEY,
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    name TEXT NOT NULL,
    price numeric(9,2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    card_id INTEGER NOT NULL REFERENCES myschema.card(id),
    supplier_id INTEGER NOT NULL REFERENCES myschema.supplier(id)
);

CREATE TABLE myschema.card_product_rejected (
    id INTEGER DEFAULT PRIMARY KEY,
    updated TIMESTAMP WITH TIME ZONE DEFAULT now(),
    name TEXT NOT NULL,
    supplier_id INTEGER NOT NULL REFERENCES myschema.supplier(id)
);

CREATE TABLE myschema.card_product_reserved (
    id INTEGER DEFAULT PRIMARY KEY,
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    name TEXT NOT NULL,
    url TEXT NOT NULL UNIQUE,
    card_id INTEGER NOT NULL REFERENCES myschema.card(id),
    supplier_id INTEGER NOT NULL REFERENCES myschema.supplier(id)
);

CREATE TABLE myschema.card_search (
    id INTEGER DEFAULT PRIMARY KEY,
    searches INTEGER,
    updated TIMESTAMP WITH TIME ZONE DEFAULT now(),
    card_id INTEGER REFERENCES myschema.card(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE myschema.supplier (
    id INTEGER DEFAULT PRIMARY KEY,
    name TEXT NOT NULL
);
```

**Comment by james-ff** [comment]
I have changed the user and password config to default postgres credentials, which seems to not give the docker containter error logs. 

I now get an error when running `prisma deploy`:

```
Creating stage default for service default ✔
Deploying service `default` to stage `default` to server `local` !

ERROR: Whoops. Looks like an internal server error. Search your server logs for request ID: local:cjta4b2yi00040834g90rawg0

{
  "data": {
    "deploy": null
  },
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Search your server logs for request ID: local:cjta4b2yi00040834g90rawg0",
      "path": [
        "deploy"
      ],
      "locations": [
        {
          "line": 2,
          "column": 9
        }
      ],
      "requestId": "local:cjta4b2yi00040834g90rawg0"
    }
  ],
  "status": 200
}
```

**Comment by james-ff** [comment]
I believe this to be fixed in the latest version of Prisma, not sure which version this was be it is working as of version 1.29.1

**Comment by do4gr** [comment]
Thanks for letting us know!

**Comment by asktree** [comment]
I'm getting this bug, too. I was only able to fix it by switching back to using the `postgres` database instead of a second database I'd made.
