### ISSUE TITLE
Unable to deploy schema saying "MigrationValue method should only be called on scalar fields"

### ISSUE THREAD

**Issue by sreejithr** [prisma/prisma#4333]
When I deploy the following schema, I'm getting this error:

```
Applying changes 1.6s
 ▸    The Migration failed and has not been performed. This is very likely not a transient issue.
 ▸    java.lang.RuntimeException: MigrationValue method should only be called on scalar fields.
 ▸    at scala.sys.package$.error(package.scala:26)
 ▸    at com.prisma.deploy.connector.MigrationValueGenerator.migrationValueForField(MigrationValueGenerator.scala:18)
 ▸    at com.prisma.deploy.connector.MigrationValueGenerator.migrationValueForField$(MigrationValueGenerator.scala:9)
 ▸    at com.prisma.deploy.connector.mysql.database.MySqlJdbcDeployDatabaseMutationBuilder.migrationValueForField(MysqlJdbcDeployDatabaseMutationBuilder.scala:20)
 ▸    at com.prisma.deploy.connector.mysql.database.MySqlJdbcDeployDatabaseMutationBuilder.createColumn(MysqlJdbcDeployDatabaseMutationBuilder.scala:173)
 ▸    at com.prisma.deploy.connector.jdbc.database.CreateColumnHelper$.withIndexIfNecessary(ColumnMutactionInterpreters.scala:156)
 ▸    at com.prisma.deploy.connector.jdbc.database.CreateColumnInterpreter.execute(ColumnMutactionInterpreters.scala:14)
 ▸    at com.prisma.deploy.connector.jdbc.database.JdbcDeployMutactionExecutor.execute(JdbcDeployMutactionExecutor.scala:19)
 ▸    at com.prisma.deploy.migration.migrator.MigrationApplierImpl.executeClientMutaction(MigrationApplier.scala:119)
 ▸    at com.prisma.deploy.migration.migrator.MigrationApplierImpl.$anonfun$applyStep$2(MigrationApplier.scala:106)
 ▸    at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
 ▸    at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
 ▸    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
 ▸    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
 ▸    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
 ▸    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 ▸    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
 ▸    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
 ▸    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
 ▸    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
 ▸    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 ▸    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 ▸    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 ▸    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
Schema:
```
type Task {
  id: ID! @unique
  title: String!
  sectionId: ID!
  projectId: ID!
  # Serialized DateTime object
  deadline: String
  # In <hour>.<min>
  timeEstimate: Int
  note: String
  complete: Boolean!
  deleted: Boolean!
  archived: Boolean
  completedTime: DateTime
}

type Section {
  id: ID! @unique
  name: String!
}

type Project {
  id: ID! @unique
  name: String!
  sections: [Section]
}
```

**To Reproduce**
1. Create a new service.
2. Replace with above schema.
3. Do a `prisma deploy`.

**Versions (please complete the following information):**
 - Connector: Demo database
 - `prisma` CLI: `1.29.1`
 - OS: `OS X High Sierra`

**Comment by pantharshit00** [comment]
I was able to reproduce this. 

![image](https://user-images.githubusercontent.com/22195362/55875203-1b30cc80-5bb2-11e9-9c74-46fab6aa4e82.png)


To reproduce you might have to deploy the datamodel a couple of times. I also tried reproducing this locally but it was different. The API only had a node method like that.

**Comment by brunoprela** [comment]
Why was this closed? This issue is still coming up in v1.30.0.

**Comment by mavilein** [comment]
fixed in `1.30.1`

**Comment by yokai-mononoke** [comment]
have this problem too

**Comment by gbols** [comment]
I am having the same problem too

**Comment by khalidahmada** [comment]
I still have this issue in prisma/1.34.10 (darwin-x64) node-v10.16.3
