### ISSUE TITLE
Introspect overwrites prisma relation field names

### ISSUE THREAD

**Issue by MichalLytek** [prisma/prisma#4802]
## Bug description

The docs: https://www.prisma.io/docs/concepts/components/introspection#introspection-with-an-existing-schema
claims that they maintain `@map and @@map attributes` and `Custom @relation names`.

However, it's not possible to achieve renaming relation fields for introspected workflow. 
When I try to put `@map` attribute, I get this error:
> `Error parsing attribute "@map": The attribute @map can not be used on relation fields.`

I've also tried to use relation names:
```diff
- CampaignAutomation      CampaignAutomation? @relation(fields: [campaignAutomationId], references: [id])
+ automation              CampaignAutomation? @relation("CampaignAutomation", fields: [campaignAutomationId], references: [id])
```

But the introspect overwrites all that changes, removing the relation name

## How to reproduce

Create two tables with one-many relation and introspect the database. Then try to change the generated relation field name.

## Expected behavior

Being able to change the introspected relation field names. They are generated as the table names in PascalCase, which is a horrible DX when making a prisma query.

## Environment & setup

- OS:  Ubuntu 20.04
- Database:  MySQL
- Node.js version:  `v15.3.0`
- Prisma version:

```
@prisma/cli          : 2.13.1
@prisma/client       : 2.13.1
Current platform     : debian-openssl-1.1.x
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/query-engine-debian-openssl-1.1.x)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/migration-engine-debian-openssl-1.1.x)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/introspection-engine-debian-openssl-1.1.x)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at node_modules/@prisma/engines/prisma-fmt-debian-openssl-1.1.x)
Studio               : 0.329.0
Done in 3.81s.
```

**Comment by do4gr** [comment]
Hey, thanks for reporting this. 

You cannot put an `@map` on relation fields like the error message says, that is correct. `@map` is used to express a difference between an API level name and a db level name, relation fields are API level only and have no representation in the db. Therefore the directive is not necessary or available on them. 

For relation fields introspection should automatically keep the names when you re-introspect. We had a regression in 2.13 where this stopped working, but we thought this was fixed with 2.13.  I'll investigate.

**Comment by MichalLytek** [comment]
@do4gr Thanks for the info.
I've double checked and I'm using `v2.13.1` and the issue still exists.

**Comment by do4gr** [comment]
I tried reproducing this on MySQL and Postgres with the exact same version you ran but could not do so. This is what worked for me: 

Create a 1:M relation with two tables: 
```sql
CREATE TABLE "User" (
    id SERIAL PRIMARY KEY
);
CREATE TABLE "Profile" (
    id SERIAL PRIMARY KEY,
    "userId" INTEGER NOT NULL,
    FOREIGN KEY ("userId") REFERENCES "User"(id)
);
```

Introspect it. 

```prisma
model Profile {
  id     Int  @id @default(autoincrement())
  userId Int
  User   User @relation(fields: [userId], references: [id])

  @@index([userId], name: "userId")
}

model User {
  id      Int       @id @default(autoincrement())
  Profile Profile[]
}
```
Lowercase the User and Profile relation field names. 
Run Introspect again. 

For me this keeps the lowercased custom names. 

I also tried adding relation names like this: 
```prisma
model Profile {
  id     Int  @id @default(autoincrement())
  userId Int
  user   User @relation("MyName", fields: [userId], references: [id])

  @@index([userId], name: "userId")
}

model User {
  id      Int       @id @default(autoincrement())
  profile Profile[] @relation("MyName")
}
```

This was also kept after reintrospection. 

I ran into a bug though where introspect crashed if you dod not provide the `@relation("MyName")` on the User side.

**Comment by do4gr** [comment]
Can you provide the full sql you used to create the initial database? Maybe there is some difference in there.

**Comment by MichalLytek** [comment]
@Jolg42 looks like giving relation name on both sides (both models) fixes the issue in `v2.13.1`. 
Thanks for the help! 😉

**Comment by do4gr** [comment]
Giving the relation name should not be necessary to prevent the overwriting. When I tried reproducing it the names were kept without overwriting, so I'd still be interested in your SQL.

**Comment by MichalLytek** [comment]
There's nothing fancy in that SQL I think:
```sql
CREATE TABLE `Campaign` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `campaignAutomationId` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `campaignAutomationId_UNIQUE` (`campaignAutomationId`),
  KEY `fk_Campaign_CampaignAutomation1_idx` (`campaignAutomationId`),
  CONSTRAINT `fk_Campaign_CampaignAutomation1` FOREIGN KEY (`campaignAutomationId`) REFERENCES `CampaignAutomation` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=368967 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `CampaignAutomation` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=488 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

If you can't reproduce and it works for me now, I think we can close the issue until someone else have this problem 😉
