### ISSUE TITLE
[aws rds mysql] Error: P1001 Can't reach database server using ssl connect

### ISSUE THREAD

**Issue by gevuong** [prisma/prisma#5132]
## Bug description

Running `prisma introspect` returns the following error:

```
Error: P1000

Authentication failed against database server at `xxxxx.rds.amazonaws.com`, the provided database credentials for `USER` are not valid.

Please make sure to provide valid database credentials for the database server at `xxxxx.rds.amazonaws.com`.
```

#### Debugging Steps Taken

* [x] successfully ssl connected (and can query) using DBeaver (a SQL client tool) with the same credentials, host, port, database name, and CA cert.

* [x]  successfully (non-ssl) connected to and ran `prisma introspect` against a Docker image of a mysql-employees sample database (found [here](https://hub.docker.com/r/genschsa/mysql-employees)).

I originally posted similar details in a Q&A Discussion post [here](https://github.com/prisma/prisma/discussions/5038).

#### Attempt 1

1. move CA cert to `./prisma` dir
2. add `DATABASE_URL="mysql://USER:PASSWORD@xxxxx.rds.amazonaws.com:3306/DATABASE&sslcert=server-ca-cert.pem"` to `.env` file.
3. prisma introspect

#### Attempt 2

1. create a pkcs12 file following instructions [here](https://serverfault.com/questions/831394/how-can-i-create-a-pkcs12-file-using-openssl-self-signed-certs)
2. move pkcs12 file to `./prisma` dir
3. add `DATABASE_URL="mysql://USER:PASSWORD@xxxxx.rds.amazonaws.com:3306/DATABASE&sslidentity=keyStore.p12&sslpassword=SSLPASS&sslcert=server-ca-cert.pem"` to `.env` file.
4. prisma introspect

#### Attempt 3

1. create a pkcs12 file using the exact steps listed in Issue #2676
2. add `DATABASE_URL="mysql://USER:PASS@xxx.rds.amazonaws.com:3306/DATABASE&sslidentity=client-identity.p12&sslpassword=SSLPASS&sslcert=server-ca-cert.pem"` to `.env` file.
3. prisma introspect

#### Attempt 4

1. add `DATABASE_URL="mysql://USER:PASS@xxx.rds.amazonaws.com:3306/DATABASE` to `.env` file.
2. prisma introspect

They all result in the same `Error: P1000 Authentication failed` error. 

## Expected behavior

A successful `prisma introspect` run.

```
❯ prisma introspect
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

Introspecting based on datasource defined in prisma/schema.prisma …

✔ Introspected x models and wrote them into prisma/schema.prisma in xxxms
      
Run prisma generate to generate Prisma Client.
```

## Prisma information

`/prisma/schema.prisma`:

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}
```

`.env`: 
```
# Environment variables declared in this file are automatically made available to Prisma.
# See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables

# Prisma supports the native connection string format for PostgreSQL, MySQL and SQLite.
# See the documentation for all the connection string options: https://pris.ly/d/connection-strings

DATABASE_URL="mysql://USER:PASSWORD@xxxxx.rds.amazonaws.com:3306/DATABASE&sslcert=server-ca-cert.pem
```

## Environment & setup

- OS: `Mac OS Catalina 10.15.6` 
- Database: `MySQL (Amazon RDS)` 
- Node.js version: `14.15.4` 
- Nestjs version: `7.5.4`
- Prisma version:
```
@prisma/cli          : 2.13.1
@prisma/client       : 2.14.0
Current platform     : darwin
Query Engine         : query-engine fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../../../../../.nvm/versions/node/v14.15.4/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../../../../../.nvm/versions/node/v14.15.4/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../../../../../.nvm/versions/node/v14.15.4/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt fcbc4bb2d306c86c28014f596b1e8c7980af8bd4 (at ../../../../../.nvm/versions/node/v14.15.4/lib/node_modules/@prisma/cli/node_modules/@prisma/engines/prisma-fmt-darwin)
Studio               : 0.329.0
```

**Comment by gevuong** [comment]
Update:

As a continuation of my debugging steps, I implemented steps similar to Issue #3146 by creating my own AWS RDS MySQL DB instance (MySQL Community edition - Free Tier), downloaded `rds-ca-2019-root.pem` certs from [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html), and attempted to run `prisma introspect` with `DATABASE_URL="mysql://admin:xxx@xxx.rds.amazonaws.com:3306/sslmode=require&sslcert=rds-ca-2019-root.pem"`. The cert was located in `./prisma` directory.

Unfortunately, I am still getting the same error when executing `prisma introspect`.

```
Error: P1000

Authentication failed against database server at `xxx.rds.amazonaws.com`, the provided database credentials for `admin` are not valid.

Please make sure to provide valid database credentials for the database server at `xxx.rds.amazonaws.com`
```

#### Debugging Steps Taken

* [x]  successfully SSL and non-SSL connected to my AWS DB instance using DBeaver GUI, which uses a JDBC driver (mysql-connector-java-5.1.44.jar). 

* [x]  successful `prisma introspect` to my AWS RDS instance by disabling SSL. 

```
❯ prisma introspect
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

Introspecting based on datasource defined in prisma/schema.prisma …

✔ Introspected 35 models and wrote them into prisma/schema.prisma in 729ms
```

## How to reproduce

1. `mysql -h xxx.rds.amazonaws.com -P 3306 -u admin -p`. More info [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ConnectToInstance.html).
2. `ALTER USER 'admin'@'%' REQUIRE SSL;` More info [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.SSLSupport). 
3. `DATABASE_URL="mysql://admin:xxx@xxx.rds.amazonaws.com:3306/sslmode=require&sslcert=rds-ca-2019-root.pem"` in `.env` file. 
4. `prisma introspect`

Any help or suggestion would be appreciated.



Any help or suggestions would be appreciated.

**Comment by gevuong** [comment]
Apologies in advance, I realized that my database url was incorrect. 
I should have been using `?` after DATABASE, as stated in the docs: `mysql://USER:PASSWORD@HOST:PORT/DATABASE?KEY1=VALUE&KEY2=VALUE&KEY3=VALUE`.
I mistakenly used `&`.

Upon changing my database url to
`DATABASE_URL="mysql://admin:xxx@xxx.rds.amazonaws.com:3306/prisma?sslmode=require&sslcert=rds-ca-2019-root.pem", I am getting a different error SSL connecting to my AWS DB instance with a newly created database name, `prisma`. 

```
Error: P1001

Can't reach database server at `xxx.rds.amazonaws.com`:`3306`

Please make sure your database server is running at `xxx.rds.amazonaws.com`:`3306`.
```

#### Debugging Steps Taken

* [x] Disabling SSL and executing `prisma introspect` using `DATABASE_URL="mysql://admin:xxx@xxx.rds.amazonaws.com:3306/prisma"` is successful.

* [x] Tested the connection to the DB instance with the following command found [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Troubleshooting.html#CHAP_Troubleshooting.Security).
```
❯ nc -zv xxx.rds.amazonaws.com 3306
Connection to xxx.rds.amazonaws.com port 3306 [tcp/mysql] succeeded!
```

**Comment by dhanish2k** [comment]
I have the same issue as well. 

I upgraded my cli version to 2.15.0 and I get 

`Error: P1001`

`Can't reach database server at `xxx.rds.amazonaws.com`:`5432`

`Please make sure your database server is running at `xxx.rds.amazonaws.com`:`5432`.`


But if I go back to 2.8.0, I'm able to connect so something has definitely changed.

**Comment by gevuong** [comment]
hey @dhanish2k, 
I reverted to prisma/cli v2.8.0 and tried this url: `DATABASE_URL="mysql://admin:xxx@xxx.rds.amazonaws.com:3306/prisma?sslcert=rds-ca-2019-root.pem"`, with `rds-ca-2019-root.pem` cert in `./prisma` directory.

It now throws the following error:

```
Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: TLS error: `One or more parameters passed to a function were not valid.'
```

I then tried reverting prisma/client to v2.8.0 as well, but it threw the same error.

Did your database url look similar to what I used? 
I'm not sure what parameter the error is referring to, maybe `sslcert`?..


## Environment And Setup
```
❯ prisma -v        
Environment variables loaded from prisma/.env
@prisma/cli          : 2.8.0
Current platform     : darwin
Query Engine         : query-engine e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at ../../../../../.nvm/versions/node/v14.15.4/lib/node_modules/@prisma/cli/query-engine-darwin)
Migration Engine     : migration-engine-cli e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at ../../../../../.nvm/versions/node/v14.15.4/lib/node_modules/@prisma/cli/migration-engine-darwin)
Introspection Engine : introspection-core e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at ../../../../../.nvm/versions/node/v14.15.4/lib/node_modules/@prisma/cli/introspection-engine-darwin)
Format Binary        : prisma-fmt e6c9b4b2b7fa162d0d459d1863321f547498fcfe (at ../../../../../.nvm/versions/node/v14.15.4/lib/node_modules/@prisma/cli/prisma-fmt-darwin)
Studio               : 0.294.0
```

**Comment by dhanish2k** [comment]
@gevuong "postgresql://admin:xxx@xxx.rds.amazonaws.com:3306/****" that's what I have. I put the cert in the prisma folder but I don't refer it in the connection string.

**Comment by gevuong** [comment]
hm ok. Thanks for the quick response.

The following is what I get with v2.8.0 with `prisma/cli` and `prisma/client`.

Before I run `prisma introspect`, I required SSL for the `admin` user by executing the following `ALTER USER 'admin'@'%' REQUIRE SSL;` in mysql shell, and tried `DATABASE_URL="mysql://admin:PASS@xxx.rds.amazonaws.com:3306/prisma"`, without the `sslcert=rds-ca-2019-root.pem` parameter in the connection string but got the following:

```
Error: P1000

Authentication failed against database server at `xxx.rds.amazonaws.com`, the provided database credentials for `admin` are not valid.

Please make sure to provide valid database credentials for the database server at `xxx.rds.amazonaws.com`.
```

Which to me, makes sense because there is no cert specified in connection string. However, if I add `sslcert=rds-ca-2019-root.pem` to the connection string, and even `sslmode=require`, I get the following:

```
Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: TLS error: `One or more parameters passed to a function were not valid.'
```

Question: @dhanish2k, does your RDS for PostgreSQL DB instance require or enforce only SSL connections? Apparently, RDS for Postgres allows you to enforce ssl by enabling the `force_ssl` parameter in the Parameter Groups page on the RDS console. I think that parameter is only unique to Postgres RDS. More info [here](https://aws.amazon.com/about-aws/whats-new/2016/03/enhanced-monitoring-and-option-to-enforce-ssl-connections-is-now-available-for-amazon-rds-for-postgresql/).

**Comment by dhanish2k** [comment]
@gevuong That's interesting. I have rds.force_ssl parameter set to 1.  For some reason it doesn't complain when I use 2.8.0. I tried with the nodejs pg client. and I get auth failure unless I do 
`    connectionString, ssl: {
        ca: [fs.readFileSync(path.resolve(__dirname, '../path/to/aws.pem')), 'ascii']
    }`

**Comment by gevuong** [comment]
ic..I appreciate your feedback.

Yes, this is interesting, so you did not need a PKCS12 client file or password to SSL connect, even though the [prisma doc](https://www.prisma.io/docs/concepts/database-connectors/postgresql) states that it's needed to create a SSL connection.

Earlier, I reached out on the Prisma slack channel and was suggested to create a PKCS12 file and password and add those parameters to the connection string. I did just that, following the steps provided [here](https://github.com/prisma/prisma/issues/2676), and used this connection string, `DATABASE_URL="mysql://admin:PASS@xxx.rds.amazonaws.com:3306/prisma?sslaccept=strict&sslidentity=client-identity.p12&sslpassword=SSLPASS&sslcert=rds-ca-2019-root.pem"`, where `client-identity.p12` and the server cert are in `./prisma` directory.

It returned the same error:

```
Error: Error in connector: Error querying the database: Error querying the database: Error querying the database: TLS error: `One or more parameters passed to a function were not valid.'
```

The docs aren't very clear about what path to provide to the PKCS12 file, so as a sanity check, I tried moving the `client-identity.p12` file to the root directory of where `prisma introspect` would be called. And tried adding the fully qualified path to `sslidentity` param (ie. `sslidentity=/Users/xxx/Projects/nestjs/prisma/client-identity.p12`).

But they all return the same error 😞..

**Comment by Jolg42** [comment]
Hi @gevuong

I'm reading this from https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html
>To get a root certificate that works for all AWS Regions, excluding opt-in AWS Regions, download it from https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem

>This root certificate is a trusted root entity and should work in most cases but might fail if your application doesn't accept certificate chains. If your application doesn't accept certificate chains, download the AWS Region–specific certificate from the list of intermediate certificates found later in this section.

Did you try to connect with an `Intermediate certificates` maybe?

**Comment by iamgoddog** [comment]
Hi, I'm having the same problem here when connecting to a Google cloud SQL instance

My connection string: 
`DATABASE_URL=mysql://USER:PASS@IP_NUMBER:3306/DB_NAME?sslidentity=client-identity.p12&sslpassword=******&sslcert=server-ca.pem&sslaccept=strict`

Schema:
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
``` 

Returns: 
``` 
Error: P1001

Can't reach database server at `xxx.xxx.xxx.xxx`:`3306`

Please make sure your database server is running at `xxx.xxx.xxx.xxx`:`3306`.
``` 

I am able to connect to the db from my machine using same certificates using Sequel Pro. 

I am able to connect if I disable all SSL and allow unsecured connections.

Any help or suggestions would be appreciated.

**Comment by gevuong** [comment]
I hopped back to prisma cli and client v2.15.0.

@iamgoddog I saw your post in [Issue#1228](https://github.com/prisma/prisma/issues/1228) to connect to GCP SQL, and decided to try adding `sslaccept=accept_invalid_cert` to connection string: `DATABASE_URL="mysql://admin:PASS@xxx.rds.amazonaws.com:3306/prisma?sslaccept=accept_invalid_cert&sslidentity=client-identity.p12&sslpassword=SSLPASS&sslcert=rds-ca-2019-root.pem"`

@Jolg42 I tried using intermediate certs, `rds-ca-2019-us-east-1.pem`, `rds-ca-2019-us-east-2.pem`, and `rds-combined-ca-bundle.pem`. Placed them in prisma directory along with p12 file.

It returns the same error:

```
Error: P1001

Can't reach database server at `mysql-1-prisma.cowjz12rle1z.us-east-1.rds.amazonaws.com`:`3306`

Please make sure your database server is running at `mysql-1-prisma.cowjz12rle1z.us-east-1.rds.amazonaws.com`:`3306`.
```

## How to reproduce
Steps to reproduce the behavior:
1. Use prisma cli and client v2.15.0.
2. Create an AWS RDS MySQL (Community, Free Tier) instance
3. Download cert, `root-ca-2019-root.pem` [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html)
4. Create a PKCS12 file following instructions in [Issue#2676](https://github.com/prisma/prisma/issues/2676).
5. Store cert and p12 file in prisma directory.
6. Login to your RDS instance: `mysql -h xxx.rds.amazonaws.com -P 3306 -u admin -p`
7. After login, require SSL for `admin` by executing the following `ALTER USER 'admin'@'%' REQUIRE SSL;`.
8. Use `DATABASE_URL="mysql://admin:PASS@xxx.rds.amazonaws.com:3306/prisma?sslaccept=accept_invalid_cert&sslidentity=client-identity.p12&sslpassword=SSLPASS&sslcert=rds-ca-2019-root.pem"`.
9. Run `prisma introspect`.

**Comment by pantharshit00** [comment]
Hello, 

Thanks for reporting this. I tried tried and I think it is a usage issue. I was able to connect to a AWS RDS instance via SSL.

Here is how I did it. 

1. Launch and new RDS instance. 
2. Expose your instance to your preferred IP range( I exposed it to everywhere).
3. Disable non ssl authentication for you user using SQL
4. Download the AWS root ca from https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html and place it inside `prisma` folder.
5. Use the following URL format: `mysql://<user>:<pass>@<db>.<id>.<region>.rds.amazonaws.com:3306/testdb?ssl_mode=require&sslcert=rootca.pem`
6. Run the commands.

![image](https://user-images.githubusercontent.com/22195362/106280242-ab4a7500-6263-11eb-89ba-84ab7ab4cfc4.png)


You do not need to make a client cert as AWS doesn't support x509 client certificate authentication. You need to use their certificate which they provide so need for the openssl step. 


Let me know if this helps.

**Comment by pantharshit00** [comment]
Other people in the thread, please open separate issues describing your problem as mixing providers in a single issue makes it hard for us to triage the issue.

**Comment by gevuong** [comment]
Hi @pantharshit00, thank you for confirming that a client cert is not necessary for AWS. 

First, to confirm that I can indeed introspect RDS MySQL instance, I disabled `REQUIRE SSL` for user and ran the following:

<img width="1338" alt="Screen Shot 2021-01-29 at 11 32 36 AM" src="https://user-images.githubusercontent.com/27314227/106309042-322d2c80-6227-11eb-961f-96f51dce491c.png">

That worked fine. 
Next, I followed your steps, set Inbound Rules to expose all traffic, `REQUIRE SSL` for user, store root cert in `/prisma`, appended `?sslmode=require&sslcert=rds-ca-2019-root.pem` to connection string, and ran the following:

<img width="1339" alt="Screen Shot 2021-01-29 at 11 31 56 AM" src="https://user-images.githubusercontent.com/27314227/106309171-5a1c9000-6227-11eb-9117-f0f779dc24bb.png">

Unfortunately, I am still getting the same error.

**Comment by gevuong** [comment]
@pantharshit00 Ok I just noticed that you used `ssl_mode` instead of `sslmode` as shown in prisma docs.

Anyhow, I tried, `ssl_mode` instead but am still getting same error.

<img width="1344" alt="Screen Shot 2021-01-29 at 12 01 19 PM" src="https://user-images.githubusercontent.com/27314227/106310887-e16b0300-6229-11eb-9830-418b3b6246e5.png">

**Comment by pantharshit00** [comment]
@gevuong Can you try this with 2.16 release once?

**Comment by gevuong** [comment]
Hi @pantharshit00,
I just tried w/ 2.16.0 and it's throwing the same P1001 Error when attempting to ssl connect.

**Comment by gevuong** [comment]
Hi @pantharshit00,

Per #2676, i tried `sslaccept=accept_invalid_certs` instead of `sslmode=require` and it worked! 

Although the [prisma docs](https://www.prisma.io/docs/concepts/database-connectors/mysql) state the `sslaccept` is not required and that the default is `accept_invalid_certs`, I had to explicitly add the argument to get it to work. Otherwise I will get `Can't reach database server at ...`.

@dhanish2k maybe this will address the error you see in postgres? 

Anyhow, thanks for your help and for everyone's contribution to this thread!

**Comment by pimeys** [comment]
@gevuong The default was wrong in the docs and has been changed in the version 2.17.0. What happened here is that most of the cloud database providers will not give you a valid and signed certificate due to you not having a public hostname for the domain. Now, originally we took an approach to be explicitly secure, and not allow certificates that are not valid. Because, well, it's kind of not that secure to use those certs, you're never sure are you actually talking to the right database!

But then again, the only cloud database that actually has valid certificates is Microsoft with their Azure SQL offering, everybody else just uses self-signed certs. Therefore our PostgreSQL and MySQL connectors both now by default accept self-signed certificates from version 2.17.0 forwards. If you're using an older version, you might want to set `sslaccept=accept_invalid_certs` in your connection string.

**Comment by pantharshit00** [comment]
I guess this is resolved now. Closing!

**Comment by vincenujib** [comment]
> Hi, I'm having the same problem here when connecting to a Google cloud SQL instance
> 
> My connection string: `DATABASE_URL=mysql://USER:PASS@IP_NUMBER:3306/DB_NAME?sslidentity=client-identity.p12&sslpassword=******&sslcert=server-ca.pem&sslaccept=strict`
> 
> The cert and p12 are in the prisma directory.
> 
> Schema:
> 
> ```
> generator client {
>   provider = "prisma-client-js"
> }
> 
> datasource db {
>   provider = "mysql"
>   url      = env("DATABASE_URL")
> }
> ```
> 
> Returns:
> 
> ```
> Error: P1001
> 
> Can't reach database server at `xxx.xxx.xxx.xxx`:`3306`
> 
> Please make sure your database server is running at `xxx.xxx.xxx.xxx`:`3306`.
> ```
> 
> I am able to connect to the db from my machine using same certificates using Sequel Pro.
> 
> I am able to connect if I disable all SSL and allow unsecured connections.
> 
> Any help or suggestions would be appreciated.

Any luck on solving your issue?

**Comment by benmkramer** [comment]
I just went through the same issue. I just found that using `ssl_mode` and `ssl_cert` rather than the same parameters without underscores is working for me (to connect to the RDS via prisma from my local machine. Going to confirm in a deploy but I suspect it will work as well.

Example:
```
DATABASE_URL = "postgresql://xxx:xxx@name.cluster.region.rds.amazonaws.com:5432/postgres?ssl_mode=require&ssl_cert=region-bundle.pem"
```

**Comment by vincenujib** [comment]
> I just went through the same issue. I just found that using `ssl_mode` and `ssl_cert` rather than the same parameters without underscores is working for me (to connect to the RDS via prisma from my local machine. Going to confirm in a deploy but I suspect it will work as well.
> 
> Example:
> 
> ```
> DATABASE_URL = "postgresql://xxx:xxx@name.cluster.region.rds.amazonaws.com:5432/postgres?ssl_mode=require&ssl_cert=region-bundle.pem"
> ```

Thanks @benmkramer ! But still no luck. Still getting `Error: P1001: Can't reach database server at ...`

**Comment by vincenujib** [comment]
> Hi @vincenujib
> 
> Could you open a [new issue](https://github.com/prisma/prisma/issues/new/choose)?
> 
> Something that you could try is connecting with another tool and see if only Prisma errors or if it's a general problem. For example, you could try with `psql`
> 
> ```
> psql -Atx postgresql://xxx:xxx@name.cluster.region.rds.amazonaws.com:5432/postgres?ssl_mode=require&ssl_cert=region-bundle.pem
> ```
> 
> Or any other tool, like DBeaver or TablePlus.

I can connect through MySQL Workbench. Will open new issue for this.

**Comment by albertdugba** [comment]
@vincenujib  were you able to fix this. I'm have also been facing this issue for days now

**Comment by athammer** [comment]
@albertdugba Were you using PlanetScale + Prisma? There might be something else unrelated to this going on. https://stackoverflow.com/a/73919700/3923233

**Comment by muhammad-Osman** [comment]
i am facing the same issue

**Comment by albertdugba** [comment]
> i am facing the same issue

In my case, I was using a vpn which was the very reason I had the error. If you're using a vpn, then you will have to turn it off

**Comment by muhammad-Osman** [comment]
> 

Well i did resolved the issue. In my case, my application was hosted on AWS server and server needs to be upgrade. :)

**Comment by vincenujib** [comment]
My problem here is just my ssl files are not pointing to the correct directory.
