### ISSUE TITLE
Postgres Connection Pinning with RDS Proxy

### ISSUE THREAD

**Issue by f0rr0** [prisma/prisma#5866]
I am using AWS RDS Proxy with Postgres. While investigating the logs for the proxy I saw many warnings with the same message:

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy.html#rds-proxy-pinning
```
The client session was pinned to the database connection [dbConnection=3377128289] for the remainder of the session. The proxy can't reuse this connection until the session ends. Reason: SQL changed session settings that the proxy doesn't track. Consider moving session configuration to the proxy's initialization query. Digest: "set search_path = $1; set names $2;".
```

It looks like Prisma sets these whenever it creates a new connection which causes the Proxy to pin all connections until released rendering the proxy useless. As suggested in the log message above, I would like to set the `search_path` and `NAMES` while initialising the Proxy and not each time a new connection is created. 

Is there any configuration parameter or any other way through which I can tell Prisma not to set these per connection?

**Comment by Jolg42** [comment]
Seems that this could be merged with https://github.com/prisma/prisma/issues/5864

**Comment by pantharshit00** [comment]
cc @pimeys

**Comment by pimeys** [comment]
Yep, and found this from our connecting code, with a comment:

```
// SET NAMES sets the client text encoding. It needs to be explicitly set for automatic
// conversion to and from UTF-8 to happen server-side.
//
// Relevant docs: https://www.postgresql.org/docs/current/multibyte.html
let session_variables = format!(
    r##"
    SET search_path = "{schema}";
    SET NAMES 'UTF8';
    "##,
    schema = schema
);
```
I need to ping @tomhoule for that.

Another thing that raised my attention in the RDS docs:

> Any statement with a text size greater than 16 KB causes the proxy to pin the session.

> Prepared statements cause the proxy to pin the session. This rule applies whether the prepared statement uses SQL text or the binary protocol.

I do believe we might trigger statements over 16 KB for larger queries, quite easily actually. And we most def use prepared statements everywhere to prevent SQL injections, to not escape the parameters by ourselves (this escaping is not very well documented, Postgres docs just tell you to use statements) and to cache the statements and allow us faster execution of similar queries.

**Comment by nihemak** [comment]
Could you please tell me the status of this issue. I have encounter the same issue. I'd like to use prisma with AWS RDS Proxy and Postgres. Thanks for awesome ORM!

**Comment by Jolg42** [comment]
@nihemak current status is documented here:

https://www.prisma.io/docs/guides/deployment/deployment#aws-rds-proxy

> AWS RDS Proxy
> 
> Prisma is compatible with AWS RDS Proxy. However, there is no benefit in using it for connection pooling with Prisma due to the way RDS Proxy pins connections:
> 
>     "Your connections to the proxy can enter a state known as pinning. When a connection is pinned, each later transaction uses the same underlying database connection until the session ends. Other client connections also can't reuse that database connection until the session ends. The session ends when the client connection is dropped." ~ AWS RDS Proxy Docs
> 
> Prepared statements (of any size) or query statements greater than 16 KB cause RDS Proxy to pin the session. Because Prisma uses prepared statements for all queries, you won't see any benefit when using RDS Proxy with Prisma.

**Comment by omar-dulaimi** [comment]
We hope that this issue gets fixed as soon as possible. Because if it isn't resolved/delayed then our whole migration would have been a waste of time since we either have to stop using lambda altogether and switch to a long running server like EC2 or ELB, or the other option is to switch from mysql to postgresql for pgBouncer. Both options will delay us once again a couple of weeks.

**Comment by dpetrick** [comment]
After assessing what would be necessary I'm sorry to say that the engineering effort to comply with RDS proxy's policies to not pin connections is far too much to do this in the near future. We may revise the topic in the future, but unfortunately we can't offer a solution right now without spending weeks of dedicated engineering time.

The limitation is documented here: https://www.prisma.io/docs/guides/deployment/deployment-guides/caveats-when-deploying-to-aws-platforms#aws-rds-proxy

We'll keep this issue around as a feature request to track interest in the topic.

**Comment by omar-dulaimi** [comment]
@dpetrick Well, we would have preferred to know about this limitation a couple of months ago before investing in time and resources in something that won't work until months or years from now. Now we're just stuck, and i'm sure many others are and will once they test live.

### I suggest you add a big red notice on all lambda pages in your docs that say: You can't run Prisma 2 on lambda without a connection pooler. If you use PostgreSQL, pgBouncer have you covered. If you're using MySQL, YOU'RE DOOMED.

**Comment by pimeys** [comment]
So, let me open up some of the problems with serverless functions and stateful database connections, so you understand where we stand right now.

## What is a stateful connection

In many relational databases, opening up a connection is relatively expensive. In PostgreSQL, a connection cost in RAM is about 14 megabytes, meaning opening up thousand connections uses gigabytes and gigabytes of memory. Creating a new connection with all the handshakes and TLS takes time, so we want to reuse them.

When we have a serverless environment, your functions want their own database connections, but are short-lived and paused a lot, meaning we keep connections up doing nothing; connections that eat up RAM from your database server.

Before the serverless trend started, there were certain tools provided for sharing these connections so that you can reserve a static amount of them to a pool and from the other side open much cheaper connections to the pool. When people started wanting to use databases with the serverless platforms, these were the tools of choice.

## Pgbouncer

The classic PostgreSQL pool has three modes of operation:

- Session mode offers a way of divisioning your companie's connections per account. One pool connection is always pinned to one application connection.
- Statement mode offers one connection per statement, no transactions or prepared statements are allowed.
- Transaction mode is the same as statement mode, but gives one connection per transaction.

In Prisma, we can support the session and transaction modes. With serverless, the transaction mode might interest you, but also understand the tradeoffs of this approach.

Prepared statements are stored in a database connection, meaning if we share the connections between different functions, we'll leak the statements and cause undefined behavior eventually that is very hard to debug.

The by-the-book solution here is to not prepare, but use the text protocol instead:

```sql
INSERT INTO a (id, title) VALUES ($1, $2)
```

Turns into:

```sql
INSERT INTO a (id, title) VALUES (123, 'asdf')
```

The classic prepared statement approach is a very effective way of compiling the statement to the connection speeding up all further queries, but even more importantly it allows us very effectively prevent SQL injection attacks, turning the innocent query to a table-dropping monster if a user sends a param `'); DROP TABLE a --"`:

```sql
INSERT INTO a (id, title) VALUES (123, ''); DROP TABLE a -- ');'
```

This is only a simple example, but there are many more. Understanding them and following them up when hackers find new ways of breaking the database is something we decided is a bit too much for us to do, especially if and when we risk user data with our decision.

Now, when using statements in Pgbouncer's transaction mode, the pool will give eventually interesting errors. Let's imagine we have a pool of one connection and two clients are connected to it:

The first one queries:

```sql
SELECT id FROM a WHERE title = $1
```

And the second user does:

```sql
UPDATE a SET title = $1 WHERE id = $2
```

How a PostgreSQL client does this is it first prepares:

```sql
PREPARE s1 (text) AS SELECT id FROM a WHERE title = $1
```

The identifier `s1` is chosen by the client and is incremented by one for subsequent queries. The user here then runs:

```sql
EXECUTE s1('meow');
```

And gets their result correctly.

Now, the second user comes from a different client, has a different connection to the bouncer and doesn't know about the other client. It runs:

```sql
PREPARE s1 (text, int) AS UPDATE a SET title = $1 WHERE id = $2
```

This will crash, because the connection in Pgbouncer saves the previous statement `s1` for other uses, but our second client doesn't know about this and wants to save a new statement with the same name. And we're in trouble.

What we could do is force a randomized statement name per connection. This would not crash, but would also pollute the connection with lots of statements that are hard to clean, leading to database server memory leaks.

We do a quite special trick to get around of this. What we must do is:

- Clean the statements before doing anything else.
- Run everything in a transaction.

```sql
BEGIN; -- first roundtrip
DEALLOCATE ALL; -- #2
PREPARE s1 (text) AS SELECT id FROM a WHERE title = $1 -- # 3
EXECUTE s1('meow'); -- #4
COMMIT; -- # 5
```

Five roundtrips. But at least we don't crash anymore! This is what you get when you use the `pgbouncer=true` in the connection string.

## RDS Proxy

Amazon RDS is a bit different here compared to Pgbouncer. What they do when you prepare a statement is that they pin the connection from the pool to the connection from the user. This makes it easier to do stuff like statements without crashing your software, but much harder to hack around the limitations.

Here we immediately lose our advantage of a transaction mode when we:

- `PREPARE`
- Do any connection-level settings.
- Run large queries (e.g. an IN statement that has many ids)

And we don't have any ways of getting around of this without actually reducing our security by getting rid of prepared statements in our code.

## Stateless connections

Now we get to the real solution, how serverless database connections should work. If we don't store any state to the connection, they suddenly become very cheap and scale up to the amounts what a normal mid-sized serverless application might need. This of course removes certain things what you can't do anymore, one of them is long-running transactions.

We are currently investigating our possibilities here. Please be patient and follow us later this year for more news.

**Comment by janpio** [comment]
> If you're using MySQL, YOU'RE DOOMED.

You could also look into using one of the connection pooling products for MySQL like https://www.proxysql.com/ Let us know how this goes in https://github.com/prisma/prisma/issues/3258, we do not have experience with that yet.

**Comment by saimonmoore** [comment]
Could this be related? https://github.com/prisma/prisma/issues/10208

**Comment by janpio** [comment]
Not if you are not using AWS RDS Proxy there.

**Comment by saimonmoore** [comment]
No. We're actually using proxysql with a galera mysql cluster but the issue we're seeing seems very similar to what you described about stateful connections. 

In order to workaround this issue, we've basically had to remove routing to various servers in the cluster and now everything is routed to the write master. It was either this or reverting all the prisma code we've been writing for the last month or so (and that would end our migration to prisma).

We're still not sure where the issue is (prisma or proxysql). We are really missing documentation into how requests are made low-level in the prisma engine to be able to debug this.

But since we see that our issue get's worse when there is only a single instance in the prisma connection pool, it smells like the above issue but applied to proxysql + galera cluster.

**Comment by janpio** [comment]
I think the problem described here is actually the **opposite** of what you are experiencing in #10208. There you have 1 transaction that is seemingly executed on different connections (main vs replica). Here we have the problem that after executing some specific queries, the proxy will only allow usage of one database connection for one specific client connection instead of using the same database connection to answer many client connections (which is the intended use case of AWS RDS Proxy). Does that make sense?

**Comment by saimonmoore** [comment]
Ah yes you're right!

**Comment by Jesus-Escalona** [comment]
Hi @pimeys any updates on this?

**Comment by janpio** [comment]
No comment means not updates. We are not working on this right now, as it is not clear how we could solve the problem without completely rewriting how we talk to PostgreSQL databases.

**Comment by eran-medan** [comment]
Regarding https://www.prisma.io/docs/guides/deployment/deployment-guides/caveats-when-deploying-to-aws-platforms#aws-rds-proxy: It seems that the sentence "Prepared statements (of any size)" has been removed from https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy.html#rds-proxy.limitations-my 

Is there a chance that this was resolved by AWS?

**Comment by nimish-kumar** [comment]
Does this issue still persists? Any update?

**Comment by janpio** [comment]
This issue still exists and has no updates, so the problem still exists and there are no updates.

**Comment by raymondKelly** [comment]
> @dpetrick Well, we would have preferred to know about this limitation a couple of months ago before investing in time and resources in something that won't work until months or years from now. Now we're just stuck, and i'm sure many others are and will once they test live.
> 
> ### I suggest you add a big red notice on all lambda pages in your docs that say: You can't run Prisma 2 on lambda without a connection pooler. If you use PostgreSQL, pgBouncer have you covered. If you're using MySQL, YOU'RE DOOMED.

Isn't it essentially an issue with almost all ORMs? as they all use prepared statements and definitely exceed the limits set forth by aws

**Comment by thomaschaaf** [comment]
mikroORM also doesn't use prepared statements. ;)

**Comment by mikerhodes** [comment]
I happened to arrive here trying to dig for details on how pgbouncer and AWS's RDS proxy work, and how they differ.

The discussion around use of prepared statements vs. pgbouncer reminded me of [this piece](https://jpcamara.com/2023/04/12/pgbouncer-is-useful.html#prepared-statements) which talks about the difference between "named" and "unnamed" prepared statements. Named are standard `PREPARE foo ...` statements, but you can still prepare an "unnamed" statement (using a more complex process, the article pulls apart some ruby code to show it) and gain the benefits against SQL injection but avoid the problems with pgbouncer.

> For SQL injection safety, both named and unnamed versions are equivalent: they separate query structure (Parse) from data values (Bind). Adding query bindings when not in a prepared statement simply makes an unnamed statement.

Chances are you already spotted this, but if not, maybe it'll help.

**Comment by eugene-kim** [comment]
This might have been addressed in a recent RDS Proxy release

https://aws.amazon.com/blogs/database/amazon-rds-proxy-multiplexing-support-for-postgresql-extended-query-protocol/

**Comment by mariomnts** [comment]
> This might have been addressed in a recent RDS Proxy release
> 
> https://aws.amazon.com/blogs/database/amazon-rds-proxy-multiplexing-support-for-postgresql-extended-query-protocol/

According to the announcement:

> Multiplexing support for prepared statements is limited to Extended Query Protocol messages. Multiplexing with Extended Query Protocol is enabled automatically in RDS Proxy.

Does somebody know if Prisma supports PostgreSQL Extended Query Protocol?

**Comment by janpio** [comment]
A few notes on that announcement:
- Only applies to PostgreSQL
- Other limitations for PostgreSQL have not changed, queries > 16kb and any `SET` commands (like the `set search_path` from the original issue description) unfortunately still cause pinning.

We are still looking into if for _some_ cases with PostgreSQL at least the pinning situation is now usable.

**Comment by mariomnts** [comment]
> A few notes on that announcement:
> 
> * Only applies to PostgreSQL, not MySQL unfortunately
> * Other limitations for PostgreSQL have not changed, SQL queries >16kb and any `SET` commands (like the `set search_path` from the original issue description) unfortunately still cause pinning.
> 
> We are looking into it anyway if for _some_ cases with PostgreSQL at least the pinning situation is now usable.

Thanks @janpio, please keep us posted 😃

**Comment by sergio-toro** [comment]
> This might have been addressed in a recent RDS Proxy release
> 
> https://aws.amazon.com/blogs/database/amazon-rds-proxy-multiplexing-support-for-postgresql-extended-query-protocol/

It would be great to be able to use RDS Proxy. At our company (https://www.oliva.health/) we will be following this very closely as we are interested, we use Postgres and will be available for testing if you decide to tackle this one 🙌🏽

**Comment by mariomnts** [comment]
Hey there! I was wondering if there has been some news regarding Prisma and AWS RDS. It's a real nightmare trying to make those two work at scale in production.

**Comment by ackinc** [comment]
> Has anyone tried using [pgBouncer mode](https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/pgbouncer#pgbouncer) with RDS proxy?
> 
> The docs say that it disables prepared statements -- which is what causes the pinning in RDS proxy to occur.
> 
> I don't know what other side effects may be introduced though. Curious!

I have, with no observable side-effects; but I'm no database expert and my app was hardly pushing the database to its limits.

**Comment by NeishaS** [comment]
Hello, 
I still have issue of session pinning when using RDS proxy with RDS Aurora Postgres. 
I am using RDS Proxy with Glue Job/Connection (Glue 5).

I tried updating the URL to include parameters `assumeMinServerVersion` and `ApplicationName` but still the sessions are getting pinned with this log message `If this prepared statement runs, the client session will be pinned to the database connection [dbConnection=25xxxx]. Reason: SQL changed session settings that the proxy doesn't track. Consider moving session configuration to the proxy's initialization query. Digest: "set session characteristics as transaction isolation level $1 uncommitted".`

**Comment by stwr667** [comment]
> Any statement with a text size greater than 16 KB causes the proxy to pin the session.

@janpio, can you please clarify [this part of the official docs](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy-pinning.html#rds-proxy-pinning.all)?

If you consider this SQL block:
```sql
BEGIN;
  INSERT INTO my_test_table (name, description) VALUES ('my VARCHAR column. 1', 'my TEXT column. 1');
  INSERT INTO my_test_table (name, description) VALUES ('my VARCHAR column. 2', 'my TEXT column. 2');
  COMMIT;
END;
```

Does it mean the 16KB size limit will apply to:
1. The entire SQL block (i.e. the whole transaction in this case), or
2. An entire statement, e.g. the 1st `INSERT` statement on line 2, or
3. The "text" size, e.g. for a column of type `TEXT`. So e.g. if `'my TEXT column. 1'` was greater than the limit?
4. Something else?

**Comment by stwr667** [comment]
For future travellers, AWS support confirmed today that the answer is **2.** (from above - `An entire statement, e.g. the 1st INSERT statement on line 2`).

See their reply from my support case below:

> Hi Team,
> 
> Thank you for contacting AWS Support Engineering. My name is ****** and I will be assisting you today.
> 
> You reached out to us today as you were looking for some clarification on our RDS Proxy Documentations.
> 
> I understand that Proxy has the following limitation -
> 
> Any statement with a text size greater than 16 KB causes the proxy to pin the session.
> [+] Avoiding pinning an RDS Proxy - https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy-pinning.html
> 
> This limitation applies to a single statement or a single query. It does not apply for the complete transaction.
> 
> The limit is applied to a single statement.
> 
> Adding further, please allow me to share that, the detailed information about the queries can only be seen at the RDS end by enabling statement logging (by setting log_statement=all in the parameter group), so you would be able to view every query running on the RDS.
> 
> Please note that, this setting (log_statement=all) causes logging overhead as additional CPU will be required to log all statements.
> 
> I hope this helps. Please feel free to reach out to me incase of further concerns and I will be happy to assist.
> 
> We value your feedback. Please share your experience by rating this and other correspondences in the AWS Support Center. You can rate a correspondence by selecting the stars in the top right corner of the correspondence.
> 
> Best regards,
> ******.
> Amazon Web Services
