### ISSUE TITLE
Drift detected right after introspection (and after applying first migration)

### ISSUE THREAD

**Issue by PeterDekkers** [prisma/prisma#6505]
## Bug description

Right after introspection, without making any changes to the database, when creating the first migration there is drift detected.

Funnily enough, even after continuing to generate and apply the first migration, subsequent migrations also complain that there is drift and want to reset the database over and over.

## How to reproduce

Use the attached PostgreSQL structure, then:
```shell
yarn prisma introspect
yarn prisma generate
yarn prisma migrate dev --name init
```

This then outputs:
```shell
prisma migrate dev --name init
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "test", schema "public" at "localhost:15432"

✔ Drift detected: Your database schema is not in sync with your migration history.

We need to reset the PostgreSQL database "test" at "localhost:15432".
Do you want to continue? All data will be lost. › (y/N)
```

## Expected behavior

The initial migration is created without drift issues.

## Prisma information
PostgreSQL structure:
[schema-postgres.sql.zip](https://github.com/prisma/prisma/files/6291136/schema-postgres.sql.zip)

Here's my `prisma.schema` also, but you can easily produce it by running `prisma introspect`.
[schema.prisma.zip](https://github.com/prisma/prisma/files/6291137/schema.prisma.zip)

And the first migration it generates:
[20210411032551_init.zip](https://github.com/prisma/prisma/files/6291141/20210411032551_init.zip)

And the subsequent migration, which it can't apply:
[20210411032733_init2.zip](https://github.com/prisma/prisma/files/6291143/20210411032733_init2.zip)

When trying to apply this second migration the error is:
```shell
prisma migrate dev --name init2
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "test", schema "public" at "localhost:15432"

✔ Drift detected: Your database schema is not in sync with your migration history.

We need to reset the PostgreSQL database "test" at "localhost:15432".
Do you want to continue? All data will be lost. … yes

eThe following migration(s) have been applied:

migrations/
  └─ 20210411032551_init/
    └─ migration.sql
Error: Database error
Error querying the database: db error: ERROR: relation "idx_51688_draad_id" already exists
   0: migration_core::api::ApplyMigrations
             at migration-engine/core/src/api.rs:73
```

## Environment & setup

- OS: Mac OS
- Database: PostgreSQL (running in local Docker container using `postgres:13-alpine`)
- Node.js version: v14.16.0
- Prisma version:
```
prisma               : 2.20.1
@prisma/client       : 2.20.1
Current platform     : darwin
Query Engine         : query-engine 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/query-engine-darwin)
Migration Engine     : migration-engine-cli 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine : introspection-core 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary        : prisma-fmt 60ba6551f29b17d7d6ce479e5733c70d9c00860e (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash : 60ba6551f29b17d7d6ce479e5733c70d9c00860e
Studio               : 0.365.0
```

**Comment by PeterDekkers** [comment]
I tried simplifying my source database using the following SQL statements. The introspection turned out a different `schema.prisma`, as expected. It still returned the `Drift detected: Your database schema is not in sync with your migration history.` when creating the first migration.
```sql
alter table actions_log alter column created_at type timestamp using created_at::timestamp;
alter table actions_log alter column created_at set default CURRENT_TIMESTAMP;
alter table actions_log alter column updated_at type timestamp using updated_at::timestamp;
alter table actions_log alter column id type int using id::int;
alter table actions_log alter column user_id type int using user_id::int;
alter table bookmarks alter column created_at type timestamp using created_at::timestamp;
alter table bookmarks alter column created_at set default CURRENT_TIMESTAMP;
alter table bookmarks alter column updated_at type timestamp using updated_at::timestamp;
alter table bookmarks alter column id type int using id::int;
alter table bookmarks alter column topic_id type int using topic_id::int;
alter table bookmarks alter column user_id type int using user_id::int;
alter table bookmarks alter column topic_id drop default;
alter table buddies alter column created_at type timestamp using created_at::timestamp;
alter table buddies alter column created_at set default CURRENT_TIMESTAMP;
alter table buddies alter column updated_at type timestamp using updated_at::timestamp;
alter table buddies alter column id type int using id::int;
alter table buddies alter column user_id type int using user_id::int;
alter table buddies alter column buddy_user_id type int using buddy_user_id::int;
alter table drawings alter column created_at type timestamp using created_at::timestamp;
alter table drawings alter column created_at set default CURRENT_TIMESTAMP;
alter table drawings alter column updated_at type timestamp using updated_at::timestamp;
alter table drawings alter column deleted_at type timestamp using deleted_at::timestamp;
alter table drawings alter column id type int using id::int;
alter table drawings alter column user_id type int using user_id::int;
alter table drawings alter column post_id type int using post_id::int;
alter table failed_logins alter column created_at type timestamp using created_at::timestamp;
alter table failed_logins alter column created_at set default CURRENT_TIMESTAMP;
alter table failed_logins alter column updated_at type timestamp using updated_at::timestamp;
alter table failed_logins alter column ip set not null;
alter table failed_logins alter column username drop default;
alter table failed_logins alter column ip drop default;
alter table failed_logins alter column id type int using id::int;
UPDATE failed_logins SET username = NULL where username = '';
alter table forums alter column name drop default;
alter table forums alter column id type int using id::int;
alter table invite_votes alter column created_at type timestamp using created_at::timestamp;
alter table invite_votes alter column created_at set default CURRENT_TIMESTAMP;
alter table invite_votes alter column updated_at type timestamp using updated_at::timestamp;
alter table invite_votes alter column id type int using id::int;
alter table invite_votes alter column invite_id type int using invite_id::int;
alter table invite_votes alter column user_id type int using user_id::int;
alter table invites alter column created_at type timestamp using created_at::timestamp;
alter table invites alter column created_at set default CURRENT_TIMESTAMP;
alter table invites alter column updated_at type timestamp using updated_at::timestamp;
alter table invites alter column name drop default;
alter table invites alter column email drop default;
alter table invites alter column id type int using id::int;
alter table invites alter column user_id type int using user_id::int;
alter table invites alter column registered_user_id type int using registered_user_id::int;
alter table message_notifications alter column sent_at type timestamp using sent_at::timestamp;
alter table message_notifications alter column created_at type timestamp using created_at::timestamp;
alter table message_notifications alter column created_at set default CURRENT_TIMESTAMP;
alter table message_notifications alter column updated_at type timestamp using updated_at::timestamp;
alter table message_notifications alter column id type int using id::int;
alter table message_notifications alter column user_id type int using user_id::int;
alter table message_notifications alter column message_id type int using message_id::int;
alter table message_recipients alter column read_at type timestamp using read_at::timestamp;
alter table message_recipients alter column deleted_at type timestamp using deleted_at::timestamp;
alter table message_recipients alter column created_at type timestamp using created_at::timestamp;
alter table message_recipients alter column created_at set default CURRENT_TIMESTAMP;
alter table message_recipients alter column updated_at type timestamp using updated_at::timestamp;
alter table message_recipients alter column id type int using id::int;
alter table message_recipients alter column user_id type int using user_id::int;
alter table message_recipients alter column message_id type int using message_id::int;
alter table messages alter column deleted_at type timestamp using deleted_at::timestamp;
alter table messages alter column created_at type timestamp using created_at::timestamp;
alter table messages alter column created_at set default CURRENT_TIMESTAMP;
alter table messages alter column updated_at type timestamp using updated_at::timestamp;
alter table messages alter column id type int using id::int;
alter table messages alter column user_id type int using user_id::int;
alter table password_resets alter column created_at type timestamp using created_at::timestamp;
alter table password_resets alter column created_at set default CURRENT_TIMESTAMP;
alter table password_resets alter column updated_at type timestamp using updated_at::timestamp;
alter table password_resets alter column id type int using id::int;
alter table posts alter column created_at type timestamp using created_at::timestamp;
alter table posts alter column created_at set default CURRENT_TIMESTAMP;
alter table posts alter column updated_at type timestamp using updated_at::timestamp;
alter table posts alter column edited_at type timestamp using edited_at::timestamp;
alter table posts alter column topic_id drop default;
alter table posts alter column gebruiker_alias drop default;
alter table posts alter column id type int using id::int;
alter table posts alter column user_id type int using user_id::int;
alter table posts alter column topic_id type int using topic_id::int;
alter table posts alter column edited_user_id type int using edited_user_id::int;
alter table topic_notifications alter column sent_at type timestamp using sent_at::timestamp;
alter table topic_notifications alter column last_read_at type timestamp using last_read_at::timestamp;
alter table topic_notifications alter column created_at type timestamp using created_at::timestamp;
alter table topic_notifications alter column created_at set default CURRENT_TIMESTAMP;
alter table topic_notifications alter column updated_at type timestamp using updated_at::timestamp;
alter table topic_notifications alter column id type int using id::int;
alter table topic_notifications alter column user_id type int using user_id::int;
alter table topic_notifications alter column topic_id type int using topic_id::int;
alter table topics alter column title drop not null;
alter table topics alter column title drop default;
alter table topics alter column last_post_at type timestamp using last_post_at::timestamp;
alter table topics alter column forum_id drop default;
alter table topics alter column post_count set default 0;
alter table topics alter column created_at type timestamp using created_at::timestamp;
alter table topics alter column created_at set default CURRENT_TIMESTAMP;
alter table topics alter column updated_at type timestamp using updated_at::timestamp;
alter table topics alter column id type int using id::int;
alter table topics alter column user_id type int using user_id::int;
alter table topics alter column last_user_id type int using last_user_id::int;
alter table user_topic_last_read alter column last_post_read_at type timestamp using last_post_read_at::timestamp;
alter table user_topic_last_read alter column created_at type timestamp using created_at::timestamp;
alter table user_topic_last_read alter column created_at set default CURRENT_TIMESTAMP;
alter table user_topic_last_read alter column updated_at type timestamp using updated_at::timestamp;
alter table user_topic_last_read alter column id type int using id::int;
alter table user_topic_last_read alter column topic_id type int using topic_id::int;
alter table user_topic_last_read alter column user_id type int using user_id::int;
alter table username_history alter column created_at type timestamp using created_at::timestamp;
alter table username_history alter column created_at set default CURRENT_TIMESTAMP;
alter table username_history alter column updated_at type timestamp using updated_at::timestamp;
alter table username_history alter column id type int using id::int;
alter table username_history alter column user_id type int using user_id::int;
alter table username_history alter column admin_user_id type int using admin_user_id::int;
alter table users alter column born_at type timestamp using born_at::timestamp;
alter table users alter column online_at type timestamp using online_at::timestamp;
alter table users alter column buddy_css_version set default 0;
alter table users alter column invite_count type int using invite_count::int;
alter table users alter column invite_count set default 0;
alter table users alter column created_at type timestamp using created_at::timestamp;
alter table users alter column created_at set default CURRENT_TIMESTAMP;
alter table users alter column updated_at type timestamp using updated_at::timestamp;
alter table users alter column id type int using id::int;
alter table users alter column buddy_css_version type int using buddy_css_version::int;
alter table users alter column last_post_id type int using last_post_id::int;
alter sequence actions_log_id_seq as int;
alter sequence bookmarks_id_seq as int;
alter sequence buddies_id_seq as int;
alter sequence drawings_id_seq as int;
alter sequence failed_logins_id_seq as int;
alter sequence forums_id_seq as int;
alter sequence invite_votes_id_seq as int;
alter sequence invites_id_seq as int;
alter sequence message_notifications_id_seq as int;
alter sequence message_recipients_id_seq as int;
alter sequence messages_id_seq as int;
alter sequence password_resets_id_seq as int;
alter sequence posts_id_seq as int;
alter sequence topic_notifications_id_seq as int;
alter sequence topics_id_seq as int;
alter sequence user_topic_last_read_id_seq as int;
alter sequence username_history_id_seq as int;
alter sequence users_id_seq as int;
```

**Comment by PeterDekkers** [comment]
Minimal reproduction seems to be possible with this single table SQL dump:
```sql
--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actions_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.actions_log (
    id integer NOT NULL,
    type character varying(64),
    user_id integer NOT NULL,
    data text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone
);


ALTER TABLE public.actions_log OWNER TO postgres;

--
-- Name: actions_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.actions_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.actions_log_id_seq OWNER TO postgres;

--
-- Name: actions_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.actions_log_id_seq OWNED BY public.actions_log.id;


--
-- Name: actions_log actions_log_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.actions_log
    ADD CONSTRAINT actions_log_pk PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--
```

**Comment by PeterDekkers** [comment]
Actually, apologies, this minimal reproduction only returns `Drift detected` on the _first_ initial migration. Once that has run the subsequent runs work fine.

I'm starting to suspect that it has something to do with the indices on the other tables.

**Comment by PeterDekkers** [comment]
It seems to be due to a having more than one index for a column, e.g.
```sql
  @@index([topic_id], name: "idx_16483_draad_id")
  @@index([topic_id], name: "idx_16483_draad_id_2")
```

**Comment by PeterDekkers** [comment]
Yes, that was it. Totally freaks the migration generation out. Mystery solved.

**Comment by janpio** [comment]
Thanks for the amazing reproduction and detective work figuring out what is going on - perfect input for us to fix this.

**Comment by pantharshit00** [comment]
I can confirm this bug. Thanks for detailed reproduction and providing the dump.

**Comment by andresribeiro** [comment]
Any temporary solution for this issue?

**Comment by PeterDekkers** [comment]
> Any temporary solution for this issue?

Removing one of the duplicate indexes will obviously work. Not sure if that applies to your situation.

**Comment by andresribeiro** [comment]
@PeterDekkers I have looked at my database, and there is no duplicate index

**Comment by pantharshit00** [comment]
@andresribeiro Open a new issue then, it might be unrelated to this one.

**Comment by AviBueno** [comment]
@janpio / @pantharshit00: Bumped into the same behavior with my own Sqlite DB, but it's easily reproduced with the Sqlite starter kit of Prisma's latest version (2.21.2).
* No duplicate keys involved as far as the eye can see.

**Comment by tomhoule** [comment]
This depends on https://github.com/prisma/prisma/issues/6680 being addressed.

**Comment by Timsonrobl** [comment]
I'm having the similar issue. Introspect -> initial migrate immediately detects drift and suggests full data wipe as a remedy for happy migration.
Table have no indexes and migrate output suggests it wants to create unique index on a column with unique constraint?
```
Drift detected: Your database schema is not in sync with your migration history.

[+] Added tables
  - storage
  - users

[*] Changed the `users` table
  [+] Added unique index on columns (sessionId)


We need to reset the SQLite database "sqlite-main.db" at "file:../sqlite-main.db".
Do you want to continue? All data will be lost.
```
All introspected tables are reported as "added tables". This is the introspected model:
```
model users {
  id              String  @id
  sessionId       String? @unique
  displayName     String?
  accessToken     String?
  expiryTimestamp Int?
  refreshToken    String?
  broadcasterType String?
}
```
Both database and model don't have unique index of `sessionId` field (only constraint).

**Comment by Timsonrobl** [comment]
This is introspected table:
```
CREATE TABLE "users" (
	"id"	TEXT NOT NULL,
	"sessionId"	TEXT UNIQUE,
	"displayName"	TEXT,
	"accessToken"	TEXT,
	"expiryTimestamp"	INTEGER,
	"refreshToken"	TEXT,
	"broadcasterType"	TEXT,
	PRIMARY KEY("id")
);
```
This is migration sql after introspection -> migration (accepting full data wipe):
```
-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sessionId" TEXT,
    "displayName" TEXT,
    "accessToken" TEXT,
    "expiryTimestamp" INTEGER,
    "refreshToken" TEXT,
    "broadcasterType" TEXT
);

-- CreateIndex
CREATE UNIQUE INDEX "users.sessionId_unique" ON "users"("sessionId");
```
Is this correct behavior?

**Comment by janpio** [comment]
Although this looks similar, I think if you get this directly after Introspection, you are looking more at https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/baselining @Timsonrobl than on what is reported in the original issue here (first it is about the same thing, but then the user did the reset and migrate is _still_ detecting drift).

**Comment by Timsonrobl** [comment]
@janpio so should I open separate issue? Or is it desired behavior? I'm looking at https://www.prisma.io/docs/guides/general-guides/database-workflows/unique-constraints-and-indexes/sqlite and don't see why initial migration would replace unique constraint with manually created index but maybe I don't understand something.
If I baseline my production database to this it would always be detected as a drift on account of having additional constraint and miss on manually created unique index name.

**Comment by janpio** [comment]
This is not desired behavior and is being fixed via a big initiative https://github.com/prisma/prisma/issues/6680 that we are hoping to roll out soon - then index names will be represented in the schema correctly and this will put an end to this useless drift detection.

So if you think that is _exactly_ what is happening to you, then I think this issue is indeed exactly what you are experiencing.

**Comment by janpio** [comment]
Ping @Timsonrobl @PeterDekkers

**Comment by janpio** [comment]
I went through this with the schema from @PeterDekkers to see how it behaves now:

Introspection with `npx prisma db pull` creates this schema:

```prisma
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model actions_log {
  id         BigInt    @id(map: "idx_51593_primary") @default(autoincrement())
  type       String?   @db.VarChar(64)
  user_id    BigInt
  data       String?
  created_at DateTime  @db.Timestamptz(6)
  updated_at DateTime? @db.Timestamptz(6)
}

model bookmarks {
  id         BigInt    @id(map: "idx_51602_primary") @default(autoincrement())
  topic_id   BigInt    @default(0)
  user_id    BigInt?
  created_at DateTime? @db.Timestamptz(6)
  updated_at DateTime? @db.Timestamptz(6)

  @@index([user_id], map: "idx_51602_bookmarks_user_id_index")
  @@index([topic_id], map: "idx_51602_draad_id")
}

model buddies {
  id            BigInt    @id(map: "idx_51609_primary") @default(autoincrement())
  color_bg      String?   @db.VarChar(25)
  color_font    String?   @db.VarChar(25)
  user_id       BigInt?
  buddy_user_id BigInt?
  created_at    DateTime? @db.Timestamptz(6)
  updated_at    DateTime? @db.Timestamptz(6)

  @@unique([user_id, buddy_user_id], map: "idx_51609_user_id")
  @@index([buddy_user_id], map: "idx_51609_user_buddy_id")
  @@index([user_id], map: "idx_51609_user_id_2")
}

model drawings {
  id         BigInt    @id(map: "idx_51615_primary") @default(autoincrement())
  user_id    BigInt
  post_id    BigInt?
  path       String
  created_at DateTime  @db.Timestamptz(6)
  updated_at DateTime? @db.Timestamptz(6)
  deleted_at DateTime? @db.Timestamptz(6)

  @@index([user_id], map: "idx_51615_user_id")
}

model failed_logins {
  id         BigInt    @id(map: "idx_51624_primary") @default(autoincrement())
  username   String?   @default("") @db.VarChar(100)
  ip         String?   @default("") @db.VarChar(32)
  type       String?   @db.VarChar(64)
  created_at DateTime  @db.Timestamptz(6)
  updated_at DateTime? @db.Timestamptz(6)
}

model forums {
  id   BigInt @id(map: "idx_51632_primary") @default(autoincrement())
  name String @default("") @db.VarChar(100)
}

model invite_votes {
  id         BigInt    @id(map: "idx_51650_primary") @default(autoincrement())
  invite_id  BigInt
  user_id    BigInt
  vote       String?   @db.VarChar(64)
  created_at DateTime? @db.Timestamptz(6)
  updated_at DateTime? @db.Timestamptz(6)

  @@unique([invite_id, user_id], map: "idx_51650_invite_id")
}

model invites {
  id                 BigInt    @id(map: "idx_51639_primary") @default(autoincrement())
  user_id            BigInt
  status             String?   @db.VarChar(64)
  name               String    @default("") @db.VarChar(255)
  email              String    @default("") @db.VarChar(255)
  about              String
  registered_user_id BigInt?
  created_at         DateTime  @db.Timestamptz(6)
  updated_at         DateTime? @db.Timestamptz(6)
}

model message_notifications {
  id         BigInt    @id(map: "idx_51666_primary") @default(autoincrement())
  user_id    BigInt
  message_id BigInt
  sent_at    DateTime? @db.Timestamptz(6)
  created_at DateTime  @db.Timestamptz(6)
  updated_at DateTime? @db.Timestamptz(6)
}

model message_recipients {
  id         BigInt    @id(map: "idx_51672_primary") @default(autoincrement())
  user_id    BigInt
  message_id BigInt
  read_at    DateTime? @db.Timestamptz(6)
  deleted    Boolean   @default(false)
  deleted_at DateTime? @db.Timestamptz(6)
  created_at DateTime  @db.Timestamptz(6)
  updated_at DateTime? @db.Timestamptz(6)

  @@index([deleted], map: "idx_51672_deleted")
  @@index([message_id], map: "idx_51672_message_id")
  @@index([user_id], map: "idx_51672_recipient_user_id")
}

model messages {
  id         BigInt    @id(map: "idx_51656_primary") @default(autoincrement())
  user_id    BigInt
  subject    String?   @db.VarChar(255)
  content    String?
  deleted    Boolean   @default(false)
  deleted_at DateTime? @db.Timestamptz(6)
  created_at DateTime  @db.Timestamptz(6)
  updated_at DateTime? @db.Timestamptz(6)

  @@index([deleted], map: "idx_51656_deleted")
  @@index([user_id], map: "idx_51656_user_id")
}

model password_resets {
  id         BigInt    @id(map: "idx_51679_primary") @default(autoincrement())
  email      String    @db.VarChar(255)
  token      String    @db.VarChar(255)
  created_at DateTime  @db.Timestamptz(6)
  updated_at DateTime? @db.Timestamptz(6)

  @@index([email], map: "idx_51679_password_resets_email_index")
  @@index([token], map: "idx_51679_password_resets_token_index")
}

model posts {
  id              BigInt    @id(map: "idx_51688_primary") @default(autoincrement())
  user_id         BigInt?
  is_anonymous    Boolean   @default(false)
  topic_id        BigInt    @default(0)
  gebruiker_alias String    @default("") @db.VarChar(100)
  created_at      DateTime? @db.Timestamptz(6)
  updated_at      DateTime? @db.Timestamptz(6)
  content         String
  code            String?
  is_deleted      Boolean?  @default(false)
  edited_at       DateTime? @db.Timestamptz(6)
  edited_user_id  BigInt?
  post_edit_user  String?   @db.VarChar(100)

  @@index([gebruiker_alias], map: "idx_51688_alias_index")
  @@index([topic_id], map: "idx_51688_draad_id")
  @@index([topic_id], map: "idx_51688_draad_id_2")
  @@index([topic_id, created_at], map: "idx_51688_draad_id_3")
  @@index([topic_id], map: "idx_51688_fk_draadid_post_index")
  @@index([gebruiker_alias], map: "idx_51688_gebruiker_alias")
  @@index([created_at], map: "idx_51688_post_datum")
  @@index([is_deleted], map: "idx_51688_post_deleted")
  @@index([id], map: "idx_51688_post_id")
  @@index([user_id], map: "idx_51688_posts_user_id_index")
}

model topic_notifications {
  id           BigInt    @id(map: "idx_51714_primary") @default(autoincrement())
  user_id      BigInt
  topic_id     BigInt
  sent_at      DateTime? @db.Timestamptz(6)
  last_read_at DateTime  @db.Timestamptz(6)
  created_at   DateTime  @db.Timestamptz(6)
  updated_at   DateTime? @db.Timestamptz(6)

  @@index([last_read_at], map: "idx_51714_last_read_at")
  @@index([sent_at], map: "idx_51714_sent_at")
  @@index([topic_id], map: "idx_51714_topic_id")
  @@index([user_id], map: "idx_51714_user_id")
}

model topics {
  id           BigInt    @id(map: "idx_51701_primary") @default(autoincrement())
  title        String    @default("") @db.VarChar(255)
  user_id      BigInt?
  last_user_id BigInt?
  last_post_at DateTime? @db.Timestamptz(6)
  forum_id     Int       @default(0) @db.SmallInt
  status       Boolean   @default(false)
  closed       Boolean   @default(false)
  is_deleted   Boolean   @default(false)
  post_count   BigInt    @default(1)
  is_anonymous Boolean   @default(false)
  created_at   DateTime? @db.Timestamptz(6)
  updated_at   DateTime? @db.Timestamptz(6)

  @@index([closed], map: "idx_51701_draad_closed")
  @@index([id], map: "idx_51701_draad_id")
  @@index([last_post_at], map: "idx_51701_draad_laatste_datum")
  @@index([created_at], map: "idx_51701_draad_start_datum")
  @@index([status], map: "idx_51701_draad_state")
  @@index([forum_id], map: "idx_51701_forum_id")
}

model user_topic_last_read {
  id                BigInt    @id(map: "idx_51746_primary") @default(autoincrement())
  topic_id          BigInt
  user_id           BigInt
  last_post_read_at DateTime  @db.Timestamptz(6)
  created_at        DateTime? @db.Timestamptz(6)
  updated_at        DateTime? @db.Timestamptz(6)

  @@unique([topic_id, user_id], map: "idx_51746_topic_user")
}

model username_history {
  id            BigInt    @id(map: "idx_51720_primary") @default(autoincrement())
  user_id       BigInt
  status        String?   @db.VarChar(64)
  admin_user_id BigInt?
  username      String?   @db.VarChar(255)
  old_username  String?   @db.VarChar(255)
  created_at    DateTime  @db.Timestamptz(6)
  updated_at    DateTime? @db.Timestamptz(6)
}

model users {
  id                BigInt    @id(map: "idx_51729_primary") @default(autoincrement())
  username          String?   @db.VarChar(255)
  password          String?   @db.VarChar(255)
  info              String?
  email             String?   @db.VarChar(255)
  hide_email        Boolean   @default(false)
  allowed           Boolean   @default(false)
  admin             Boolean   @default(false)
  url1              String?   @db.VarChar(255)
  url2              String?   @db.VarChar(255)
  url3              String?   @db.VarChar(255)
  name              String?   @db.VarChar(255)
  born_at           DateTime? @db.Timestamptz(6)
  location          String?   @db.VarChar(255)
  online_at         DateTime? @db.Timestamptz(6)
  ip                String?   @db.VarChar(255)
  title             String?   @db.VarChar(255)
  show_avatars      Boolean   @default(false)
  disable_media     Boolean   @default(false)
  gui_listings      String?   @db.VarChar(64)
  gui_menu          String?   @db.VarChar(64)
  buddy_css_version BigInt    @default(0)
  invite_count      BigInt    @default(0)
  last_post_id      BigInt?
  message_notify    Boolean   @default(false)
  img_original      String?   @db.VarChar(255)
  img_small         String?   @db.VarChar(255)
  img_bigger        String?   @db.VarChar(255)
  timezone          String?   @db.VarChar(255)
  created_at        DateTime? @db.Timestamptz(6)
  updated_at        DateTime? @db.Timestamptz(6)

  @@index([username], map: "idx_51729_gebruiker_alias")
}
```

A first `npx prisma migrate dev` then detects "drift" and resets the database:

```
C:\Users\Jan\Documents\throwaway\6505>npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "magenta_tiger", schema "public" at "pg-db-provision.cm0mkpwj8arx.eu-central-1.rds.amazonaws.com:5432"

√ Drift detected: Your database schema is not in sync with your migration history.

The following is a summary of the differences between the expected database schema given your migrations files, and the actual schema of the database.

It should be understood as the set of changes to get from the expected schema to the actual schema.

[+] Added tables
  - actions_log
  - bookmarks
  - buddies
  - drawings
  - failed_logins
  - forums
  - invite_votes
  - invites
  - message_notifications
  - message_recipients
  - messages
  - password_resets
  - posts
  - topic_notifications
  - topics
  - user_topic_last_read
  - username_history
  - users

[*] Changed the `bookmarks` table
  [+] Added index on columns (user_id)
  [+] Added index on columns (topic_id)

[*] Changed the `buddies` table
  [+] Added index on columns (buddy_user_id)
  [+] Added unique index on columns (user_id, buddy_user_id)
  [+] Added index on columns (user_id)

[*] Changed the `drawings` table
  [+] Added index on columns (user_id)

[*] Changed the `invite_votes` table
  [+] Added unique index on columns (invite_id, user_id)

[*] Changed the `message_recipients` table
  [+] Added index on columns (deleted)
  [+] Added index on columns (message_id)
  [+] Added index on columns (user_id)

[*] Changed the `messages` table
  [+] Added index on columns (deleted)
  [+] Added index on columns (user_id)

[*] Changed the `password_resets` table
  [+] Added index on columns (email)
  [+] Added index on columns (token)

[*] Changed the `posts` table
  [+] Added index on columns (gebruiker_alias)
  [+] Added index on columns (topic_id)
  [+] Added index on columns (topic_id)
  [+] Added index on columns (topic_id, created_at)
  [+] Added index on columns (topic_id)
  [+] Added index on columns (gebruiker_alias)
  [+] Added index on columns (created_at)
  [+] Added index on columns (is_deleted)
  [+] Added index on columns (id)
  [+] Added index on columns (user_id)

[*] Changed the `topic_notifications` table
  [+] Added index on columns (last_read_at)
  [+] Added index on columns (sent_at)
  [+] Added index on columns (topic_id)
  [+] Added index on columns (user_id)

[*] Changed the `topics` table
  [+] Added index on columns (closed)
  [+] Added index on columns (id)
  [+] Added index on columns (last_post_at)
  [+] Added index on columns (created_at)
  [+] Added index on columns (status)
  [+] Added index on columns (forum_id)

[*] Changed the `user_topic_last_read` table
  [+] Added unique index on columns (topic_id, user_id)

[*] Changed the `users` table
  [+] Added index on columns (username)


We need to reset the PostgreSQL database "magenta_tiger" at "pg-db-provision.cm0mkpwj8arx.eu-central-1.rds.amazonaws.com:5432".
Do you want to continue? All data will be lost. ... yes

√ Enter a name for the new migration: ... init
The following migration(s) have been created and applied from new schema changes:

migrations/
  └─ 20210917185801_init/
    └─ migration.sql

Your database is now in sync with your schema.
```

Another `migrate dev` then leads to the database found in sync:

```
C:\Users\Jan\Documents\throwaway\6505>npx prisma migrate dev
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Datasource "db": PostgreSQL database "magenta_tiger", schema "public" at "pg-db-provision.cm0mkpwj8arx.eu-central-1.rds.amazonaws.com:5432"

Already in sync, no schema change or pending migration was found.
```

So I would consider the original issue to be fixed. Do you agree @PeterDekkers?

**Comment by PringlePot** [comment]
This isn't fixed tho since the data is being reset tho right?

**Comment by janpio** [comment]
No, with not existing history that is expected. Use baselining to create a history that it can use to figure out if there is actual drift: https://www.prisma.io/docs/guides/database/developing-with-prisma-migrate/baselining
