### ISSUE TITLE
MSSQL Prisma: ConnectorError { user_facing_error: None, kind: QueryError(Utf8)

### ISSUE THREAD

**Issue by BJladika** [prisma/prisma#7476]
### Bug description

Kinda premise is here: https://github.com/prisma/prisma/discussions/7475

In short: Introspected via prisma already existing database on localhost (which was created via .bak file earlier with MS SQL Server Studio), tried to make a basic query/graphql type for start via example and now receiving error while querying
```Invalid `prisma.people_List.findMany()` invocation:\n\n\n Error occurred during query execution:\nConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Utf8) })```

### Prisma information

```
generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["microsoftSqlServer"]
}

datasource db {
  provider = "sqlserver"
  url      = env("DATABASE_URL")
}

model people_List {
  id_People           Int       @id @default(autoincrement())
  Surname             String    @db.VarChar(30)
  Name                String    @db.VarChar(30)
  **[A lot of other columns] too lazy to describe**
}

```

### Environment & setup

- OS: Windows 10 [RU]
- Database: MSSQL
- Node.js version: 15.8

**Comment by janpio** [comment]
Can you post the full log with https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/logging enabled and `DEBUG=*` set? 
What version of Prisma are you using? (The template usually asks for the `prisma -v` output)

**Comment by BJladika** [comment]
prisma: 2.24.1
prisma/client: 2.24.1
I am a bit lost - where to set this debug?

**Comment by janpio** [comment]
It is an environment variable that you can set, sorry I should have explained that better. See https://www.prisma.io/docs/concepts/components/prisma-client/debugging#overview (On windows you actually use `set DEBUG=*` command)

**Comment by BJladika** [comment]
no, I quite understood that you're refering to this page, but I didnt understand from it, where exactly I must write this command

**Comment by janpio** [comment]
In the command line before you run the command, so probably some terminal or console. It sets the environment variable for when you run your node script (or start your web server etc).

**Comment by BJladika** [comment]
I kinda just write 'npm run dev' in cmd from Windows. Already tried to write ```export DEBUG="*"``` via cmd, didnt work

**Comment by janpio** [comment]
As I said above, on Windows it is `set DEBUG=*` that you run first, then `npm run dev`. (I opened an issue to update our docs with Windows instructions)

**Comment by BJladika** [comment]
well, kinda run, a lot of junk
```
 prisma:engine stdout Unknown error +1ms
prisma:query SELECT [dbo].[people_List].[id_People], [dbo].[people_List].[Surname], [dbo].[people_List].[Name], [dbo].[people_List].[Patronymic], [dbo].[people_List].[OldSurname], [dbo].[people_List].[OldName], [dbo].[people_List].[OldPatronymic], [dbo].[people_List].[Marriage], [dbo].[people_List].[Sex], [dbo].[people_List].[BornDate], [dbo].[people_List].[BornPlace], [dbo].[people_List].[id_Doc], [dbo].[people_List].[DocSerial], [dbo].[people_List].[DocNo], [dbo].[people_List].[DocDistributed], [dbo].[people_List].[DocDate], [dbo].[people_List].[DocDepartmentCode], [dbo].[people_List].[id_Sitizen], [dbo].[people_List].[Photo], [dbo].[people_List].[Other], [dbo].[people_List].[is_webimported], [dbo].[people_List].[id_web], [dbo].[people_List].[FIO], [dbo].[people_List].[FIO2], [dbo].[people_List].[msrepl_tran_version], [dbo].[people_List].[SurnameRP], [dbo].[people_List].[NameRP], [dbo].[people_List].[PatronymicRP], [dbo].[people_List].[id_Nationality_old], [dbo].[people_List].[id_Nationality], [dbo].[people_List].[UID], [dbo].[people_List].[UID_stat], [dbo].[people_List].[UID_sok], [dbo].[people_List].[UID_zo], [dbo].[people_List].[INN_old], [dbo].[people_List].[SSN], [dbo].[people_List].[INN], [dbo].[people_List].[tabNumber] FROM [dbo].[people_List] WHERE 1=1
  prisma:engine stdout Fetched a connection from the pool +1ms
  prisma:engine stdout Flushing unhandled packet from the wire. Please consume your streams! +0ms
prisma:warn Flushing unhandled packet from the wire. Please consume your streams!
  prisma:engine stdout Flushing unhandled packet from the wire. Please consume your streams! +1ms
prisma:warn Flushing unhandled packet from the wire. Please consume your streams!
  prisma:engine stdout Flushing unhandled packet from the wire. Please consume your streams! +1ms
prisma:warn Flushing unhandled packet from the wire. Please consume your streams!
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
```

Also have checked my database on my server (localhost) and server collation (encoding) seems like is Cyrillic_General_CI_AS, could this be an issue?

**Comment by janpio** [comment]
It _should_ probably not, but considering that SQL Server is a preview feature that is indeed possible we do not support that properly yet.

Is this something that needs to be set on the server, database or table level? If you can share some code how to achieve this on a stock SQL Server, we might be able to reproduce this and hopefully understand and fix it.

**Comment by BJladika** [comment]
> Is this something that needs to be set on the server, database or table level? If you can share some code how to achieve this on a stock SQL Server, we might be able to reproduce this and hopefully understand and fix it.

You mean Collation (encoding)? Kinda it was automatically (I guess) set on installing MS SQL Server and MS SQL Server Studio. But I suppose it can be changed at least via MS SQL Server Studio with right-clicking and setting parameters of collation of the database

**Comment by BJladika** [comment]
kinda "full" log, opened cmd - npm run dev - made query (on playground) - stopped server
```
  nodemon bus new listener: reset (0) +0ms
  nodemon bus new listener: reset (0) +1ms
  nodemon bus new listener: quit (0) +21ms
  nodemon bus new listener: quit (0) +0ms
  nodemon bus new listener: restart (0) +1ms
  nodemon bus new listener: restart (0) +0ms
  nodemon bus new listener: reset (2) +1ms
  nodemon bus emit: reset +1ms
  nodemon resetting watchers +0ms
  nodemon reset +0ms
  nodemon config: dirs [ 'C:\\Projects\\Diplom_Work\\graphql-prisma-svfu' ] +0ms
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
  nodemon bus new listener: error (0) +38ms
  nodemon bus new listener: error (0) +0ms
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/server.js`
  nodemon:run fork C:\Windows\system32\cmd.exe /d /s /c node src/server.js +0ms
  nodemon bus new listener: exit (0) +10ms
  nodemon bus new listener: exit (0) +0ms
  nodemon:run start watch on: [ '*.*', re: /.*\..*/ ] +1ms
  nodemon start watch on: C:\Projects\Diplom_Work\graphql-prisma-svfu +49ms
  nodemon ignored [
  '**/.git/**',
  '**/.nyc_output/**',
  '**/.sass-cache/**',
  '**/bower_components/**',
  '**/coverage/**',
  '**/node_modules/**',
  re: /.*.*\/\.git\/.*.*|.*.*\/\.nyc_output\/.*.*|.*.*\/\.sass\-cache\/.*.*|.*.*\/bower_components\/.*.*|.*.*\/coverage\/.*.*|.*.*\/node_modules\/.*.*/
] +1ms
  nodemon:watch chokidar watching: C:\Projects\Diplom_Work\graphql-prisma-svfu\package-lock.json +0ms
  nodemon:watch chokidar watching: C:\Projects\Diplom_Work\graphql-prisma-svfu\package.json +1ms
  nodemon:watch chokidar watching: C:\Projects\Diplom_Work\graphql-prisma-svfu\README.md +1ms
  nodemon:watch chokidar watching: C:\Projects\Diplom_Work\graphql-prisma-svfu\schema.graphql +0ms
  nodemon:watch chokidar watching: C:\Projects\Diplom_Work\graphql-prisma-svfu\prisma\schema.prisma +4ms
  nodemon:watch chokidar watching: C:\Projects\Diplom_Work\graphql-prisma-svfu\src\context.js +1ms
  nodemon:watch chokidar watching: C:\Projects\Diplom_Work\graphql-prisma-svfu\src\schema.js +0ms
  nodemon:watch chokidar watching: C:\Projects\Diplom_Work\graphql-prisma-svfu\src\server.js +1ms
  nodemon:watch chokidar watching: C:\Projects\Diplom_Work\graphql-prisma-svfu\src\generated\nexus.ts +1ms
  nodemon watch is complete +20ms
  prisma:tryLoadEnv Environment variables loaded from C:\Projects\Diplom_Work\graphql-prisma-svfu\.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # Environment variables declared in this file are automatically made available to Prisma.
[dotenv][DEBUG] did not match key and value when parsing line 2: # See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables
[dotenv][DEBUG] did not match key and value when parsing line 3:
[dotenv][DEBUG] did not match key and value when parsing line 4: # Prisma supports the native connection string format for PostgreSQL, MySQL and SQLite.
[dotenv][DEBUG] did not match key and value when parsing line 5: # See the documentation for all the connection string options: https://pris.ly/d/connection-strings
[dotenv][DEBUG] did not match key and value when parsing line 6:
  prisma:tryLoadEnv Environment variables not found at C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\.prisma\client\.env +5ms
  prisma:tryLoadEnv Environment variables not found at C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\.prisma\client\.env +0ms
  prisma:tryLoadEnv No Environment variables loaded +0ms
  prisma:client clientVersion: 2.24.1 +0ms
  prisma:engine Search for Query Engine in C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\.prisma\client +0ms
  express:application set "x-powered-by" to true +0ms
  express:application set "etag" to 'weak' +1ms
  express:application set "etag fn" to [Function: generateETag] +0ms
  express:application set "env" to 'development' +1ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +0ms
  express:application set "subdomain offset" to 2 +1ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +0ms
  express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +1ms
  express:application set "views" to 'C:\\Projects\\Diplom_Work\\graphql-prisma-svfu\\views' +0ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:application set "x-powered-by" to false +1ms
  express:router use '/.well-known/apollo/server-health' <anonymous> +0ms
  express:router:layer new '/.well-known/apollo/server-health' +0ms
  express:router use '/' corsMiddleware +1ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +1ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +0ms
  express:router:layer new '/' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +0ms
  express:router use '/' query +0ms
  express:router:layer new '/' +1ms
  express:router use '/' expressInit +0ms
  express:router:layer new '/' +0ms
  express:router use '/' router +1ms
  express:router:layer new '/' +0ms
🚀 Server ready at: http://localhost:4000/
⭐️ See sample queries: http://pris.ly/e/js/graphql#using-the-graphql-api

  express:router dispatching POST / +220ms
  express:router query  : / +1ms
  express:router expressInit  : / +1ms
  express:router router  : / +1ms
  express:router dispatching POST / +1ms
  express:router corsMiddleware  : / +1ms
  express:router jsonParser  : / +2ms
  body-parser:json content-type "application/json" +0ms
  body-parser:json content-encoding "identity" +3ms
  body-parser:json read body +0ms
  body-parser:json parse body +15ms
  body-parser:json parse json +0ms
  express:router <anonymous>  : / +0ms
  express:router <anonymous>  : / +1ms
  express:router dispatching POST / +2s
  express:router query  : / +0ms
  express:router expressInit  : / +1ms
  express:router router  : / +0ms
  express:router dispatching POST / +0ms
  express:router corsMiddleware  : / +1ms
  express:router jsonParser  : / +0ms
  body-parser:json content-type "application/json" +0ms
  body-parser:json content-encoding "identity" +0ms
  body-parser:json read body +1ms
  body-parser:json parse body +0ms
  body-parser:json parse json +0ms
  express:router <anonymous>  : / +1ms
  express:router <anonymous>  : / +0ms
  prisma:client Prisma Client call: +2s
  prisma:client prisma.people_List.findMany(undefined) +0ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findManypeople_List {
  prisma:client     id_People
  prisma:client     Surname
  prisma:client     Name
  prisma:client     Patronymic
  prisma:client     OldSurname
  prisma:client     OldName
  prisma:client     OldPatronymic
  prisma:client     Marriage
  prisma:client     Sex
  prisma:client     BornDate
  prisma:client     BornPlace
  prisma:client     id_Doc
  prisma:client     DocSerial
  prisma:client     DocNo
  prisma:client     DocDistributed
  prisma:client     DocDate
  prisma:client     DocDepartmentCode
  prisma:client     id_Sitizen
  prisma:client     Photo
  prisma:client     Other
  prisma:client     is_webimported
  prisma:client     id_web
  prisma:client     FIO
  prisma:client     FIO2
  prisma:client     msrepl_tran_version
  prisma:client     SurnameRP
  prisma:client     NameRP
  prisma:client     PatronymicRP
  prisma:client     id_Nationality_old
  prisma:client     id_Nationality
  prisma:client     UID
  prisma:client     UID_stat
  prisma:client     UID_sok
  prisma:client     UID_zo
  prisma:client     INN_old
  prisma:client     SSN
  prisma:client     INN
  prisma:client     tabNumber
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:engine { cwd: 'C:\\Projects\\Diplom_Work\\graphql-prisma-svfu\\prisma' } +2s
  prisma:engine Search for Query Engine in C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\.prisma\client +1ms
  prisma:engine { flags: [ '--enable-raw-queries', '--port', '10239' ] } +2ms
  prisma:engine stdout Starting a mssql pool with 17 connections. +53ms
prisma:info Starting a mssql pool with 17 connections.
  prisma:engine stdout Performing a TLS handshake +13ms
prisma:info Performing a TLS handshake
  prisma:engine stdout Trusting the server certificate without validation. +1ms
prisma:warn Trusting the server certificate without validation.
  prisma:engine stdout TLS handshake successful +32ms
prisma:info TLS handshake successful
  prisma:engine stdout Turning TLS off after a login. All traffic from here on is not encrypted. +1ms
prisma:warn Turning TLS off after a login. All traffic from here on is not encrypted.
  prisma:engine stdout Database change from 'iisuss' to 'master' +0ms
prisma:info Database change from 'iisuss' to 'master'
  prisma:engine stdout Контекст базы данных изменен на "iisuss". +1ms
prisma:info Контекст базы данных изменен на "iisuss".
  prisma:engine stdout SQL collation change from None to None +1ms
prisma:info SQL collation change from None to None
  prisma:engine stdout Microsoft SQL Server version 3490119695 +0ms
prisma:info Microsoft SQL Server version 3490119695
  prisma:engine stdout Packet size change from '4096' to '4096' +1ms
prisma:info Packet size change from '4096' to '4096'
  prisma:engine stdout Fetched a connection from the pool +0ms
  prisma:engine stdout Started http server on http://127.0.0.1:10239 +1ms
prisma:info Started http server on http://127.0.0.1:10239
  prisma:engine Search for Query Engine in C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\.prisma\client +10ms
  prisma:engine stdout Fetched a connection from the pool +10ms
  prisma:engine stdout Unknown error +1ms
prisma:query SELECT [dbo].[people_List].[id_People], [dbo].[people_List].[Surname], [dbo].[people_List].[Name], [dbo].[people_List].[Patronymic], [dbo].[people_List].[OldSurname], [dbo].[people_List].[OldName], [dbo].[people_List].[OldPatronymic], [dbo].[people_List].[Marriage], [dbo].[people_List].[Sex], [dbo].[people_List].[BornDate], [dbo].[people_List].[BornPlace], [dbo].[people_List].[id_Doc], [dbo].[people_List].[DocSerial], [dbo].[people_List].[DocNo], [dbo].[people_List].[DocDistributed], [dbo].[people_List].[DocDate], [dbo].[people_List].[DocDepartmentCode], [dbo].[people_List].[id_Sitizen], [dbo].[people_List].[Photo], [dbo].[people_List].[Other], [dbo].[people_List].[is_webimported], [dbo].[people_List].[id_web], [dbo].[people_List].[FIO], [dbo].[people_List].[FIO2], [dbo].[people_List].[msrepl_tran_version], [dbo].[people_List].[SurnameRP], [dbo].[people_List].[NameRP], [dbo].[people_List].[PatronymicRP], [dbo].[people_List].[id_Nationality_old], [dbo].[people_List].[id_Nationality], [dbo].[people_List].[UID], [dbo].[people_List].[UID_stat], [dbo].[people_List].[UID_sok], [dbo].[people_List].[UID_zo], [dbo].[people_List].[INN_old], [dbo].[people_List].[SSN], [dbo].[people_List].[INN], [dbo].[people_List].[tabNumber] FROM [dbo].[people_List] WHERE 1=1
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Utf8) })
  prisma:engine       at NodeEngine.graphQLToJSError (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:28377:14)
  prisma:engine       at NodeEngine.request (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:28273:24)
  prisma:engine       at processTicksAndRejections (node:internal/process/task_queues:94:5)
  prisma:engine       at async cb (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:35193:26) {
  prisma:engine     clientVersion: '2.24.1'
  prisma:engine   }
  prisma:engine } +2ms
  prisma:engine stdout Fetched a connection from the pool +2ms
  prisma:engine stdout Flushing unhandled packet from the wire. Please consume your streams! +0ms
prisma:warn Flushing unhandled packet from the wire. Please consume your streams!
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Utf8) })
  prisma:engine       at NodeEngine.graphQLToJSError (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:28377:14)
  prisma:engine       at NodeEngine.request (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:28273:24)
  prisma:engine       at processTicksAndRejections (node:internal/process/task_queues:94:5)
  prisma:engine       at async cb (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:35193:26) {
  prisma:engine     clientVersion: '2.24.1'
  prisma:engine   }
  prisma:engine } +1ms
  prisma:engine stdout Flushing unhandled packet from the wire. Please consume your streams! +1ms
prisma:warn Flushing unhandled packet from the wire. Please consume your streams!
  prisma:engine stdout Flushing unhandled packet from the wire. Please consume your streams! +0ms
prisma:warn Flushing unhandled packet from the wire. Please consume your streams!
  prisma:engine stdout Unknown error +1ms
prisma:query SELECT [dbo].[people_List].[id_People], [dbo].[people_List].[Surname], [dbo].[people_List].[Name], [dbo].[people_List].[Patronymic], [dbo].[people_List].[OldSurname], [dbo].[people_List].[OldName], [dbo].[people_List].[OldPatronymic], [dbo].[people_List].[Marriage], [dbo].[people_List].[Sex], [dbo].[people_List].[BornDate], [dbo].[people_List].[BornPlace], [dbo].[people_List].[id_Doc], [dbo].[people_List].[DocSerial], [dbo].[people_List].[DocNo], [dbo].[people_List].[DocDistributed], [dbo].[people_List].[DocDate], [dbo].[people_List].[DocDepartmentCode], [dbo].[people_List].[id_Sitizen], [dbo].[people_List].[Photo], [dbo].[people_List].[Other], [dbo].[people_List].[is_webimported], [dbo].[people_List].[id_web], [dbo].[people_List].[FIO], [dbo].[people_List].[FIO2], [dbo].[people_List].[msrepl_tran_version], [dbo].[people_List].[SurnameRP], [dbo].[people_List].[NameRP], [dbo].[people_List].[PatronymicRP], [dbo].[people_List].[id_Nationality_old], [dbo].[people_List].[id_Nationality], [dbo].[people_List].[UID], [dbo].[people_List].[UID_stat], [dbo].[people_List].[UID_sok], [dbo].[people_List].[UID_zo], [dbo].[people_List].[INN_old], [dbo].[people_List].[SSN], [dbo].[people_List].[INN], [dbo].[people_List].[tabNumber] FROM [dbo].[people_List] WHERE 1=1
  prisma:engine {
  prisma:engine   error: PrismaClientUnknownRequestError2 [PrismaClientUnknownRequestError]: Error occurred during query execution:
  prisma:engine   ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Utf8) })
  prisma:engine       at NodeEngine.graphQLToJSError (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:28377:14)
  prisma:engine       at NodeEngine.request (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:28273:24)
  prisma:engine       at processTicksAndRejections (node:internal/process/task_queues:94:5)
  prisma:engine       at async cb (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:35193:26) {
  prisma:engine     clientVersion: '2.24.1'
  prisma:engine   }
  prisma:engine } +1ms
  prisma:client Error: Error occurred during query execution:
  prisma:client ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Utf8) })
  prisma:client     at NodeEngine.graphQLToJSError (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:28377:14)
  prisma:client     at NodeEngine.request (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:28273:24)
  prisma:client     at processTicksAndRejections (node:internal/process/task_queues:94:5)
  prisma:client     at async cb (C:\Projects\Diplom_Work\graphql-prisma-svfu\node_modules\@prisma\client\runtime\index.js:35193:26) +139ms
  prisma:engine stdout Fetched a connection from the pool +6ms
  prisma:engine stdout Flushing unhandled packet from the wire. Please consume your streams! +0ms
prisma:warn Flushing unhandled packet from the wire. Please consume your streams!
  prisma:engine stdout Flushing unhandled packet from the wire. Please consume your streams! +0ms
prisma:warn Flushing unhandled packet from the wire. Please consume your streams!
  prisma:engine stdout Flushing unhandled packet from the wire. Please consume your streams! +1ms
prisma:warn Flushing unhandled packet from the wire. Please consume your streams!
  prisma:engine stdout Unknown error +2ms
prisma:query SELECT [dbo].[people_List].[id_People], [dbo].[people_List].[Surname], [dbo].[people_List].[Name], [dbo].[people_List].[Patronymic], [dbo].[people_List].[OldSurname], [dbo].[people_List].[OldName], [dbo].[people_List].[OldPatronymic], [dbo].[people_List].[Marriage], [dbo].[people_List].[Sex], [dbo].[people_List].[BornDate], [dbo].[people_List].[BornPlace], [dbo].[people_List].[id_Doc], [dbo].[people_List].[DocSerial], [dbo].[people_List].[DocNo], [dbo].[people_List].[DocDistributed], [dbo].[people_List].[DocDate], [dbo].[people_List].[DocDepartmentCode], [dbo].[people_List].[id_Sitizen], [dbo].[people_List].[Photo], [dbo].[people_List].[Other], [dbo].[people_List].[is_webimported], [dbo].[people_List].[id_web], [dbo].[people_List].[FIO], [dbo].[people_List].[FIO2], [dbo].[people_List].[msrepl_tran_version], [dbo].[people_List].[SurnameRP], [dbo].[people_List].[NameRP], [dbo].[people_List].[PatronymicRP], [dbo].[people_List].[id_Nationality_old], [dbo].[people_List].[id_Nationality], [dbo].[people_List].[UID], [dbo].[people_List].[UID_stat], [dbo].[people_List].[UID_sok], [dbo].[people_List].[UID_zo], [dbo].[people_List].[INN_old], [dbo].[people_List].[SSN], [dbo].[people_List].[INN], [dbo].[people_List].[tabNumber] FROM [dbo].[people_List] WHERE 1=1
  prisma:engine Client Version: 2.24.1 +21ms
  prisma:engine Engine Version: query-engine 18095475d5ee64536e2f93995e48ad800737a9e4 +0ms
  prisma:engine Active provider: sqlserver +1ms
  express:router dispatching POST / +323ms
  express:router query  : / +0ms
  express:router expressInit  : / +2ms
  express:router router  : / +1ms
  express:router dispatching POST / +1ms
  express:router corsMiddleware  : / +1ms
  express:router jsonParser  : / +0ms
  body-parser:json content-type "application/json" +1ms
  body-parser:json content-encoding "identity" +1ms
  body-parser:json read body +0ms
  body-parser:json parse body +2ms
  body-parser:json parse json +0ms
  express:router <anonymous>  : / +1ms
  express:router <anonymous>  : / +0ms
```

**Comment by janpio** [comment]
Thanks, that should give us more information to reproduce. You hunch that this might be caused by the collation sounds reasonable to me.

**Comment by BJladika** [comment]
Changed my database collation to "Cyrillic_General_100_CI_AS_KS_WS_SC_UTF8", but the server (localhost) itself remains "Cyrillic_General_CI_AS". Still kinda receiving this query error. I'm now looking for way to change server collation too

**Comment by BJladika** [comment]
Interesting. Couldn't change server collation.

But I've created a minor separate database instead of the real one (which is from .bak file) with 1 table Users(id, name), and its working with collation "Cyrillic_General_CI_AS".

I am really frustrated what is happening. I even checked databases parameters, all the same (on the first sight), just the real one had SQL support of 2016, changed it to 2019 but still same error on this database

**Comment by BJladika** [comment]
Okay. I have managed a bit fix it. In short I guess its connected to query size, kinda. Reduced real model of people_List to (for example) id_People, Name, Surname - running fine (Prisma making query (from logs) "SELECT [dbo].[people_List].[id_People], [dbo].[people_List].[Surname], [dbo].[people_List].[Name], [dbo].[people_List].[Patronymic] FROM [dbo].[people_List] WHERE 1=1")
Changed it back to full model with a lot of columns - previously mentioned error

**Comment by janpio** [comment]
Definitely something on the Prisma side.

Can you share the full SQL of that table with _all_ the columns that made it fail? Maybe that is already enough to reproduce it on our side.

**Comment by BJladika** [comment]
Ofc, there's Prisma model
```
model people_List {
  id_People           Int       @id
  Surname             String    @db.VarChar(30)
  Name                String    @db.VarChar(30)
  Patronymic          String?   @db.VarChar(30)
  OldSurname          String?   @db.VarChar(30)
  OldName             String?   @db.VarChar(30)
  OldPatronymic       String?   @db.VarChar(30)
  Marriage            Boolean
  Sex                 String    @db.Char(1)
  BornDate            DateTime  @db.DateTime
  BornPlace           String?   @db.VarChar(100)
  id_Doc              Int       @db.SmallInt
  DocSerial           String    @db.VarChar(10)
  DocNo               String    @db.VarChar(30)
  DocDistributed      String?   @db.VarChar(150)
  DocDate             DateTime? @db.DateTime
  DocDepartmentCode   String?   @db.VarChar(50)
  id_Sitizen          Int       @db.SmallInt
  Photo               Bytes?    @db.Image
  Other               String?   @db.Text
  is_webimported      Boolean
  id_web              Int?
  FIO                 String    @db.VarChar(92)
  FIO2                String?   @db.VarChar(125)
  msrepl_tran_version String    @db.UniqueIdentifier
  SurnameRP           String?   @db.VarChar(30)
  NameRP              String?   @db.VarChar(30)
  PatronymicRP        String?   @db.VarChar(30)
  id_Nationality_old  Int?
  id_Nationality      Int?
  UID                 Int?
  UID_stat            Int?
  UID_sok             Int?
  UID_zo              Int?
  INN_old             BigInt?
  SSN                 String?   @db.VarChar(255)
  INN                 String?   @db.VarChar(12)
  tabNumber           String?   @db.VarChar(10)
}
```
SQL Query was already mentioned, but just to repeat
```
SELECT [dbo].[people_List].[id_People], [dbo].[people_List].[Surname], [dbo].[people_List].[Name], [dbo].[people_List].[Patronymic], [dbo].[people_List].[OldSurname], [dbo].[people_List].[OldName], [dbo].[people_List].[OldPatronymic], [dbo].[people_List].[Marriage], [dbo].[people_List].[Sex], [dbo].[people_List].[BornDate], [dbo].[people_List].[BornPlace], [dbo].[people_List].[id_Doc], [dbo].[people_List].[DocSerial], [dbo].[people_List].[DocNo], [dbo].[people_List].[DocDistributed], [dbo].[people_List].[DocDate], [dbo].[people_List].[DocDepartmentCode], [dbo].[people_List].[id_Sitizen], [dbo].[people_List].[Photo], [dbo].[people_List].[Other], [dbo].[people_List].[is_webimported], [dbo].[people_List].[id_web], [dbo].[people_List].[FIO], [dbo].[people_List].[FIO2], [dbo].[people_List].[msrepl_tran_version], [dbo].[people_List].[SurnameRP], [dbo].[people_List].[NameRP], [dbo].[people_List].[PatronymicRP], [dbo].[people_List].[id_Nationality_old], [dbo].[people_List].[id_Nationality], [dbo].[people_List].[UID], [dbo].[people_List].[UID_stat], [dbo].[people_List].[UID_sok], [dbo].[people_List].[UID_zo], [dbo].[people_List].[INN_old], [dbo].[people_List].[SSN], [dbo].[people_List].[INN], [dbo].[people_List].[tabNumber] FROM [dbo].[people_List] WHERE 1=1"
```
A bit lost at word "full sql table" so I will share an image of that table with its columns
![image](https://user-images.githubusercontent.com/23732658/120913685-d3dff100-c6d3-11eb-98bf-6b029b176028.png)

**Comment by janpio** [comment]
Thanks. Did you create the SQL table with Prisma Migrate (`migrate dev` or `db push` for example) or did you already have it? SQL UIs usually have a button to export the DDL or SQL needed to create the exact same table. 

(But we can try with the data we have already)

**Comment by BJladika** [comment]
Its a table from the real database (kinda, backup file didnt contail all data/rows) with a lot of tables, which was restored via .bak file with MS SQL Server Studio on my localhost for testing purposes. I dunno how to copy exactly the table, though I could try to send .bak of database if you need, although its a pretty confidential theme.

**Comment by BJladika** [comment]
Oh, wait, got the script of creating table (columns), though I guess it will be empty
```
/****** Object:  Table [dbo].[people_List]    Script Date: 06.06.2021 18:17:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[people_List](
	[id_People] [int] NOT NULL,
	[Surname] [varchar](30) NOT NULL,
	[Name] [varchar](30) NOT NULL,
	[Patronymic] [varchar](30) NULL,
	[OldSurname] [varchar](30) NULL,
	[OldName] [varchar](30) NULL,
	[OldPatronymic] [varchar](30) NULL,
	[Marriage] [bit] NOT NULL,
	[Sex] [char](1) NOT NULL,
	[BornDate] [datetime] NOT NULL,
	[BornPlace] [varchar](100) NULL,
	[id_Doc] [smallint] NOT NULL,
	[DocSerial] [varchar](10) NOT NULL,
	[DocNo] [varchar](30) NOT NULL,
	[DocDistributed] [varchar](150) NULL,
	[DocDate] [datetime] NULL,
	[DocDepartmentCode] [varchar](50) NULL,
	[id_Sitizen] [smallint] NOT NULL,
	[Photo] [image] NULL,
	[Other] [text] NULL,
	[is_webimported] [bit] NOT NULL,
	[id_web] [int] NULL,
	[FIO] [varchar](92) NOT NULL,
	[FIO2] [varchar](125) NULL,
	[msrepl_tran_version] [uniqueidentifier] NOT NULL,
	[SurnameRP] [varchar](30) NULL,
	[NameRP] [varchar](30) NULL,
	[PatronymicRP] [varchar](30) NULL,
	[id_Nationality_old] [int] NULL,
	[id_Nationality] [int] NULL,
	[UID] [int] NULL,
	[UID_stat] [int] NULL,
	[UID_sok] [int] NULL,
	[UID_zo] [int] NULL,
	[INN_old] [bigint] NULL,
	[SSN] [varchar](255) NULL,
	[INN] [varchar](12) NULL,
	[tabNumber] [varchar](10) NULL,
 CONSTRAINT [PK_people_List] PRIMARY KEY CLUSTERED 
(
	[id_People] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

**Comment by janpio** [comment]
Thanks, that is perfect. With that someone will try to reproduce this soon - and if it is indeed the data causing the error, we will ask for that later.

**Comment by pimeys** [comment]
Hey, so are you using `VarChar` to store non-ascii data? What I suspect is that we don't have the right collation data in the library, and try to read the data as UTF-8. This should just work with `NVarChar` columns, but we don't really test with `VarChar` and non-ascii...

**Comment by BJladika** [comment]
Can you elaborate on non-ascii data? It contains cyrillic symbols (aka russian language), dunno if its non-ascii or not...
But after your question I've tested additionally and finally found out that the filed on Prisma.schema  
`Sex                 String    @db.Char(1)` 
used cyrillic language and after removing it from schema it finally now works. I guess the problem is solved, kinda.

**Comment by pimeys** [comment]
This is an extremely interesting issue, I'll take a look for sure.

I was originally thinking it might be some of the `@db.VarChar` fields holding data we can't read correctly.

Can you provide me an example of a value in `@db.Char(1)` field that breaks Prisma? I can write a test and fix that then.

**Comment by BJladika** [comment]
Ofc, its 1 symbols meaning Sex of human like male/female but in russian symbols, `М` or `Ж`
![image](https://user-images.githubusercontent.com/23732658/121206987-def17780-c8b3-11eb-92d2-53c01d3a24df.png)

**Comment by pimeys** [comment]
Cool. Thanks for an excellent reproduction. I'll try to spin up a dockerized server with the right collation, and see what's wrong in our `CHAR` parsing code.

**Comment by pimeys** [comment]
So, you have cyrillic symbols in the `VarChar` fields too and they do work?

**Comment by BJladika** [comment]
Yep, they work fine, at least I'm now running queries without any crashes

**Comment by pimeys** [comment]
I think the `NChar` would work here just fine, but I need to fix the `Char` handling.

**Comment by pimeys** [comment]
Hey @BJladika we just published a special version for you to test a bit: `2.25.0-integration-sql-server-char-collation-fix.2`. Could you try this out, try reading that `CHAR(1)` value and see the result. Also, would be interested to know if you can write to the `VARCHAR` and `CHAR` columns successfully. We definitely have some areas in non-UTF column types we haven't covered, and if this does not work out, I'm trying to do an installation of SQL Server that can talk this collation and try to reproduce the problems by myself.

**Comment by BJladika** [comment]
Can you give me a hint how to change to this version?

**Comment by pimeys** [comment]
``bash
npm install prisma@2.25.0-integration-sql-server-char-collation-fix.2 --save-dev
```
Or set it in your `package.json`.

**Comment by pimeys** [comment]
In npm: https://www.npmjs.com/package/prisma/v/2.25.0-integration-sql-server-char-collation-fix.2

**Comment by BJladika** [comment]
Well, seems like its not working?
```
  "dependencies": {
    "@prisma/client": "2.24.1",
    "apollo-server": "2.25.0",
    "graphql": "15.5.0",
    "graphql-scalars": "1.9.3"
  },
  "devDependencies": {
    "prisma": "^2.25.0-integration-sql-server-char-collation-fix.2"
  },
```
Still facing that error with query or I must also update prisma client?

**Comment by pimeys** [comment]
yeah you should also update the client!

I got a database now with `Cyrillic_General_CI_AS` as the collation. Created a table with `CHAR(1)` and `VARCHAR(255)` columns, and added a row there with `Ж` and `ЖЖЖЖЖЖЖЖ` written to the columns. On the current prisma master I get `UTF-8 error` and on my branch, the data is loaded correctly:

```bash
❯ cargo run --example async-std
   Compiling tiberius v0.5.13 (/home/pimeys/code/tiberius)
    Finished dev [unoptimized + debuginfo] target(s) in 4.92s
     Running `target/debug/examples/async-std`
Row { columns: [Column { name: "id", column_type: Int4 }, Column { name: "data", column_type: BigChar }, Column { name: "data2", column_type: BigVarChar }], data: TokenRow { data: [I32(Some(1)), String(Some("Ж")), String(Some("ЖЖЖЖЖЖЖЖ"))] } }
```

I might want to try to write a test for this issue...

**Comment by pimeys** [comment]
You might need to run `prisma generate` too to get the correct engine.

**Comment by BJladika** [comment]
Well, i tried to use `npm install @prisma/client@2.25.0-integration-sql-server-char-collation-fix.2 --save-dev` and via changing depencies to `@prisma/client": "2.25.0-integration-sql-server-char-collation-fix.2"` but only getting error
``` 
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\Projects\graphql-sdl-first\node_modules\@prisma\engines-version
npm ERR! dest C:\Projects\graphql-sdl-first\node_modules\@prisma\.engines-version-SMIlxHHf
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Projects\graphql-sdl-first\node_modules\@prisma\engines-version' -> 'C:\Projects\Diplom_Work\graphql-sdl-first\node_modules\@prisma\.engines-version-SMIlxHHf'
npm ERR!  [Error: EPERM: operation not permitted, rename 'C:\Projects\graphql-sdl-first\node_modules\@prisma\engines-version' -> 'C:\Projects\graphql-sdl-first\node_modules\@prisma\.engines-version-SMIlxHHf'] {
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Projects\\graphql-sdl-first\\node_modules\\@prisma\\engines-version',
npm ERR!   dest: 'C:\\Projects\\graphql-sdl-first\\node_modules\\@prisma\\.engines-version-SMIlxHHf'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
```

**Comment by janpio** [comment]
Hey @BJladika, Node on Windows sometimes can be a pain - I also get this message from time to time. Maybe uninstall `prisma` and `@prisma/client` first (`npm uninstall prisma @prisma/client`)  and then install it again (the commands you posted above). Sometimes it also helps to run the commands a few more times. The less tools and programs are open, the less probably it is that one of them is blocking the file access.

**Comment by BJladika** [comment]
Yeah, ran a query now with an updated (aka reinstalled) `@prisma/client` and `prisma` to 25.0 version and now I'm not receiving error and can receive Char string. About mutations... well, maybe will write/test later, now a bit busy

![image](https://user-images.githubusercontent.com/23732658/121345196-85df1d80-c95f-11eb-989a-a2fcd18159db.png)

**Comment by pimeys** [comment]
The pull request above fixes it and adds a test so we don't get a regression in the future. I noticed the type `TEXT` was also broken in a similar way.

**Comment by pimeys** [comment]
This will be fully available in the 2.25.0 version on next week.

**Comment by janpio** [comment]
Can you confirm this worked in our `latest` now @BJladika?

**Comment by Allislove** [comment]
There is a guide to understand why happens this, i solve my error with the docs of this url

http://www.sql-server-helper.com/error-messages/msg-8115-numeric-to-numeric.aspx
