### ISSUE TITLE
Custom `@default(dbgenerated("..."))` value creates repeated migration scripts

### ISSUE THREAD

**Issue by TomiHiltunen** [prisma/prisma#9823]
### Bug description

A schema with a certain value for a DateTime column will repeatedly produce new `ALTER TABLE` statements in following migrations (see "Prisma information" segment). Regardless of the repeated migration, the definition itself produces a migration that does exactly what is expected. The issue is just the repetition of the statement in all the following migrations.

### How to reproduce

1. Create schema based on the information under "Prisma information".
2. Run `npx prisma migrate dev`.
3. Add some other field (any) to the schema.
4. Run `npx prisma migrate dev`.
5. Observe the created migrations and notice the `ALTER TABLE` being repeated in all the following migrations.

### Expected behavior

Only the first migration after adding the specific column to schema should produce the associated `ALTER TABLE` statement.

### Prisma information

**Schema:**
```
model Invitation {
  expiresAt      DateTime             @default(dbgenerated("NOW() + INTERVAL '7 DAYS'"))
  ...
}
```

**The migration that keeps repeating:**
```
-- AlterTable
ALTER TABLE "Invitation" ALTER COLUMN "expiresAt" SET DEFAULT NOW() + INTERVAL '7 DAYS';
```

### Environment & setup

- OS: MacOS
- Database: PostgreSQL
- Node.js version: v14.18.0 (LTS)

### Prisma Version

```
Environment variables loaded from .env
prisma                  : 3.2.1
@prisma/client          : 3.2.1
Current platform        : darwin
Query Engine (Node-API) : libquery-engine b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : b71d8cb16c4ddc7e3e9821f42fd09b0f82d7934c
Studio                  : 0.435.0
```

**Comment by massivefermion** [comment]
I'm also experiencing this bug using prisma 3.6.0 on linux with `@default(dbgenerated("extract(epoch from now())::bigint"))`.
I should also add that even if I don't change the schema at all and just run `npx prisma migrate dev`, prisma still creates a new migration with `alter table alter column` for only that column.

**Comment by janpio** [comment]
Thanks for these reports @TomiHiltunen and @massivefermion - that matches some other reports of `@default(dbgenerated(...))` sometimes being problematic by creating repeated migrations. (Examples: https://github.com/prisma/prisma/issues/8328 https://github.com/prisma/prisma/issues/7592) 

We collected these now and are aware they are related and should be fixed together - hopefully soon. 

(The problem is not `DateTime` related this time)

**Comment by burz** [comment]
This is still happening for me with `@default(dbgenerated("date_trunc('year', now())"))` on:
```
prisma                  : 3.8.1
@prisma/client          : 3.8.1
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f (at node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : 34df67547cf5598f5a6cd3eb45f14ee70c3fb86f
Studio                  : 0.452.0
```

**Comment by LeoAso** [comment]
I had a similar problem and solved it by following the discussion on #7592 ([this comment](https://github.com/prisma/prisma/issues/7592#issuecomment-874224714) in particular).

Apparently, the way you type in your default value is not exactly the way Postgres will store it. For example, my default value was `NOW() + INTERVAL '1 HOUR'`, but checking the column properties in PgAdmin, the default value was stored as `(now() + '01:00:00'::interval)`.

So until this issue is solved with Prisma, you'll have to copy the exact canonical representation of your value in the database and make sure that you write it exactly that way in `schema.prisma`. Then generate your migration again.

**Comment by knpwrs** [comment]
This was happening for me with the following schema:

```
model AppSession {
  expiresAt DateTime @default(dbgenerated("now() + interval '2 weeks'")) @map("expires_at")
}
```

It seems like this has been affecting many users:

- https://github.com/prisma/prisma/issues/8366
- https://github.com/prisma/prisma/issues/12915
- https://github.com/prisma/prisma/issues/5892
- https://github.com/prisma/prisma/issues/12212

That said, https://github.com/prisma/prisma/issues/9823#issuecomment-1177686869 worked for me! I had to update my schema as such:

```diff
   model AppSession {
-    expiresAt DateTime @default(dbgenerated("now() + interval '2 weeks'")) @map("expires_at")
+    expiresAt DateTime @default(dbgenerated("(now() + '14 days'::interval)"))
   }
```

Thank you, @LeoAso! It would be great to see Prisma support this somehow, or maybe at least produce a warning.

Should the other linked tickets be closed in favor of this one? It would make the process of finding this fix easier. Maybe for the time being the docs can be updated with a caveat or known issue or something.

**Comment by nerixim** [comment]
Thanks @LeoAso @knpwrs 
Posting my diff just for reference.

```diff
model Test {
-      expiresAt         DateTime  @default(dbgenerated("NOW() + interval '72 hour'")) # initial
-      expiresAt         DateTime  @default(dbgenerated("(NOW() + '72 hour'::interval)")) # wrong
+      expiresAt         DateTime  @default(dbgenerated("(now() + '72:00:00'::interval)")) # corrent
   }
```

**Comment by jaredatron** [comment]
having the same issue with  JSONB columns 
```prisma
model Things {
  …
  metadata Json @default(dbgenerated("'{}'::jsonb"))
}
```
makes migrations forever of
```sql
-- AlterTable
ALTER TABLE "Things" ALTER COLUMN "metadata" SET DEFAULT '{}'::jsonb;
```

**Comment by jaredatron** [comment]
fix:
```prisma
  metadata        Json     @default("{}")
```

**Comment by Fugguri** [comment]
for mysql(mariabd)  work with expires DateTime @default(dbgenerated("(now() + '72:00:00')"))

**Comment by chemalopezp** [comment]
We just found this, field
```

**Comment by marklai1998** [comment]
For those who're looking for the [answer](https://github.com/prisma/prisma/issues/5892#issuecomment-903045006)

Why:
Prisma will pull from db and compare with your local schema, sometime there are syntax diff from the db pull, making it think it has changed everytime

Solution:
Do `prisma db pull --print`, see whats prisma generated, replace it in your schema, done!

**Comment by hyoretsu** [comment]
Bump, this is really annoying and is still happening
```prisma
id          BigInt        @id @default(dbgenerated("generate_tsid('Movie')"))
```

**Comment by jkomyno** [comment]
Closing this as a duplicate in favour of https://github.com/prisma/prisma/issues/12574 (which despite being newer, has useful comments to avoid this issue).
